import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";

import { brand } from "@/config/brand";
import { site } from "@/config/site";
import { AppProviders } from "@/providers/app-providers";

import "./globals.css";

// Self-hosted (TEC-141): the build must not depend on fonts.googleapis.com.
// Files and OFL licenses live in ./fonts, regenerated by
// scripts/build-fonts.py. Each file is a variable font cut to the weights
// below; scripts a family lacks use the fallback stack in styles/theme.css.
const plusJakarta = localFont({
  src: "./fonts/plus-jakarta-sans-wght.woff2",
  variable: "--font-jakarta",
  weight: "400 700",
  display: "swap",
});

const outfit = localFont({
  src: "./fonts/outfit-wght.woff2",
  variable: "--font-outfit",
  weight: "500 700",
  display: "swap",
});

const jetbrainsMono = localFont({
  src: "./fonts/jetbrains-mono-wght.woff2",
  variable: "--font-jetbrains",
  weight: "400 500",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: brand.productName,
    template: `%s · ${brand.name}`,
  },
  description: brand.tagline,
  applicationName: brand.productName,
  openGraph: {
    type: "website",
    siteName: site.name,
    locale: site.locale,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: brand.colors.mist },
    { media: "(prefers-color-scheme: dark)", color: brand.colors.ink },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" suppressHydrationWarning className="h-full">
      <body
        className={`${plusJakarta.variable} ${outfit.variable} ${jetbrainsMono.variable} min-h-full font-sans antialiased`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
