// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAnnouncementAudience = `-- name: AddAnnouncementAudience :one
INSERT INTO announcement_audiences (announcement_id, target_type, role_slug, target_organization_id)
VALUES ($1, $2, $3, $4)
RETURNING id, announcement_id, target_type, role_slug, target_organization_id, created_at
`

type AddAnnouncementAudienceParams struct {
	AnnouncementID       int64       `json:"announcement_id"`
	TargetType           string      `json:"target_type"`
	RoleSlug             pgtype.Text `json:"role_slug"`
	TargetOrganizationID pgtype.Int8 `json:"target_organization_id"`
}

func (q *Queries) AddAnnouncementAudience(ctx context.Context, arg AddAnnouncementAudienceParams) (AnnouncementAudience, error) {
	row := q.db.QueryRow(ctx, addAnnouncementAudience,
		arg.AnnouncementID,
		arg.TargetType,
		arg.RoleSlug,
		arg.TargetOrganizationID,
	)
	var i AnnouncementAudience
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.TargetType,
		&i.RoleSlug,
		&i.TargetOrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const countAnnouncementReads = `-- name: CountAnnouncementReads :one
SELECT COUNT(*) FROM announcement_reads WHERE announcement_id = $1
`

func (q *Queries) CountAnnouncementReads(ctx context.Context, announcementID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnnouncementReads, announcementID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAnnouncementsByOrganizations = `-- name: CountAnnouncementsByOrganizations :one
SELECT COUNT(*) FROM announcements
WHERE organization_id = ANY($1::bigint[])
  AND ($2::varchar IS NULL OR status = $2::varchar)
`

type CountAnnouncementsByOrganizationsParams struct {
	OrganizationIds []int64     `json:"organization_ids"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CountAnnouncementsByOrganizations(ctx context.Context, arg CountAnnouncementsByOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnnouncementsByOrganizations, arg.OrganizationIds, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisibleAnnouncements = `-- name: CountVisibleAnnouncements :one
SELECT COUNT(*)
FROM announcements a
LEFT JOIN announcement_reads r
       ON r.announcement_id = a.id AND r.user_id = $1::bigint
WHERE a.brand_id = $2::bigint
  AND a.status = 'published'
  AND a.publish_at <= $3::timestamptz
  AND (a.expires_at IS NULL OR a.expires_at > $3::timestamptz)
  AND EXISTS (
      SELECT 1 FROM announcement_audiences au
      WHERE au.announcement_id = a.id
        AND (au.role_slug IS NULL OR au.role_slug = ANY($4::text[]))
        AND (
            au.target_type IN ('all_network', 'role')
            OR (au.target_type = 'distributors' AND $5::varchar = 'distributor')
            OR (au.target_type = 'dealers' AND $5::varchar = 'dealer')
            OR (au.target_type = 'subtree' AND au.target_organization_id = ANY($6::bigint[]))
        )
  )
  AND (NOT $7::boolean OR r.read_at IS NULL)
`

type CountVisibleAnnouncementsParams struct {
	UserID           int64              `json:"user_id"`
	BrandID          int64              `json:"brand_id"`
	Now              pgtype.Timestamptz `json:"now"`
	ViewerRoleSlugs  []string           `json:"viewer_role_slugs"`
	ViewerOrgType    string             `json:"viewer_org_type"`
	ViewerOrgLineage []int64            `json:"viewer_org_lineage"`
	UnreadOnly       bool               `json:"unread_only"`
}

func (q *Queries) CountVisibleAnnouncements(ctx context.Context, arg CountVisibleAnnouncementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVisibleAnnouncements,
		arg.UserID,
		arg.BrandID,
		arg.Now,
		arg.ViewerRoleSlugs,
		arg.ViewerOrgType,
		arg.ViewerOrgLineage,
		arg.UnreadOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one

INSERT INTO announcements (
    organization_id, brand_id, default_locale, title, body, body_format,
    status, pinned, notify, publish_at, expires_at, author_user_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12
)
RETURNING id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at
`

type CreateAnnouncementParams struct {
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	DefaultLocale  string             `json:"default_locale"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	BodyFormat     string             `json:"body_format"`
	Status         string             `json:"status"`
	Pinned         bool               `json:"pinned"`
	Notify         bool               `json:"notify"`
	PublishAt      pgtype.Timestamptz `json:"publish_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AuthorUserID   pgtype.Int8        `json:"author_user_id"`
}

// TEC-329 (F3-05a): announcements, their translations, audiences and read
// receipts (migration 000086).
func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.OrganizationID,
		arg.BrandID,
		arg.DefaultLocale,
		arg.Title,
		arg.Body,
		arg.BodyFormat,
		arg.Status,
		arg.Pinned,
		arg.Notify,
		arg.PublishAt,
		arg.ExpiresAt,
		arg.AuthorUserID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.DefaultLocale,
		&i.Title,
		&i.Body,
		&i.BodyFormat,
		&i.Status,
		&i.Pinned,
		&i.Notify,
		&i.PublishAt,
		&i.ExpiresAt,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements
WHERE id = $1 AND organization_id = $2 AND status = 'draft'
`

type DeleteAnnouncementParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAnnouncementAudiences = `-- name: DeleteAnnouncementAudiences :exec
DELETE FROM announcement_audiences WHERE announcement_id = $1
`

func (q *Queries) DeleteAnnouncementAudiences(ctx context.Context, announcementID int64) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementAudiences, announcementID)
	return err
}

const deleteAnnouncementLocale = `-- name: DeleteAnnouncementLocale :execrows
DELETE FROM announcement_locales
WHERE announcement_id = $1 AND locale = $2
`

type DeleteAnnouncementLocaleParams struct {
	AnnouncementID int64  `json:"announcement_id"`
	Locale         string `json:"locale"`
}

func (q *Queries) DeleteAnnouncementLocale(ctx context.Context, arg DeleteAnnouncementLocaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncementLocale, arg.AnnouncementID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at FROM announcements WHERE id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id int64) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.DefaultLocale,
		&i.Title,
		&i.Body,
		&i.BodyFormat,
		&i.Status,
		&i.Pinned,
		&i.Notify,
		&i.PublishAt,
		&i.ExpiresAt,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementByUUID = `-- name: GetAnnouncementByUUID :one
SELECT id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at FROM announcements WHERE uuid = $1
`

func (q *Queries) GetAnnouncementByUUID(ctx context.Context, argUuid uuid.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByUUID, argUuid)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.DefaultLocale,
		&i.Title,
		&i.Body,
		&i.BodyFormat,
		&i.Status,
		&i.Pinned,
		&i.Notify,
		&i.PublishAt,
		&i.ExpiresAt,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnouncementAudiences = `-- name: ListAnnouncementAudiences :many
SELECT id, announcement_id, target_type, role_slug, target_organization_id, created_at FROM announcement_audiences
WHERE announcement_id = $1
ORDER BY id
`

func (q *Queries) ListAnnouncementAudiences(ctx context.Context, announcementID int64) ([]AnnouncementAudience, error) {
	rows, err := q.db.Query(ctx, listAnnouncementAudiences, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementAudience{}
	for rows.Next() {
		var i AnnouncementAudience
		if err := rows.Scan(
			&i.ID,
			&i.AnnouncementID,
			&i.TargetType,
			&i.RoleSlug,
			&i.TargetOrganizationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementLocales = `-- name: ListAnnouncementLocales :many
SELECT id, announcement_id, locale, title, body, created_at, updated_at FROM announcement_locales
WHERE announcement_id = $1
ORDER BY locale
`

func (q *Queries) ListAnnouncementLocales(ctx context.Context, announcementID int64) ([]AnnouncementLocale, error) {
	rows, err := q.db.Query(ctx, listAnnouncementLocales, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementLocale{}
	for rows.Next() {
		var i AnnouncementLocale
		if err := rows.Scan(
			&i.ID,
			&i.AnnouncementID,
			&i.Locale,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementReadReport = `-- name: ListAnnouncementReadReport :many
SELECT u.uuid AS user_uuid, u.email, u.name, u.surname, r.read_at
FROM announcement_reads r
JOIN users u ON u.id = r.user_id AND u.deleted_at IS NULL
WHERE r.announcement_id = $1
ORDER BY r.read_at DESC
LIMIT $3 OFFSET $2
`

type ListAnnouncementReadReportParams struct {
	AnnouncementID int64 `json:"announcement_id"`
	PageOffset     int32 `json:"page_offset"`
	PageLimit      int32 `json:"page_limit"`
}

type ListAnnouncementReadReportRow struct {
	UserUuid uuid.UUID          `json:"user_uuid"`
	Email    pgtype.Text        `json:"email"`
	Name     string             `json:"name"`
	Surname  string             `json:"surname"`
	ReadAt   pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) ListAnnouncementReadReport(ctx context.Context, arg ListAnnouncementReadReportParams) ([]ListAnnouncementReadReportRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementReadReport, arg.AnnouncementID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementReadReportRow{}
	for rows.Next() {
		var i ListAnnouncementReadReportRow
		if err := rows.Scan(
			&i.UserUuid,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementReads = `-- name: ListAnnouncementReads :many
SELECT announcement_id, user_id, read_at FROM announcement_reads
WHERE announcement_id = $1
ORDER BY read_at DESC
LIMIT $3 OFFSET $2
`

type ListAnnouncementReadsParams struct {
	AnnouncementID int64 `json:"announcement_id"`
	PageOffset     int32 `json:"page_offset"`
	PageLimit      int32 `json:"page_limit"`
}

func (q *Queries) ListAnnouncementReads(ctx context.Context, arg ListAnnouncementReadsParams) ([]AnnouncementRead, error) {
	rows, err := q.db.Query(ctx, listAnnouncementReads, arg.AnnouncementID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnouncementRead{}
	for rows.Next() {
		var i AnnouncementRead
		if err := rows.Scan(&i.AnnouncementID, &i.UserID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementTargetUserIDs = `-- name: ListAnnouncementTargetUserIDs :many
WITH RECURSIVE subtree(root_id, id) AS (
    SELECT au.target_organization_id, au.target_organization_id
    FROM announcement_audiences au
    WHERE au.announcement_id = $1
      AND au.target_type = 'subtree'
      AND au.target_organization_id IS NOT NULL
    UNION ALL
    SELECT s.root_id, o.id
    FROM subtree s
    JOIN organizations o ON o.parent_id = s.id AND o.deleted_at IS NULL
)
SELECT DISTINCT om.user_id
FROM announcements a
JOIN organization_members om ON TRUE
JOIN organizations o ON o.id = om.organization_id AND o.deleted_at IS NULL
WHERE a.id = $1
  AND a.brand_id = o.brand_id
  AND EXISTS (
      SELECT 1
      FROM announcement_audiences au
      WHERE au.announcement_id = a.id
        AND (
            au.role_slug IS NULL
            OR EXISTS (
                SELECT 1
                FROM organization_member_roles mr
                JOIN roles r ON r.id = mr.role_id
                WHERE mr.member_id = om.id AND r.slug = au.role_slug
            )
        )
        AND (
            au.target_type IN ('all_network', 'role')
            OR (au.target_type = 'distributors' AND o.type = 'distributor')
            OR (au.target_type = 'dealers' AND o.type = 'dealer')
            OR (au.target_type = 'subtree' AND EXISTS (
                SELECT 1 FROM subtree s WHERE s.root_id = au.target_organization_id AND s.id = o.id
            ))
        )
  )
ORDER BY om.user_id
`

func (q *Queries) ListAnnouncementTargetUserIDs(ctx context.Context, announcementID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAnnouncementTargetUserIDs, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementsByOrganizations = `-- name: ListAnnouncementsByOrganizations :many
SELECT id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at FROM announcements
WHERE organization_id = ANY($1::bigint[])
  AND ($2::varchar IS NULL OR status = $2::varchar)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListAnnouncementsByOrganizationsParams struct {
	OrganizationIds []int64     `json:"organization_ids"`
	Status          pgtype.Text `json:"status"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

// Author view: announcements written by the given organizations (the
// caller's resolved write scope), newest first.
func (q *Queries) ListAnnouncementsByOrganizations(ctx context.Context, arg ListAnnouncementsByOrganizationsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsByOrganizations,
		arg.OrganizationIds,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.DefaultLocale,
			&i.Title,
			&i.Body,
			&i.BodyFormat,
			&i.Status,
			&i.Pinned,
			&i.Notify,
			&i.PublishAt,
			&i.ExpiresAt,
			&i.AuthorUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAnnouncements = `-- name: ListVisibleAnnouncements :many
SELECT
    a.id, a.uuid, a.organization_id, a.default_locale, a.body_format, a.pinned, a.publish_at, a.expires_at,
    COALESCE(l.locale, a.default_locale)::varchar AS locale,
    COALESCE(l.title, a.title)::varchar AS title,
    COALESCE(l.body, a.body)::text AS body,
    r.read_at
FROM announcements a
LEFT JOIN announcement_locales l
       ON l.announcement_id = a.id AND l.locale = $1::varchar
LEFT JOIN announcement_reads r
       ON r.announcement_id = a.id AND r.user_id = $2::bigint
WHERE a.brand_id = $3::bigint
  AND a.status = 'published'
  AND a.publish_at <= $4::timestamptz
  AND (a.expires_at IS NULL OR a.expires_at > $4::timestamptz)
  AND EXISTS (
      SELECT 1 FROM announcement_audiences au
      WHERE au.announcement_id = a.id
        AND (au.role_slug IS NULL OR au.role_slug = ANY($5::text[]))
        AND (
            au.target_type IN ('all_network', 'role')
            OR (au.target_type = 'distributors' AND $6::varchar = 'distributor')
            OR (au.target_type = 'dealers' AND $6::varchar = 'dealer')
            OR (au.target_type = 'subtree' AND au.target_organization_id = ANY($7::bigint[]))
        )
  )
  AND (NOT $8::boolean OR r.read_at IS NULL)
ORDER BY a.pinned DESC, a.publish_at DESC, a.id DESC
LIMIT $10 OFFSET $9
`

type ListVisibleAnnouncementsParams struct {
	Locale           string             `json:"locale"`
	UserID           int64              `json:"user_id"`
	BrandID          int64              `json:"brand_id"`
	Now              pgtype.Timestamptz `json:"now"`
	ViewerRoleSlugs  []string           `json:"viewer_role_slugs"`
	ViewerOrgType    string             `json:"viewer_org_type"`
	ViewerOrgLineage []int64            `json:"viewer_org_lineage"`
	UnreadOnly       bool               `json:"unread_only"`
	PageOffset       int32              `json:"page_offset"`
	PageLimit        int32              `json:"page_limit"`
}

type ListVisibleAnnouncementsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	DefaultLocale  string             `json:"default_locale"`
	BodyFormat     string             `json:"body_format"`
	Pinned         bool               `json:"pinned"`
	PublishAt      pgtype.Timestamptz `json:"publish_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Locale         string             `json:"locale"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

// Reader feed: published, inside its window, in the viewer's brand and
// matching at least one audience row. viewer_org_lineage is the viewer
// organization followed by its ancestors (subtree targets match any of
// them); viewer_role_slugs are the viewer's role slugs in that
// organization. locale picks the translation, falling back to the default
// text.
func (q *Queries) ListVisibleAnnouncements(ctx context.Context, arg ListVisibleAnnouncementsParams) ([]ListVisibleAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleAnnouncements,
		arg.Locale,
		arg.UserID,
		arg.BrandID,
		arg.Now,
		arg.ViewerRoleSlugs,
		arg.ViewerOrgType,
		arg.ViewerOrgLineage,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleAnnouncementsRow{}
	for rows.Next() {
		var i ListVisibleAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.DefaultLocale,
			&i.BodyFormat,
			&i.Pinned,
			&i.PublishAt,
			&i.ExpiresAt,
			&i.Locale,
			&i.Title,
			&i.Body,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnnouncementRead = `-- name: MarkAnnouncementRead :one
INSERT INTO announcement_reads (announcement_id, user_id)
VALUES ($1, $2)
ON CONFLICT (announcement_id, user_id) DO UPDATE SET read_at = announcement_reads.read_at
RETURNING announcement_id, user_id, read_at
`

type MarkAnnouncementReadParams struct {
	AnnouncementID int64 `json:"announcement_id"`
	UserID         int64 `json:"user_id"`
}

// Idempotent: a second read keeps the first read_at.
func (q *Queries) MarkAnnouncementRead(ctx context.Context, arg MarkAnnouncementReadParams) (AnnouncementRead, error) {
	row := q.db.QueryRow(ctx, markAnnouncementRead, arg.AnnouncementID, arg.UserID)
	var i AnnouncementRead
	err := row.Scan(&i.AnnouncementID, &i.UserID, &i.ReadAt)
	return i, err
}

const organizationLineage = `-- name: OrganizationLineage :many
WITH RECURSIVE lineage(id, parent_id, depth) AS (
    SELECT id, parent_id, 0
    FROM organizations
    WHERE id = $1::bigint AND deleted_at IS NULL
    UNION ALL
    SELECT p.id, p.parent_id, lineage.depth + 1
    FROM lineage
    JOIN organizations p ON p.id = lineage.parent_id AND p.deleted_at IS NULL
    WHERE lineage.depth < 16
)
SELECT id FROM lineage ORDER BY depth ASC
`

func (q *Queries) OrganizationLineage(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, organizationLineage, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAnnouncementStatus = `-- name: SetAnnouncementStatus :one
UPDATE announcements
SET status     = $1::varchar,
    publish_at = CASE
        WHEN $1::varchar = 'published' AND publish_at IS NULL THEN NOW()
        ELSE publish_at
    END
WHERE id = $2 AND organization_id = $3
RETURNING id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at
`

type SetAnnouncementStatusParams struct {
	Status         string `json:"status"`
	ID             int64  `json:"id"`
	OrganizationID int64  `json:"organization_id"`
}

// publish_at is stamped with NOW() when a row is published without one.
func (q *Queries) SetAnnouncementStatus(ctx context.Context, arg SetAnnouncementStatusParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, setAnnouncementStatus, arg.Status, arg.ID, arg.OrganizationID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.DefaultLocale,
		&i.Title,
		&i.Body,
		&i.BodyFormat,
		&i.Status,
		&i.Pinned,
		&i.Notify,
		&i.PublishAt,
		&i.ExpiresAt,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET default_locale = $1,
    title          = $2,
    body           = $3,
    body_format    = $4,
    pinned         = $5,
    notify         = $6,
    publish_at     = $7,
    expires_at     = $8
WHERE id = $9 AND organization_id = $10
RETURNING id, uuid, organization_id, brand_id, default_locale, title, body, body_format, status, pinned, notify, publish_at, expires_at, author_user_id, created_at, updated_at
`

type UpdateAnnouncementParams struct {
	DefaultLocale  string             `json:"default_locale"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	BodyFormat     string             `json:"body_format"`
	Pinned         bool               `json:"pinned"`
	Notify         bool               `json:"notify"`
	PublishAt      pgtype.Timestamptz `json:"publish_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ID             int64              `json:"id"`
	OrganizationID int64              `json:"organization_id"`
}

// Content and flags of an announcement written by the organization.
func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.DefaultLocale,
		arg.Title,
		arg.Body,
		arg.BodyFormat,
		arg.Pinned,
		arg.Notify,
		arg.PublishAt,
		arg.ExpiresAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.DefaultLocale,
		&i.Title,
		&i.Body,
		&i.BodyFormat,
		&i.Status,
		&i.Pinned,
		&i.Notify,
		&i.PublishAt,
		&i.ExpiresAt,
		&i.AuthorUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAnnouncementLocale = `-- name: UpsertAnnouncementLocale :one
INSERT INTO announcement_locales (announcement_id, locale, title, body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (announcement_id, locale)
DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body
RETURNING id, announcement_id, locale, title, body, created_at, updated_at
`

type UpsertAnnouncementLocaleParams struct {
	AnnouncementID int64  `json:"announcement_id"`
	Locale         string `json:"locale"`
	Title          string `json:"title"`
	Body           string `json:"body"`
}

func (q *Queries) UpsertAnnouncementLocale(ctx context.Context, arg UpsertAnnouncementLocaleParams) (AnnouncementLocale, error) {
	row := q.db.QueryRow(ctx, upsertAnnouncementLocale,
		arg.AnnouncementID,
		arg.Locale,
		arg.Title,
		arg.Body,
	)
	var i AnnouncementLocale
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.Locale,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
