// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dealer_sales_lists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDealerPriceCatalog = `-- name: CountDealerPriceCatalog :one
SELECT COUNT(*)
FROM products p
LEFT JOIN dealer_product_prices dp
       ON dp.product_id = p.id AND dp.organization_id = $1
WHERE p.brand_id = $2
  AND ((p.active AND p.unit_type = 'piece') OR dp.id IS NOT NULL)
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3::text || '%' OR p.sku ILIKE '%' || $3::text || '%')
  AND ($4::boolean IS NULL OR (dp.id IS NOT NULL) = $4::boolean)
`

type CountDealerPriceCatalogParams struct {
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	Q              pgtype.Text `json:"q"`
	Priced         pgtype.Bool `json:"priced"`
}

func (q *Queries) CountDealerPriceCatalog(ctx context.Context, arg CountDealerPriceCatalogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDealerPriceCatalog,
		arg.OrganizationID,
		arg.BrandID,
		arg.Q,
		arg.Priced,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductSalesPage = `-- name: CountProductSalesPage :one
WITH sales AS (
    SELECT s.id, s.uuid, s.organization_id, s.brand_id, s.customer_user_id, s.payment_method, s.cari_id, s.currency, s.total, s.sold_at, s.note, s.finance_entry_id, s.created_by_user_id, s.created_at, s.updated_at,
           COALESCE(NULLIF(btrim(u.name || ' ' || u.surname), ''), '') AS customer_name,
           NOT EXISTS (
               SELECT 1 FROM finance_entries e
               WHERE e.source_type = 'product_sale' AND e.source_uuid = s.uuid
                 AND e.reversal_of_id IS NULL
                 AND NOT EXISTS (SELECT 1 FROM finance_entries r WHERE r.reversal_of_id = e.id)
           ) AS voided
    FROM product_sales s
    LEFT JOIN users u ON u.id = s.customer_user_id
    WHERE s.organization_id = $8
)
SELECT COUNT(*)
FROM sales s
WHERE (COALESCE(cardinality($1::text[]), 0) = 0
       OR s.payment_method = ANY ($1::text[]))
  AND ($2::boolean IS NULL OR s.voided = $2::boolean)
  AND ($3::timestamptz IS NULL OR s.sold_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR s.sold_at < $4::timestamptz)
  AND ($5::numeric IS NULL OR s.total >= $5::numeric)
  AND ($6::numeric IS NULL OR s.total <= $6::numeric)
  AND ($7::text IS NULL
       OR s.customer_name ILIKE '%' || $7::text || '%'
       OR s.note ILIKE '%' || $7::text || '%'
       OR EXISTS (
           SELECT 1 FROM product_sale_lines l
           JOIN products p ON p.id = l.product_id
           LEFT JOIN units un ON un.id = l.unit_id
           WHERE l.sale_id = s.id
             AND (p.name ILIKE '%' || $7::text || '%' OR un.barcode = $7::text)
       ))
`

type CountProductSalesPageParams struct {
	PaymentMethods []string           `json:"payment_methods"`
	Voided         pgtype.Bool        `json:"voided"`
	SoldFrom       pgtype.Timestamptz `json:"sold_from"`
	SoldBefore     pgtype.Timestamptz `json:"sold_before"`
	TotalMin       pgtype.Numeric     `json:"total_min"`
	TotalMax       pgtype.Numeric     `json:"total_max"`
	Q              pgtype.Text        `json:"q"`
	OrganizationID int64              `json:"organization_id"`
}

func (q *Queries) CountProductSalesPage(ctx context.Context, arg CountProductSalesPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSalesPage,
		arg.PaymentMethods,
		arg.Voided,
		arg.SoldFrom,
		arg.SoldBefore,
		arg.TotalMin,
		arg.TotalMax,
		arg.Q,
		arg.OrganizationID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchasesPage = `-- name: CountPurchasesPage :one
SELECT COUNT(*)
FROM purchases pu
JOIN suppliers su ON su.id = pu.supplier_id
WHERE pu.organization_id = $1
  AND (COALESCE(cardinality($2::uuid[]), 0) = 0
       OR su.uuid = ANY ($2::uuid[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0
       OR pu.payment_method = ANY ($3::text[]))
  AND ($4::date IS NULL OR pu.purchased_on >= $4::date)
  AND ($5::date IS NULL OR pu.purchased_on < $5::date)
  AND ($6::numeric IS NULL OR pu.amount >= $6::numeric)
  AND ($7::numeric IS NULL OR pu.amount <= $7::numeric)
  AND ($8::text IS NULL
       OR su.name ILIKE '%' || $8::text || '%'
       OR pu.note ILIKE '%' || $8::text || '%'
       OR EXISTS (SELECT 1 FROM purchase_lines l WHERE l.purchase_id = pu.id
                  AND l.description ILIKE '%' || $8::text || '%'))
`

type CountPurchasesPageParams struct {
	OrganizationID int64          `json:"organization_id"`
	SupplierUuids  []uuid.UUID    `json:"supplier_uuids"`
	PaymentMethods []string       `json:"payment_methods"`
	DateFrom       pgtype.Date    `json:"date_from"`
	DateBefore     pgtype.Date    `json:"date_before"`
	AmountMin      pgtype.Numeric `json:"amount_min"`
	AmountMax      pgtype.Numeric `json:"amount_max"`
	Q              pgtype.Text    `json:"q"`
}

func (q *Queries) CountPurchasesPage(ctx context.Context, arg CountPurchasesPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchasesPage,
		arg.OrganizationID,
		arg.SupplierUuids,
		arg.PaymentMethods,
		arg.DateFrom,
		arg.DateBefore,
		arg.AmountMin,
		arg.AmountMax,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppliersPage = `-- name: CountSuppliersPage :one
SELECT COUNT(*) FROM suppliers
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR active = $2::boolean)
  AND ($3::text IS NULL
       OR name ILIKE '%' || $3::text || '%'
       OR tax_no ILIKE '%' || $3::text || '%'
       OR phone_e164 ILIKE '%' || $3::text || '%'
       OR email ILIKE '%' || $3::text || '%')
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
`

type CountSuppliersPageParams struct {
	OrganizationID int64              `json:"organization_id"`
	Active         pgtype.Bool        `json:"active"`
	Q              pgtype.Text        `json:"q"`
	CreatedFrom    pgtype.Timestamptz `json:"created_from"`
	CreatedBefore  pgtype.Timestamptz `json:"created_before"`
}

func (q *Queries) CountSuppliersPage(ctx context.Context, arg CountSuppliersPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliersPage,
		arg.OrganizationID,
		arg.Active,
		arg.Q,
		arg.CreatedFrom,
		arg.CreatedBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDealerPriceCatalog = `-- name: ListDealerPriceCatalog :many


SELECT p.id AS product_id, p.uuid AS product_uuid, p.sku, p.name, p.uses_fixed_barcode,
       dp.sale_price, dp.currency AS sale_currency, dp.updated_at AS price_updated_at,
       pp.recommended_sale_price
FROM products p
LEFT JOIN dealer_product_prices dp
       ON dp.product_id = p.id AND dp.organization_id = $1
LEFT JOIN product_prices pp
       ON pp.product_id = p.id AND pp.brand_id = p.brand_id AND pp.currency = $2::text
WHERE p.brand_id = $3
  AND ((p.active AND p.unit_type = 'piece') OR dp.id IS NOT NULL)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4::text || '%' OR p.sku ILIKE '%' || $4::text || '%')
  AND ($5::boolean IS NULL OR (dp.id IS NOT NULL) = $5::boolean)
ORDER BY
  CASE WHEN NOT $6::bool THEN
    CASE $7::text WHEN 'name' THEN p.name WHEN 'sku' THEN p.sku END
  END ASC,
  CASE WHEN $6::bool THEN
    CASE $7::text WHEN 'name' THEN p.name WHEN 'sku' THEN p.sku END
  END DESC,
  CASE WHEN NOT $6::bool AND $7::text = 'sale_price' THEN dp.sale_price END ASC NULLS LAST,
  CASE WHEN $6::bool AND $7::text = 'sale_price' THEN dp.sale_price END DESC NULLS LAST,
  CASE WHEN NOT $6::bool AND $7::text = 'recommended_sale_price' THEN pp.recommended_sale_price END ASC NULLS LAST,
  CASE WHEN $6::bool AND $7::text = 'recommended_sale_price' THEN pp.recommended_sale_price END DESC NULLS LAST,
  CASE WHEN NOT $6::bool AND $7::text = 'updated_at' THEN dp.updated_at END ASC NULLS LAST,
  CASE WHEN $6::bool AND $7::text = 'updated_at' THEN dp.updated_at END DESC NULLS LAST,
  CASE WHEN $6::bool THEN p.id END DESC,
  p.id ASC
LIMIT $9 OFFSET $8
`

type ListDealerPriceCatalogParams struct {
	OrganizationID int64       `json:"organization_id"`
	Currency       string      `json:"currency"`
	BrandID        int64       `json:"brand_id"`
	Q              pgtype.Text `json:"q"`
	Priced         pgtype.Bool `json:"priced"`
	SortDesc       bool        `json:"sort_desc"`
	SortKey        string      `json:"sort_key"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListDealerPriceCatalogRow struct {
	ProductID            int64              `json:"product_id"`
	ProductUuid          uuid.UUID          `json:"product_uuid"`
	Sku                  string             `json:"sku"`
	Name                 string             `json:"name"`
	UsesFixedBarcode     bool               `json:"uses_fixed_barcode"`
	SalePrice            pgtype.Numeric     `json:"sale_price"`
	SaleCurrency         pgtype.Text        `json:"sale_currency"`
	PriceUpdatedAt       pgtype.Timestamptz `json:"price_updated_at"`
	RecommendedSalePrice pgtype.Numeric     `json:"recommended_sale_price"`
}

// TEC-348 (F3-07h): paged list reads of the dealer sales screens (sale
// prices, quick sales, suppliers, purchases). Sort keys come from the
// dealeraccounting handler specs (docs/list-contract.md); every read is
// bounded by the dealer organization the API layer resolved.
// ---------------------------------------------------------------------------
// Sale price catalog: the brand's active piece products (plus any product
// the dealer already priced) with the dealer's own price and the brand's
// recommended price.
func (q *Queries) ListDealerPriceCatalog(ctx context.Context, arg ListDealerPriceCatalogParams) ([]ListDealerPriceCatalogRow, error) {
	rows, err := q.db.Query(ctx, listDealerPriceCatalog,
		arg.OrganizationID,
		arg.Currency,
		arg.BrandID,
		arg.Q,
		arg.Priced,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealerPriceCatalogRow{}
	for rows.Next() {
		var i ListDealerPriceCatalogRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductUuid,
			&i.Sku,
			&i.Name,
			&i.UsesFixedBarcode,
			&i.SalePrice,
			&i.SaleCurrency,
			&i.PriceUpdatedAt,
			&i.RecommendedSalePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductSalesPage = `-- name: ListProductSalesPage :many

WITH sales AS (
    SELECT s.id, s.uuid, s.organization_id, s.brand_id, s.customer_user_id, s.payment_method, s.cari_id, s.currency, s.total, s.sold_at, s.note, s.finance_entry_id, s.created_by_user_id, s.created_at, s.updated_at,
           COALESCE(NULLIF(btrim(u.name || ' ' || u.surname), ''), '') AS customer_name,
           u.uuid AS customer_uuid,
           NOT EXISTS (
               SELECT 1 FROM finance_entries e
               WHERE e.source_type = 'product_sale' AND e.source_uuid = s.uuid
                 AND e.reversal_of_id IS NULL
                 AND NOT EXISTS (SELECT 1 FROM finance_entries r WHERE r.reversal_of_id = e.id)
           ) AS voided
    FROM product_sales s
    LEFT JOIN users u ON u.id = s.customer_user_id
    WHERE s.organization_id = $12
)
SELECT s.id, s.uuid, s.payment_method, s.currency, s.total, s.sold_at, s.note,
       s.customer_name::text AS customer_name, s.customer_uuid, s.voided::bool AS voided,
       (SELECT COUNT(*) FROM product_sale_lines l WHERE l.sale_id = s.id)::bigint AS line_count,
       (SELECT COALESCE(SUM(l.line_total - COALESCE(l.purchase_unit_cost * l.quantity, 0)), 0)
          FROM product_sale_lines l WHERE l.sale_id = s.id)::numeric(18,2) AS profit,
       (SELECT COALESCE(string_agg(p.name, ', ' ORDER BY l.sort_order, l.id), '')
          FROM product_sale_lines l JOIN products p ON p.id = l.product_id
          WHERE l.sale_id = s.id)::text AS products
FROM sales s
WHERE (COALESCE(cardinality($1::text[]), 0) = 0
       OR s.payment_method = ANY ($1::text[]))
  AND ($2::boolean IS NULL OR s.voided = $2::boolean)
  AND ($3::timestamptz IS NULL OR s.sold_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR s.sold_at < $4::timestamptz)
  AND ($5::numeric IS NULL OR s.total >= $5::numeric)
  AND ($6::numeric IS NULL OR s.total <= $6::numeric)
  AND ($7::text IS NULL
       OR s.customer_name ILIKE '%' || $7::text || '%'
       OR s.note ILIKE '%' || $7::text || '%'
       OR EXISTS (
           SELECT 1 FROM product_sale_lines l
           JOIN products p ON p.id = l.product_id
           LEFT JOIN units un ON un.id = l.unit_id
           WHERE l.sale_id = s.id
             AND (p.name ILIKE '%' || $7::text || '%' OR un.barcode = $7::text)
       ))
ORDER BY
  CASE WHEN NOT $8::bool AND $9::text = 'sold_at' THEN s.sold_at END ASC,
  CASE WHEN $8::bool AND $9::text = 'sold_at' THEN s.sold_at END DESC,
  CASE WHEN NOT $8::bool AND $9::text = 'total' THEN s.total END ASC,
  CASE WHEN $8::bool AND $9::text = 'total' THEN s.total END DESC,
  CASE WHEN NOT $8::bool AND $9::text = 'payment_method' THEN s.payment_method END ASC,
  CASE WHEN $8::bool AND $9::text = 'payment_method' THEN s.payment_method END DESC,
  CASE WHEN $8::bool THEN s.id END DESC,
  s.id ASC
LIMIT $11 OFFSET $10
`

type ListProductSalesPageParams struct {
	PaymentMethods []string           `json:"payment_methods"`
	Voided         pgtype.Bool        `json:"voided"`
	SoldFrom       pgtype.Timestamptz `json:"sold_from"`
	SoldBefore     pgtype.Timestamptz `json:"sold_before"`
	TotalMin       pgtype.Numeric     `json:"total_min"`
	TotalMax       pgtype.Numeric     `json:"total_max"`
	Q              pgtype.Text        `json:"q"`
	SortDesc       bool               `json:"sort_desc"`
	SortKey        string             `json:"sort_key"`
	OffsetCount    int32              `json:"offset_count"`
	LimitCount     int32              `json:"limit_count"`
	OrganizationID int64              `json:"organization_id"`
}

type ListProductSalesPageRow struct {
	ID            int64              `json:"id"`
	Uuid          uuid.UUID          `json:"uuid"`
	PaymentMethod string             `json:"payment_method"`
	Currency      string             `json:"currency"`
	Total         pgtype.Numeric     `json:"total"`
	SoldAt        pgtype.Timestamptz `json:"sold_at"`
	Note          string             `json:"note"`
	CustomerName  string             `json:"customer_name"`
	CustomerUuid  pgtype.UUID        `json:"customer_uuid"`
	Voided        bool               `json:"voided"`
	LineCount     int64              `json:"line_count"`
	Profit        pgtype.Numeric     `json:"profit"`
	Products      string             `json:"products"`
}

// ---------------------------------------------------------------------------
// Quick sales. voided: the sale's income entry was reversed.
func (q *Queries) ListProductSalesPage(ctx context.Context, arg ListProductSalesPageParams) ([]ListProductSalesPageRow, error) {
	rows, err := q.db.Query(ctx, listProductSalesPage,
		arg.PaymentMethods,
		arg.Voided,
		arg.SoldFrom,
		arg.SoldBefore,
		arg.TotalMin,
		arg.TotalMax,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
		arg.OrganizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductSalesPageRow{}
	for rows.Next() {
		var i ListProductSalesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PaymentMethod,
			&i.Currency,
			&i.Total,
			&i.SoldAt,
			&i.Note,
			&i.CustomerName,
			&i.CustomerUuid,
			&i.Voided,
			&i.LineCount,
			&i.Profit,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesPage = `-- name: ListPurchasesPage :many

SELECT pu.id, pu.uuid, pu.purchased_on, pu.currency, pu.amount, pu.payment_method, pu.note, pu.created_at,
       su.uuid AS supplier_uuid, su.name AS supplier_name,
       COALESCE((SELECT l.description FROM purchase_lines l WHERE l.purchase_id = pu.id ORDER BY l.sort_order, l.id LIMIT 1), '')::text AS description
FROM purchases pu
JOIN suppliers su ON su.id = pu.supplier_id
WHERE pu.organization_id = $1
  AND (COALESCE(cardinality($2::uuid[]), 0) = 0
       OR su.uuid = ANY ($2::uuid[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0
       OR pu.payment_method = ANY ($3::text[]))
  AND ($4::date IS NULL OR pu.purchased_on >= $4::date)
  AND ($5::date IS NULL OR pu.purchased_on < $5::date)
  AND ($6::numeric IS NULL OR pu.amount >= $6::numeric)
  AND ($7::numeric IS NULL OR pu.amount <= $7::numeric)
  AND ($8::text IS NULL
       OR su.name ILIKE '%' || $8::text || '%'
       OR pu.note ILIKE '%' || $8::text || '%'
       OR EXISTS (SELECT 1 FROM purchase_lines l WHERE l.purchase_id = pu.id
                  AND l.description ILIKE '%' || $8::text || '%'))
ORDER BY
  CASE WHEN NOT $9::bool AND $10::text = 'purchased_on' THEN pu.purchased_on END ASC,
  CASE WHEN $9::bool AND $10::text = 'purchased_on' THEN pu.purchased_on END DESC,
  CASE WHEN NOT $9::bool AND $10::text = 'amount' THEN pu.amount END ASC,
  CASE WHEN $9::bool AND $10::text = 'amount' THEN pu.amount END DESC,
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'supplier_name' THEN su.name WHEN 'payment_method' THEN pu.payment_method::text END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'supplier_name' THEN su.name WHEN 'payment_method' THEN pu.payment_method::text END
  END DESC,
  CASE WHEN $9::bool THEN pu.id END DESC,
  pu.id ASC
LIMIT $12 OFFSET $11
`

type ListPurchasesPageParams struct {
	OrganizationID int64          `json:"organization_id"`
	SupplierUuids  []uuid.UUID    `json:"supplier_uuids"`
	PaymentMethods []string       `json:"payment_methods"`
	DateFrom       pgtype.Date    `json:"date_from"`
	DateBefore     pgtype.Date    `json:"date_before"`
	AmountMin      pgtype.Numeric `json:"amount_min"`
	AmountMax      pgtype.Numeric `json:"amount_max"`
	Q              pgtype.Text    `json:"q"`
	SortDesc       bool           `json:"sort_desc"`
	SortKey        string         `json:"sort_key"`
	OffsetCount    int32          `json:"offset_count"`
	LimitCount     int32          `json:"limit_count"`
}

type ListPurchasesPageRow struct {
	ID            int64              `json:"id"`
	Uuid          uuid.UUID          `json:"uuid"`
	PurchasedOn   pgtype.Date        `json:"purchased_on"`
	Currency      string             `json:"currency"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod string             `json:"payment_method"`
	Note          string             `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SupplierUuid  uuid.UUID          `json:"supplier_uuid"`
	SupplierName  string             `json:"supplier_name"`
	Description   string             `json:"description"`
}

// ---------------------------------------------------------------------------
// Purchases with the supplier name and the (single) line description.
func (q *Queries) ListPurchasesPage(ctx context.Context, arg ListPurchasesPageParams) ([]ListPurchasesPageRow, error) {
	rows, err := q.db.Query(ctx, listPurchasesPage,
		arg.OrganizationID,
		arg.SupplierUuids,
		arg.PaymentMethods,
		arg.DateFrom,
		arg.DateBefore,
		arg.AmountMin,
		arg.AmountMax,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasesPageRow{}
	for rows.Next() {
		var i ListPurchasesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PurchasedOn,
			&i.Currency,
			&i.Amount,
			&i.PaymentMethod,
			&i.Note,
			&i.CreatedAt,
			&i.SupplierUuid,
			&i.SupplierName,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliersPage = `-- name: ListSuppliersPage :many

SELECT id, uuid, organization_id, brand_id, name, tax_no, phone_e164, email, note, active, created_at, updated_at FROM suppliers
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR active = $2::boolean)
  AND ($3::text IS NULL
       OR name ILIKE '%' || $3::text || '%'
       OR tax_no ILIKE '%' || $3::text || '%'
       OR phone_e164 ILIKE '%' || $3::text || '%'
       OR email ILIKE '%' || $3::text || '%')
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
ORDER BY
  CASE WHEN NOT $6::bool AND $7::text = 'name' THEN name END ASC,
  CASE WHEN $6::bool AND $7::text = 'name' THEN name END DESC,
  CASE WHEN NOT $6::bool THEN
    CASE $7::text WHEN 'created_at' THEN created_at WHEN 'updated_at' THEN updated_at END
  END ASC,
  CASE WHEN $6::bool THEN
    CASE $7::text WHEN 'created_at' THEN created_at WHEN 'updated_at' THEN updated_at END
  END DESC,
  CASE WHEN $6::bool THEN id END DESC,
  id ASC
LIMIT $9 OFFSET $8
`

type ListSuppliersPageParams struct {
	OrganizationID int64              `json:"organization_id"`
	Active         pgtype.Bool        `json:"active"`
	Q              pgtype.Text        `json:"q"`
	CreatedFrom    pgtype.Timestamptz `json:"created_from"`
	CreatedBefore  pgtype.Timestamptz `json:"created_before"`
	SortDesc       bool               `json:"sort_desc"`
	SortKey        string             `json:"sort_key"`
	OffsetCount    int32              `json:"offset_count"`
	LimitCount     int32              `json:"limit_count"`
}

// ---------------------------------------------------------------------------
// Suppliers.
func (q *Queries) ListSuppliersPage(ctx context.Context, arg ListSuppliersPageParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliersPage,
		arg.OrganizationID,
		arg.Active,
		arg.Q,
		arg.CreatedFrom,
		arg.CreatedBefore,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.Name,
			&i.TaxNo,
			&i.PhoneE164,
			&i.Email,
			&i.Note,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
