// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dealer_showcases.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDealerShowcasePhotos = `-- name: CountDealerShowcasePhotos :one
SELECT COUNT(*) FROM dealer_showcase_photos
WHERE showcase_id = $1
`

// The usecase compares it with showcase.max_photos under LockDealerShowcase.
func (q *Queries) CountDealerShowcasePhotos(ctx context.Context, showcaseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDealerShowcasePhotos, showcaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDealerShowcaseReviews = `-- name: CountDealerShowcaseReviews :one
SELECT COUNT(*)
FROM dealer_showcases s
JOIN organizations o ON o.id = s.organization_id
WHERE s.brand_id = $1
  AND o.deleted_at IS NULL
  AND (COALESCE(cardinality($2::bigint[]), 0) = 0
       OR s.organization_id = ANY ($2::bigint[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR s.status = ANY ($3::text[]))
  AND ($4::text IS NULL
       OR o.name ILIKE '%' || $4::text || '%'
       OR o.city ILIKE '%' || $4::text || '%')
  AND ($5::timestamptz IS NULL OR s.updated_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR s.updated_at < $6::timestamptz)
`

type CountDealerShowcaseReviewsParams struct {
	BrandID         int64              `json:"brand_id"`
	OrganizationIds []int64            `json:"organization_ids"`
	Statuses        []string           `json:"statuses"`
	Q               pgtype.Text        `json:"q"`
	UpdatedFrom     pgtype.Timestamptz `json:"updated_from"`
	UpdatedBefore   pgtype.Timestamptz `json:"updated_before"`
}

func (q *Queries) CountDealerShowcaseReviews(ctx context.Context, arg CountDealerShowcaseReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDealerShowcaseReviews,
		arg.BrandID,
		arg.OrganizationIds,
		arg.Statuses,
		arg.Q,
		arg.UpdatedFrom,
		arg.UpdatedBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDealerShowcasePhoto = `-- name: DeleteDealerShowcasePhoto :one
DELETE FROM dealer_showcase_photos
WHERE uuid = $1 AND showcase_id = $2
RETURNING storage_key
`

type DeleteDealerShowcasePhotoParams struct {
	Uuid       uuid.UUID `json:"uuid"`
	ShowcaseID int64     `json:"showcase_id"`
}

// Returns the storage key so the caller removes the object after commit.
func (q *Queries) DeleteDealerShowcasePhoto(ctx context.Context, arg DeleteDealerShowcasePhotoParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteDealerShowcasePhoto, arg.Uuid, arg.ShowcaseID)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const deleteDealerShowcaseService = `-- name: DeleteDealerShowcaseService :execrows
DELETE FROM dealer_showcase_services
WHERE uuid = $1 AND showcase_id = $2
`

type DeleteDealerShowcaseServiceParams struct {
	Uuid       uuid.UUID `json:"uuid"`
	ShowcaseID int64     `json:"showcase_id"`
}

func (q *Queries) DeleteDealerShowcaseService(ctx context.Context, arg DeleteDealerShowcaseServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDealerShowcaseService, arg.Uuid, arg.ShowcaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDealerShowcaseByOrg = `-- name: GetDealerShowcaseByOrg :one


SELECT id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at FROM dealer_showcases
WHERE organization_id = $1
`

// TEC-466 (F5-01a): dealer showcase. The usecase (F5-01b) checks the
// module flag, the organization scope and the transition graph
// (dealershowcase/model); these queries only guard the row state.
// Showcase --------------------------------------------------------------------
func (q *Queries) GetDealerShowcaseByOrg(ctx context.Context, organizationID int64) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, getDealerShowcaseByOrg, organizationID)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealerShowcaseByUUID = `-- name: GetDealerShowcaseByUUID :one
SELECT id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at FROM dealer_showcases
WHERE uuid = $1 AND brand_id = $2
`

type GetDealerShowcaseByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetDealerShowcaseByUUID(ctx context.Context, arg GetDealerShowcaseByUUIDParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, getDealerShowcaseByUUID, arg.Uuid, arg.BrandID)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedDealerShowcase = `-- name: GetPublishedDealerShowcase :one
SELECT s.published_content,
       s.id AS showcase_id,
       s.published_at,
       s.google_place_id,
       s.google_rating,
       s.google_review_count,
       s.google_rating_source,
       s.google_rating_updated_at,
       o.id AS organization_id,
       o.locale AS organization_locale
FROM dealer_showcases s
JOIN organizations o ON o.id = s.organization_id
WHERE o.slug = $1
  AND s.brand_id = $2
  AND s.published_content IS NOT NULL
  AND o.deleted_at IS NULL
  AND o.status = 'active'
  AND o.type IN ('dealer', 'distributor')
  AND o.access_starts_at <= NOW()
  AND (o.access_ends_at IS NULL OR o.access_ends_at > NOW())
  AND (o.contract_valid_until IS NULL OR o.contract_valid_until >= CURRENT_DATE)
`

type GetPublishedDealerShowcaseParams struct {
	Slug    string `json:"slug"`
	BrandID int64  `json:"brand_id"`
}

type GetPublishedDealerShowcaseRow struct {
	PublishedContent      []byte             `json:"published_content"`
	ShowcaseID            int64              `json:"showcase_id"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	GooglePlaceID         pgtype.Text        `json:"google_place_id"`
	GoogleRating          pgtype.Numeric     `json:"google_rating"`
	GoogleReviewCount     pgtype.Int4        `json:"google_review_count"`
	GoogleRatingSource    pgtype.Text        `json:"google_rating_source"`
	GoogleRatingUpdatedAt pgtype.Timestamptz `json:"google_rating_updated_at"`
	OrganizationID        int64              `json:"organization_id"`
	OrganizationLocale    string             `json:"organization_locale"`
}

// Public read of /bayi/{code}: the approved snapshot of an active, serving
// dealer or distributor of the brand (same organization filters as
// GetPublicDealerBySlug). A showcase that was published once keeps serving
// its snapshot while a newer version waits for review or was rejected.
// The module flag is checked by the usecase. The Google rating is live.
func (q *Queries) GetPublishedDealerShowcase(ctx context.Context, arg GetPublishedDealerShowcaseParams) (GetPublishedDealerShowcaseRow, error) {
	row := q.db.QueryRow(ctx, getPublishedDealerShowcase, arg.Slug, arg.BrandID)
	var i GetPublishedDealerShowcaseRow
	err := row.Scan(
		&i.PublishedContent,
		&i.ShowcaseID,
		&i.PublishedAt,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.OrganizationID,
		&i.OrganizationLocale,
	)
	return i, err
}

const getShowcaseLeadTargetBySlug = `-- name: GetShowcaseLeadTargetBySlug :one
SELECT o.id AS organization_id,
       o.brand_id,
       o.slug,
       o.name,
       o.locale,
       o.country_id,
       c.iso2 AS country_iso2,
       s.id AS showcase_id,
       s.published_at
FROM organizations o
JOIN dealer_showcases s ON s.organization_id = o.id AND s.brand_id = o.brand_id
LEFT JOIN countries c ON c.id = o.country_id
WHERE o.slug = $1
  AND o.brand_id = $2
  AND s.published_content IS NOT NULL
  AND o.deleted_at IS NULL
  AND o.status = 'active'
  AND o.type IN ('dealer', 'distributor')
  AND o.access_starts_at <= NOW()
  AND (o.access_ends_at IS NULL OR o.access_ends_at > NOW())
  AND (o.contract_valid_until IS NULL OR o.contract_valid_until >= CURRENT_DATE)
`

type GetShowcaseLeadTargetBySlugParams struct {
	Slug    string `json:"slug"`
	BrandID int64  `json:"brand_id"`
}

type GetShowcaseLeadTargetBySlugRow struct {
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Locale         string             `json:"locale"`
	CountryID      pgtype.Int8        `json:"country_id"`
	CountryIso2    pgtype.Text        `json:"country_iso2"`
	ShowcaseID     int64              `json:"showcase_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

// TEC-468: public lead form is accepted only when the dealer showcase add-on
// is enabled and the showcase has a published snapshot.
func (q *Queries) GetShowcaseLeadTargetBySlug(ctx context.Context, arg GetShowcaseLeadTargetBySlugParams) (GetShowcaseLeadTargetBySlugRow, error) {
	row := q.db.QueryRow(ctx, getShowcaseLeadTargetBySlug, arg.Slug, arg.BrandID)
	var i GetShowcaseLeadTargetBySlugRow
	err := row.Scan(
		&i.OrganizationID,
		&i.BrandID,
		&i.Slug,
		&i.Name,
		&i.Locale,
		&i.CountryID,
		&i.CountryIso2,
		&i.ShowcaseID,
		&i.PublishedAt,
	)
	return i, err
}

const insertDealerShowcasePhoto = `-- name: InsertDealerShowcasePhoto :one
INSERT INTO dealer_showcase_photos (showcase_id, organization_id, brand_id, storage_key, mime, size_bytes, sha256,
                                    caption, created_by_user_id, sort_order)
SELECT s.id, s.organization_id, s.brand_id, $1, $2, $3,
       $4, $5, $6,
       COALESCE((SELECT MAX(x.sort_order) FROM dealer_showcase_photos x WHERE x.showcase_id = s.id), 0) + 10
FROM dealer_showcases s
WHERE s.id = $7
RETURNING id, uuid, showcase_id, organization_id, brand_id, storage_key, mime, size_bytes, sha256, caption, sort_order, created_by_user_id, created_at, updated_at
`

type InsertDealerShowcasePhotoParams struct {
	StorageKey      string      `json:"storage_key"`
	Mime            string      `json:"mime"`
	SizeBytes       int64       `json:"size_bytes"`
	Sha256          string      `json:"sha256"`
	Caption         []byte      `json:"caption"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
	ShowcaseID      int64       `json:"showcase_id"`
}

// A new photo goes to the end of the gallery.
func (q *Queries) InsertDealerShowcasePhoto(ctx context.Context, arg InsertDealerShowcasePhotoParams) (DealerShowcasePhoto, error) {
	row := q.db.QueryRow(ctx, insertDealerShowcasePhoto,
		arg.StorageKey,
		arg.Mime,
		arg.SizeBytes,
		arg.Sha256,
		arg.Caption,
		arg.CreatedByUserID,
		arg.ShowcaseID,
	)
	var i DealerShowcasePhoto
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ShowcaseID,
		&i.OrganizationID,
		&i.BrandID,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDealerShowcaseService = `-- name: InsertDealerShowcaseService :one
INSERT INTO dealer_showcase_services (showcase_id, organization_id, brand_id, kind, category_id, title,
                                      description, visible, sort_order)
SELECT s.id, s.organization_id, s.brand_id, $1, $2, $3,
       $4, $5,
       COALESCE((SELECT MAX(x.sort_order) FROM dealer_showcase_services x WHERE x.showcase_id = s.id), 0) + 10
FROM dealer_showcases s
WHERE s.id = $6
RETURNING id, uuid, showcase_id, organization_id, brand_id, kind, category_id, title, description, sort_order, visible, created_at, updated_at
`

type InsertDealerShowcaseServiceParams struct {
	Kind        string      `json:"kind"`
	CategoryID  pgtype.Int8 `json:"category_id"`
	Title       []byte      `json:"title"`
	Description []byte      `json:"description"`
	Visible     bool        `json:"visible"`
	ShowcaseID  int64       `json:"showcase_id"`
}

// A new service goes to the end of the list.
func (q *Queries) InsertDealerShowcaseService(ctx context.Context, arg InsertDealerShowcaseServiceParams) (DealerShowcaseService, error) {
	row := q.db.QueryRow(ctx, insertDealerShowcaseService,
		arg.Kind,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Visible,
		arg.ShowcaseID,
	)
	var i DealerShowcaseService
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ShowcaseID,
		&i.OrganizationID,
		&i.BrandID,
		&i.Kind,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.Visible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDealerShowcasePhotos = `-- name: ListDealerShowcasePhotos :many

SELECT id, uuid, showcase_id, organization_id, brand_id, storage_key, mime, size_bytes, sha256, caption, sort_order, created_by_user_id, created_at, updated_at FROM dealer_showcase_photos
WHERE showcase_id = $1
ORDER BY sort_order, id
`

// Photos ----------------------------------------------------------------------
func (q *Queries) ListDealerShowcasePhotos(ctx context.Context, showcaseID int64) ([]DealerShowcasePhoto, error) {
	rows, err := q.db.Query(ctx, listDealerShowcasePhotos, showcaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealerShowcasePhoto{}
	for rows.Next() {
		var i DealerShowcasePhoto
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ShowcaseID,
			&i.OrganizationID,
			&i.BrandID,
			&i.StorageKey,
			&i.Mime,
			&i.SizeBytes,
			&i.Sha256,
			&i.Caption,
			&i.SortOrder,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealerShowcaseReviews = `-- name: ListDealerShowcaseReviews :many
SELECT s.id, s.uuid, s.organization_id, s.brand_id, s.status, s.content, s.working_hours, s.social_links, s.seo_keywords, s.google_place_id, s.google_rating, s.google_review_count, s.google_rating_source, s.google_rating_updated_at, s.published_content, s.published_at, s.submitted_at, s.reviewed_by, s.reviewed_at, s.review_note, s.created_by_user_id, s.updated_by_user_id, s.created_at, s.updated_at,
       o.uuid AS organization_uuid,
       o.slug AS organization_slug,
       o.name AS organization_name,
       o.type AS organization_type,
       o.city AS organization_city
FROM dealer_showcases s
JOIN organizations o ON o.id = s.organization_id
WHERE s.brand_id = $1
  AND o.deleted_at IS NULL
  AND (COALESCE(cardinality($2::bigint[]), 0) = 0
       OR s.organization_id = ANY ($2::bigint[]))
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR s.status = ANY ($3::text[]))
  AND ($4::text IS NULL
       OR o.name ILIKE '%' || $4::text || '%'
       OR o.city ILIKE '%' || $4::text || '%')
  AND ($5::timestamptz IS NULL OR s.updated_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR s.updated_at < $6::timestamptz)
ORDER BY
  CASE WHEN NOT $7::bool AND $8::text = 'name' THEN o.name END ASC,
  CASE WHEN $7::bool AND $8::text = 'name' THEN o.name END DESC,
  CASE WHEN NOT $7::bool AND $8::text = 'status' THEN
    CASE s.status WHEN 'draft' THEN 1 WHEN 'pending_review' THEN 2 WHEN 'published' THEN 3 ELSE 4 END
  END ASC,
  CASE WHEN $7::bool AND $8::text = 'status' THEN
    CASE s.status WHEN 'draft' THEN 1 WHEN 'pending_review' THEN 2 WHEN 'published' THEN 3 ELSE 4 END
  END DESC,
  CASE WHEN NOT $7::bool AND $8::text = 'updated_at' THEN s.updated_at END ASC,
  CASE WHEN $7::bool AND $8::text = 'updated_at' THEN s.updated_at END DESC,
  CASE WHEN $7::bool THEN s.id END DESC,
  s.id ASC
LIMIT $10 OFFSET $9
`

type ListDealerShowcaseReviewsParams struct {
	BrandID         int64              `json:"brand_id"`
	OrganizationIds []int64            `json:"organization_ids"`
	Statuses        []string           `json:"statuses"`
	Q               pgtype.Text        `json:"q"`
	UpdatedFrom     pgtype.Timestamptz `json:"updated_from"`
	UpdatedBefore   pgtype.Timestamptz `json:"updated_before"`
	SortDesc        bool               `json:"sort_desc"`
	SortKey         string             `json:"sort_key"`
	PageOffset      int32              `json:"page_offset"`
	PageLimit       int32              `json:"page_limit"`
}

type ListDealerShowcaseReviewsRow struct {
	ID                    int64              `json:"id"`
	Uuid                  uuid.UUID          `json:"uuid"`
	OrganizationID        int64              `json:"organization_id"`
	BrandID               int64              `json:"brand_id"`
	Status                string             `json:"status"`
	Content               []byte             `json:"content"`
	WorkingHours          []byte             `json:"working_hours"`
	SocialLinks           []byte             `json:"social_links"`
	SeoKeywords           []string           `json:"seo_keywords"`
	GooglePlaceID         pgtype.Text        `json:"google_place_id"`
	GoogleRating          pgtype.Numeric     `json:"google_rating"`
	GoogleReviewCount     pgtype.Int4        `json:"google_review_count"`
	GoogleRatingSource    pgtype.Text        `json:"google_rating_source"`
	GoogleRatingUpdatedAt pgtype.Timestamptz `json:"google_rating_updated_at"`
	PublishedContent      []byte             `json:"published_content"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	SubmittedAt           pgtype.Timestamptz `json:"submitted_at"`
	ReviewedBy            pgtype.Int8        `json:"reviewed_by"`
	ReviewedAt            pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNote            pgtype.Text        `json:"review_note"`
	CreatedByUserID       pgtype.Int8        `json:"created_by_user_id"`
	UpdatedByUserID       pgtype.Int8        `json:"updated_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	OrganizationUuid      uuid.UUID          `json:"organization_uuid"`
	OrganizationSlug      string             `json:"organization_slug"`
	OrganizationName      string             `json:"organization_name"`
	OrganizationType      string             `json:"organization_type"`
	OrganizationCity      string             `json:"organization_city"`
}

// Center review queue (docs/list-contract.md): sort updated_at | name |
// status (flow rank) with an id tiebreak; statuses multi-valued (empty = all);
// q matches the organization name or city; updated_from / updated_before.
// organization_ids narrows to a scope (empty = whole brand).
func (q *Queries) ListDealerShowcaseReviews(ctx context.Context, arg ListDealerShowcaseReviewsParams) ([]ListDealerShowcaseReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDealerShowcaseReviews,
		arg.BrandID,
		arg.OrganizationIds,
		arg.Statuses,
		arg.Q,
		arg.UpdatedFrom,
		arg.UpdatedBefore,
		arg.SortDesc,
		arg.SortKey,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealerShowcaseReviewsRow{}
	for rows.Next() {
		var i ListDealerShowcaseReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.Status,
			&i.Content,
			&i.WorkingHours,
			&i.SocialLinks,
			&i.SeoKeywords,
			&i.GooglePlaceID,
			&i.GoogleRating,
			&i.GoogleReviewCount,
			&i.GoogleRatingSource,
			&i.GoogleRatingUpdatedAt,
			&i.PublishedContent,
			&i.PublishedAt,
			&i.SubmittedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
			&i.OrganizationName,
			&i.OrganizationType,
			&i.OrganizationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealerShowcaseServices = `-- name: ListDealerShowcaseServices :many

SELECT id, uuid, showcase_id, organization_id, brand_id, kind, category_id, title, description, sort_order, visible, created_at, updated_at FROM dealer_showcase_services
WHERE showcase_id = $1
ORDER BY sort_order, id
`

// Services --------------------------------------------------------------------
func (q *Queries) ListDealerShowcaseServices(ctx context.Context, showcaseID int64) ([]DealerShowcaseService, error) {
	rows, err := q.db.Query(ctx, listDealerShowcaseServices, showcaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DealerShowcaseService{}
	for rows.Next() {
		var i DealerShowcaseService
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ShowcaseID,
			&i.OrganizationID,
			&i.BrandID,
			&i.Kind,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.Visible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDealerShowcase = `-- name: LockDealerShowcase :one
SELECT id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at FROM dealer_showcases
WHERE id = $1
FOR UPDATE
`

// Serializes photo inserts and status moves of one showcase (the caller
// runs in a transaction).
func (q *Queries) LockDealerShowcase(ctx context.Context, id int64) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, lockDealerShowcase, id)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishDealerShowcase = `-- name: PublishDealerShowcase :one
UPDATE dealer_showcases
SET status            = 'published',
    published_content = $1,
    published_at      = NOW(),
    reviewed_by       = $2,
    reviewed_at       = CASE WHEN $2::bigint IS NULL THEN NULL ELSE NOW() END,
    review_note       = NULL,
    updated_by_user_id = COALESCE($2, $3)
WHERE id = $4 AND status = $5
RETURNING id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type PublishDealerShowcaseParams struct {
	PublishedContent []byte      `json:"published_content"`
	ReviewerUserID   pgtype.Int8 `json:"reviewer_user_id"`
	ActorUserID      pgtype.Int8 `json:"actor_user_id"`
	ID               int64       `json:"id"`
	FromStatus       string      `json:"from_status"`
}

// CAS from_status → published and writes the snapshot the public endpoint
// reads. reviewer_user_id is set when the center approved a pending
// showcase, NULL when the owner published directly (approval off).
func (q *Queries) PublishDealerShowcase(ctx context.Context, arg PublishDealerShowcaseParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, publishDealerShowcase,
		arg.PublishedContent,
		arg.ReviewerUserID,
		arg.ActorUserID,
		arg.ID,
		arg.FromStatus,
	)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectDealerShowcase = `-- name: RejectDealerShowcase :one
UPDATE dealer_showcases
SET status             = 'rejected',
    reviewed_by        = $1,
    reviewed_at        = NOW(),
    review_note        = $2,
    updated_by_user_id = $1
WHERE id = $3 AND status = 'pending_review'
RETURNING id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type RejectDealerShowcaseParams struct {
	ReviewerUserID pgtype.Int8 `json:"reviewer_user_id"`
	ReviewNote     pgtype.Text `json:"review_note"`
	ID             int64       `json:"id"`
}

// CAS pending_review → rejected with the reviewer's note. The previous
// published snapshot (if any) stays live.
func (q *Queries) RejectDealerShowcase(ctx context.Context, arg RejectDealerShowcaseParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, rejectDealerShowcase, arg.ReviewerUserID, arg.ReviewNote, arg.ID)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reorderDealerShowcasePhotos = `-- name: ReorderDealerShowcasePhotos :execrows
UPDATE dealer_showcase_photos x
SET sort_order = o.ord * 10
FROM unnest($2::uuid[]) WITH ORDINALITY AS o (uuid, ord)
WHERE x.uuid = o.uuid AND x.showcase_id = $1
`

type ReorderDealerShowcasePhotosParams struct {
	ShowcaseID int64       `json:"showcase_id"`
	Uuids      []uuid.UUID `json:"uuids"`
}

func (q *Queries) ReorderDealerShowcasePhotos(ctx context.Context, arg ReorderDealerShowcasePhotosParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderDealerShowcasePhotos, arg.ShowcaseID, arg.Uuids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderDealerShowcaseServices = `-- name: ReorderDealerShowcaseServices :execrows
UPDATE dealer_showcase_services x
SET sort_order = o.ord * 10
FROM unnest($2::uuid[]) WITH ORDINALITY AS o (uuid, ord)
WHERE x.uuid = o.uuid AND x.showcase_id = $1
`

type ReorderDealerShowcaseServicesParams struct {
	ShowcaseID int64       `json:"showcase_id"`
	Uuids      []uuid.UUID `json:"uuids"`
}

// Sets sort_order 10, 20, … in the given order; uuids of other showcases
// are ignored (the caller compares the row count with the list length).
func (q *Queries) ReorderDealerShowcaseServices(ctx context.Context, arg ReorderDealerShowcaseServicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderDealerShowcaseServices, arg.ShowcaseID, arg.Uuids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDealerShowcaseGoogleRating = `-- name: SetDealerShowcaseGoogleRating :one
UPDATE dealer_showcases
SET google_rating            = $1,
    google_review_count      = $2,
    google_rating_source     = $3,
    google_rating_updated_at = CASE WHEN $1::numeric IS NULL THEN NULL ELSE NOW() END
WHERE id = $4
RETURNING id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type SetDealerShowcaseGoogleRatingParams struct {
	GoogleRating       pgtype.Numeric `json:"google_rating"`
	GoogleReviewCount  pgtype.Int4    `json:"google_review_count"`
	GoogleRatingSource pgtype.Text    `json:"google_rating_source"`
	ID                 int64          `json:"id"`
}

// Writes the Google rating (Places worker or manual entry, F5-01d); NULL
// rating and count clear it.
func (q *Queries) SetDealerShowcaseGoogleRating(ctx context.Context, arg SetDealerShowcaseGoogleRatingParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, setDealerShowcaseGoogleRating,
		arg.GoogleRating,
		arg.GoogleReviewCount,
		arg.GoogleRatingSource,
		arg.ID,
	)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitDealerShowcase = `-- name: SubmitDealerShowcase :one
UPDATE dealer_showcases
SET status             = 'pending_review',
    submitted_at       = NOW(),
    review_note        = NULL,
    updated_by_user_id = $1
WHERE id = $2 AND status = $3
RETURNING id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type SubmitDealerShowcaseParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	ID          int64       `json:"id"`
	FromStatus  string      `json:"from_status"`
}

// CAS from_status → pending_review (approval on). No row when the status
// moved meanwhile.
func (q *Queries) SubmitDealerShowcase(ctx context.Context, arg SubmitDealerShowcaseParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, submitDealerShowcase, arg.ActorUserID, arg.ID, arg.FromStatus)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDealerShowcasePhotoCaption = `-- name: UpdateDealerShowcasePhotoCaption :one
UPDATE dealer_showcase_photos
SET caption = $1
WHERE uuid = $2 AND showcase_id = $3
RETURNING id, uuid, showcase_id, organization_id, brand_id, storage_key, mime, size_bytes, sha256, caption, sort_order, created_by_user_id, created_at, updated_at
`

type UpdateDealerShowcasePhotoCaptionParams struct {
	Caption    []byte    `json:"caption"`
	Uuid       uuid.UUID `json:"uuid"`
	ShowcaseID int64     `json:"showcase_id"`
}

func (q *Queries) UpdateDealerShowcasePhotoCaption(ctx context.Context, arg UpdateDealerShowcasePhotoCaptionParams) (DealerShowcasePhoto, error) {
	row := q.db.QueryRow(ctx, updateDealerShowcasePhotoCaption, arg.Caption, arg.Uuid, arg.ShowcaseID)
	var i DealerShowcasePhoto
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ShowcaseID,
		&i.OrganizationID,
		&i.BrandID,
		&i.StorageKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Sha256,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDealerShowcaseService = `-- name: UpdateDealerShowcaseService :one
UPDATE dealer_showcase_services
SET kind        = $1,
    category_id = $2,
    title       = $3,
    description = $4,
    visible     = $5
WHERE uuid = $6 AND showcase_id = $7
RETURNING id, uuid, showcase_id, organization_id, brand_id, kind, category_id, title, description, sort_order, visible, created_at, updated_at
`

type UpdateDealerShowcaseServiceParams struct {
	Kind        string      `json:"kind"`
	CategoryID  pgtype.Int8 `json:"category_id"`
	Title       []byte      `json:"title"`
	Description []byte      `json:"description"`
	Visible     bool        `json:"visible"`
	Uuid        uuid.UUID   `json:"uuid"`
	ShowcaseID  int64       `json:"showcase_id"`
}

func (q *Queries) UpdateDealerShowcaseService(ctx context.Context, arg UpdateDealerShowcaseServiceParams) (DealerShowcaseService, error) {
	row := q.db.QueryRow(ctx, updateDealerShowcaseService,
		arg.Kind,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Visible,
		arg.Uuid,
		arg.ShowcaseID,
	)
	var i DealerShowcaseService
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ShowcaseID,
		&i.OrganizationID,
		&i.BrandID,
		&i.Kind,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.Visible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDealerShowcase = `-- name: UpsertDealerShowcase :one
INSERT INTO dealer_showcases (organization_id, brand_id, content, working_hours, social_links, seo_keywords,
                              google_place_id, created_by_user_id, updated_by_user_id)
VALUES ($1, $2, $3, $4,
        $5, $6::text[], $7,
        $8, $8)
ON CONFLICT (organization_id) DO UPDATE
SET content            = EXCLUDED.content,
    working_hours      = EXCLUDED.working_hours,
    social_links       = EXCLUDED.social_links,
    seo_keywords       = EXCLUDED.seo_keywords,
    google_place_id    = EXCLUDED.google_place_id,
    updated_by_user_id = EXCLUDED.updated_by_user_id
RETURNING id, uuid, organization_id, brand_id, status, content, working_hours, social_links, seo_keywords, google_place_id, google_rating, google_review_count, google_rating_source, google_rating_updated_at, published_content, published_at, submitted_at, reviewed_by, reviewed_at, review_note, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpsertDealerShowcaseParams struct {
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	Content        []byte      `json:"content"`
	WorkingHours   []byte      `json:"working_hours"`
	SocialLinks    []byte      `json:"social_links"`
	SeoKeywords    []string    `json:"seo_keywords"`
	GooglePlaceID  pgtype.Text `json:"google_place_id"`
	ActorUserID    pgtype.Int8 `json:"actor_user_id"`
}

// Creates the organization's showcase or replaces its draft content. The
// status, the published snapshot and the Google rating are left alone: a
// draft edit never touches the live page.
func (q *Queries) UpsertDealerShowcase(ctx context.Context, arg UpsertDealerShowcaseParams) (DealerShowcase, error) {
	row := q.db.QueryRow(ctx, upsertDealerShowcase,
		arg.OrganizationID,
		arg.BrandID,
		arg.Content,
		arg.WorkingHours,
		arg.SocialLinks,
		arg.SeoKeywords,
		arg.GooglePlaceID,
		arg.ActorUserID,
	)
	var i DealerShowcase
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Status,
		&i.Content,
		&i.WorkingHours,
		&i.SocialLinks,
		&i.SeoKeywords,
		&i.GooglePlaceID,
		&i.GoogleRating,
		&i.GoogleReviewCount,
		&i.GoogleRatingSource,
		&i.GoogleRatingUpdatedAt,
		&i.PublishedContent,
		&i.PublishedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
