// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet_api.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelFleetServicePlan = `-- name: CancelFleetServicePlan :one
UPDATE fleet_service_plans
SET status = 'cancelled',
    cancel_reason = $1,
    cancelled_by_user_id = $2,
    cancelled_at = NOW()
WHERE id = $3::bigint
  AND organization_id = $4::bigint
  AND status = 'scheduled'
RETURNING id, uuid, organization_id, brand_id, fleet_org_id, fleet_link_id, title, service_type, note, start_date, daily_vehicle_limit, preferred_times, status, idempotency_key, cancel_reason, created_by_user_id, cancelled_by_user_id, cancelled_at, created_at, updated_at
`

type CancelFleetServicePlanParams struct {
	CancelReason      pgtype.Text `json:"cancel_reason"`
	CancelledByUserID pgtype.Int8 `json:"cancelled_by_user_id"`
	ID                int64       `json:"id"`
	OrganizationID    int64       `json:"organization_id"`
}

func (q *Queries) CancelFleetServicePlan(ctx context.Context, arg CancelFleetServicePlanParams) (FleetServicePlan, error) {
	row := q.db.QueryRow(ctx, cancelFleetServicePlan,
		arg.CancelReason,
		arg.CancelledByUserID,
		arg.ID,
		arg.OrganizationID,
	)
	var i FleetServicePlan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.FleetOrgID,
		&i.FleetLinkID,
		&i.Title,
		&i.ServiceType,
		&i.Note,
		&i.StartDate,
		&i.DailyVehicleLimit,
		&i.PreferredTimes,
		&i.Status,
		&i.IdempotencyKey,
		&i.CancelReason,
		&i.CreatedByUserID,
		&i.CancelledByUserID,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFleetActiveWarranties = `-- name: CountFleetActiveWarranties :one
SELECT COUNT(*)::bigint
FROM warranties w
JOIN vehicles v ON v.id = w.vehicle_id
WHERE v.fleet_org_id = $1::bigint AND v.deleted_at IS NULL
  AND w.status = 'active' AND w.end_at > NOW()
  AND ($2::bigint[] IS NULL
       OR w.organization_id = ANY ($2::bigint[]))
`

type CountFleetActiveWarrantiesParams struct {
	FleetOrgID    int64   `json:"fleet_org_id"`
	ServiceOrgIds []int64 `json:"service_org_ids"`
}

// Active warranties on the fleet's vehicles; service_org_ids limits them
// to the warranties of those organizations (NULL: all).
func (q *Queries) CountFleetActiveWarranties(ctx context.Context, arg CountFleetActiveWarrantiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetActiveWarranties, arg.FleetOrgID, arg.ServiceOrgIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetReportsFiltered = `-- name: CountFleetReportsFiltered :one
SELECT COUNT(*)::bigint FROM fleet_reports
WHERE fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR status = ANY ($2::text[])
  )
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR period_kind = ANY ($3::text[])
  )
`

type CountFleetReportsFilteredParams struct {
	FleetOrgID  int64    `json:"fleet_org_id"`
	Statuses    []string `json:"statuses"`
	PeriodKinds []string `json:"period_kinds"`
}

func (q *Queries) CountFleetReportsFiltered(ctx context.Context, arg CountFleetReportsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetReportsFiltered, arg.FleetOrgID, arg.Statuses, arg.PeriodKinds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetServicePlansOfOrg = `-- name: CountFleetServicePlansOfOrg :one
SELECT COUNT(*)::bigint FROM fleet_service_plans p
WHERE p.organization_id = $1::bigint
  AND p.fleet_org_id = $2::bigint
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR p.status = ANY ($3::text[])
  )
`

type CountFleetServicePlansOfOrgParams struct {
	OrganizationID int64    `json:"organization_id"`
	FleetOrgID     int64    `json:"fleet_org_id"`
	Statuses       []string `json:"statuses"`
}

func (q *Queries) CountFleetServicePlansOfOrg(ctx context.Context, arg CountFleetServicePlansOfOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetServicePlansOfOrg, arg.OrganizationID, arg.FleetOrgID, arg.Statuses)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetServices = `-- name: CountFleetServices :one
SELECT COUNT(*)::bigint
FROM services s
JOIN vehicles v ON v.id = s.vehicle_id
WHERE v.fleet_org_id = $1::bigint
  AND ($2::bigint[] IS NULL
       OR s.organization_id = ANY ($2::bigint[]))
`

type CountFleetServicesParams struct {
	FleetOrgID    int64   `json:"fleet_org_id"`
	ServiceOrgIds []int64 `json:"service_org_ids"`
}

func (q *Queries) CountFleetServices(ctx context.Context, arg CountFleetServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetServices, arg.FleetOrgID, arg.ServiceOrgIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetUsers = `-- name: CountFleetUsers :one
SELECT COUNT(*)::bigint
FROM fleet_users fu
JOIN users u ON u.id = fu.user_id
WHERE fu.fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR fu.status = ANY ($2::text[])
  )
  AND (
    $3::text IS NULL
    OR u.name ILIKE '%' || $3 || '%'
    OR u.surname ILIKE '%' || $3 || '%'
    OR u.email ILIKE '%' || $3 || '%'
  )
`

type CountFleetUsersParams struct {
	FleetOrgID int64       `json:"fleet_org_id"`
	Statuses   []string    `json:"statuses"`
	Q          pgtype.Text `json:"q"`
}

// Same filter block as ListFleetUsers.
func (q *Queries) CountFleetUsers(ctx context.Context, arg CountFleetUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetUsers, arg.FleetOrgID, arg.Statuses, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetUsersOfFleet = `-- name: CountFleetUsersOfFleet :one
SELECT COUNT(*)::bigint FROM fleet_users WHERE fleet_org_id = $1
`

// Every user row of the fleet (disabled included): the first one is the
// primary user.
func (q *Queries) CountFleetUsersOfFleet(ctx context.Context, fleetOrgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetUsersOfFleet, fleetOrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFleetServicePlan = `-- name: CreateFleetServicePlan :one

INSERT INTO fleet_service_plans (
    organization_id, brand_id, fleet_org_id, fleet_link_id, title, service_type,
    note, start_date, daily_vehicle_limit, preferred_times, idempotency_key,
    created_by_user_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
RETURNING id, uuid, organization_id, brand_id, fleet_org_id, fleet_link_id, title, service_type, note, start_date, daily_vehicle_limit, preferred_times, status, idempotency_key, cancel_reason, created_by_user_id, cancelled_by_user_id, cancelled_at, created_at, updated_at
`

type CreateFleetServicePlanParams struct {
	OrganizationID    int64       `json:"organization_id"`
	BrandID           int64       `json:"brand_id"`
	FleetOrgID        int64       `json:"fleet_org_id"`
	FleetLinkID       int64       `json:"fleet_link_id"`
	Title             string      `json:"title"`
	ServiceType       string      `json:"service_type"`
	Note              string      `json:"note"`
	StartDate         pgtype.Date `json:"start_date"`
	DailyVehicleLimit int32       `json:"daily_vehicle_limit"`
	PreferredTimes    []byte      `json:"preferred_times"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	CreatedByUserID   pgtype.Int8 `json:"created_by_user_id"`
}

// TEC-475 (F5-02d): fleet service plans.
func (q *Queries) CreateFleetServicePlan(ctx context.Context, arg CreateFleetServicePlanParams) (FleetServicePlan, error) {
	row := q.db.QueryRow(ctx, createFleetServicePlan,
		arg.OrganizationID,
		arg.BrandID,
		arg.FleetOrgID,
		arg.FleetLinkID,
		arg.Title,
		arg.ServiceType,
		arg.Note,
		arg.StartDate,
		arg.DailyVehicleLimit,
		arg.PreferredTimes,
		arg.IdempotencyKey,
		arg.CreatedByUserID,
	)
	var i FleetServicePlan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.FleetOrgID,
		&i.FleetLinkID,
		&i.Title,
		&i.ServiceType,
		&i.Note,
		&i.StartDate,
		&i.DailyVehicleLimit,
		&i.PreferredTimes,
		&i.Status,
		&i.IdempotencyKey,
		&i.CancelReason,
		&i.CreatedByUserID,
		&i.CancelledByUserID,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFleetUser = `-- name: CreateFleetUser :one

INSERT INTO fleet_users (fleet_org_id, brand_id, user_id, is_primary, invited_by_org_id, invited_by_user_id)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, uuid, fleet_org_id, brand_id, user_id, is_primary, status, invited_by_org_id, invited_by_user_id, disabled_at, created_at, updated_at
`

type CreateFleetUserParams struct {
	FleetOrgID      int64       `json:"fleet_org_id"`
	BrandID         int64       `json:"brand_id"`
	UserID          int64       `json:"user_id"`
	IsPrimary       bool        `json:"is_primary"`
	InvitedByOrgID  pgtype.Int8 `json:"invited_by_org_id"`
	InvitedByUserID pgtype.Int8 `json:"invited_by_user_id"`
}

// TEC-473 (F5-02b): fleet management API. Fleet users, the dealer's access
// to a fleet (its active links), the fleet card aggregates and the fleet
// statement (the fleet cari in the dealer's ledger).
func (q *Queries) CreateFleetUser(ctx context.Context, arg CreateFleetUserParams) (FleetUser, error) {
	row := q.db.QueryRow(ctx, createFleetUser,
		arg.FleetOrgID,
		arg.BrandID,
		arg.UserID,
		arg.IsPrimary,
		arg.InvitedByOrgID,
		arg.InvitedByUserID,
	)
	var i FleetUser
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.UserID,
		&i.IsPrimary,
		&i.Status,
		&i.InvitedByOrgID,
		&i.InvitedByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableFleetUser = `-- name: DisableFleetUser :one
UPDATE fleet_users
SET status = 'disabled', disabled_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, uuid, fleet_org_id, brand_id, user_id, is_primary, status, invited_by_org_id, invited_by_user_id, disabled_at, created_at, updated_at
`

func (q *Queries) DisableFleetUser(ctx context.Context, id int64) (FleetUser, error) {
	row := q.db.QueryRow(ctx, disableFleetUser, id)
	var i FleetUser
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.UserID,
		&i.IsPrimary,
		&i.Status,
		&i.InvitedByOrgID,
		&i.InvitedByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCarBrandByName = `-- name: FindCarBrandByName :one
SELECT id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at FROM car_brands WHERE lower(name) = lower(btrim($1::text)) AND active
ORDER BY id LIMIT 1
`

// Import: a car brand of the catalog by name (case insensitive).
func (q *Queries) FindCarBrandByName(ctx context.Context, name string) (CarBrand, error) {
	row := q.db.QueryRow(ctx, findCarBrandByName, name)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCarModelByName = `-- name: FindCarModelByName :one
SELECT id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at FROM car_models
WHERE car_brand_id = $1 AND lower(name) = lower(btrim($2::text)) AND active
ORDER BY id LIMIT 1
`

type FindCarModelByNameParams struct {
	CarBrandID int64  `json:"car_brand_id"`
	Name       string `json:"name"`
}

func (q *Queries) FindCarModelByName(ctx context.Context, arg FindCarModelByNameParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, findCarModelByName, arg.CarBrandID, arg.Name)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fleetCariBalanceBefore = `-- name: FleetCariBalanceBefore :one
SELECT COALESCE(SUM(CASE WHEN direction IN ('income', 'charge', 'payment') THEN amount ELSE -amount END), 0)::numeric(18,2)
FROM finance_entries
WHERE cari_id = $1::bigint AND organization_id = $2
  AND created_at < $3
`

type FleetCariBalanceBeforeParams struct {
	CariID         int64              `json:"cari_id"`
	OrganizationID int64              `json:"organization_id"`
	Before         pgtype.Timestamptz `json:"before"`
}

// The cari balance (income/charge/payment add, expense/collection
// subtract, like cari_account_balances) before a point in time.
func (q *Queries) FleetCariBalanceBefore(ctx context.Context, arg FleetCariBalanceBeforeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, fleetCariBalanceBefore, arg.CariID, arg.OrganizationID, arg.Before)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getFleetCarModelByID = `-- name: GetFleetCarModelByID :one
SELECT id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at FROM car_models WHERE id = $1
`

func (q *Queries) GetFleetCarModelByID(ctx context.Context, id int64) (CarModel, error) {
	row := q.db.QueryRow(ctx, getFleetCarModelByID, id)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetServicePlanByIdempotency = `-- name: GetFleetServicePlanByIdempotency :one
SELECT id, uuid, organization_id, brand_id, fleet_org_id, fleet_link_id, title, service_type, note, start_date, daily_vehicle_limit, preferred_times, status, idempotency_key, cancel_reason, created_by_user_id, cancelled_by_user_id, cancelled_at, created_at, updated_at FROM fleet_service_plans
WHERE organization_id = $1::bigint
  AND idempotency_key = $2::text
`

type GetFleetServicePlanByIdempotencyParams struct {
	OrganizationID int64  `json:"organization_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetFleetServicePlanByIdempotency(ctx context.Context, arg GetFleetServicePlanByIdempotencyParams) (FleetServicePlan, error) {
	row := q.db.QueryRow(ctx, getFleetServicePlanByIdempotency, arg.OrganizationID, arg.IdempotencyKey)
	var i FleetServicePlan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.FleetOrgID,
		&i.FleetLinkID,
		&i.Title,
		&i.ServiceType,
		&i.Note,
		&i.StartDate,
		&i.DailyVehicleLimit,
		&i.PreferredTimes,
		&i.Status,
		&i.IdempotencyKey,
		&i.CancelReason,
		&i.CreatedByUserID,
		&i.CancelledByUserID,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetServicePlanByUUID = `-- name: GetFleetServicePlanByUUID :one
SELECT id, uuid, organization_id, brand_id, fleet_org_id, fleet_link_id, title, service_type, note, start_date, daily_vehicle_limit, preferred_times, status, idempotency_key, cancel_reason, created_by_user_id, cancelled_by_user_id, cancelled_at, created_at, updated_at FROM fleet_service_plans
WHERE uuid = $1 AND organization_id = $2::bigint
`

type GetFleetServicePlanByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetFleetServicePlanByUUID(ctx context.Context, arg GetFleetServicePlanByUUIDParams) (FleetServicePlan, error) {
	row := q.db.QueryRow(ctx, getFleetServicePlanByUUID, arg.Uuid, arg.OrganizationID)
	var i FleetServicePlan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.FleetOrgID,
		&i.FleetLinkID,
		&i.Title,
		&i.ServiceType,
		&i.Note,
		&i.StartDate,
		&i.DailyVehicleLimit,
		&i.PreferredTimes,
		&i.Status,
		&i.IdempotencyKey,
		&i.CancelReason,
		&i.CreatedByUserID,
		&i.CancelledByUserID,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetUserByUUID = `-- name: GetFleetUserByUUID :one
SELECT id, uuid, fleet_org_id, brand_id, user_id, is_primary, status, invited_by_org_id, invited_by_user_id, disabled_at, created_at, updated_at FROM fleet_users
WHERE uuid = $1 AND fleet_org_id = $2
`

type GetFleetUserByUUIDParams struct {
	Uuid       uuid.UUID `json:"uuid"`
	FleetOrgID int64     `json:"fleet_org_id"`
}

func (q *Queries) GetFleetUserByUUID(ctx context.Context, arg GetFleetUserByUUIDParams) (FleetUser, error) {
	row := q.db.QueryRow(ctx, getFleetUserByUUID, arg.Uuid, arg.FleetOrgID)
	var i FleetUser
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.UserID,
		&i.IsPrimary,
		&i.Status,
		&i.InvitedByOrgID,
		&i.InvitedByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetUserByUserID = `-- name: GetFleetUserByUserID :one
SELECT fu.id, fu.uuid, fu.fleet_org_id, fu.brand_id, fu.user_id, fu.is_primary, fu.status, fu.invited_by_org_id, fu.invited_by_user_id, fu.disabled_at, fu.created_at, fu.updated_at, o.uuid AS fleet_uuid
FROM fleet_users fu
JOIN organizations o ON o.id = fu.fleet_org_id AND o.deleted_at IS NULL
WHERE fu.user_id = $1 AND fu.status = 'active'
`

type GetFleetUserByUserIDRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	FleetOrgID      int64              `json:"fleet_org_id"`
	BrandID         int64              `json:"brand_id"`
	UserID          int64              `json:"user_id"`
	IsPrimary       bool               `json:"is_primary"`
	Status          string             `json:"status"`
	InvitedByOrgID  pgtype.Int8        `json:"invited_by_org_id"`
	InvitedByUserID pgtype.Int8        `json:"invited_by_user_id"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FleetUuid       uuid.UUID          `json:"fleet_uuid"`
}

// The fleet of a signed-in fleet user (portal).
func (q *Queries) GetFleetUserByUserID(ctx context.Context, userID int64) (GetFleetUserByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getFleetUserByUserID, userID)
	var i GetFleetUserByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.UserID,
		&i.IsPrimary,
		&i.Status,
		&i.InvitedByOrgID,
		&i.InvitedByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetUuid,
	)
	return i, err
}

const getFleetVehicleForUpdate = `-- name: GetFleetVehicleForUpdate :one
SELECT id, uuid, user_id, organization_id, brand_id, car_brand_id, car_model_id, model_year, plate, plate_normalized, plate_country, vin, created_at, updated_at, deleted_at, fleet_org_id FROM vehicles
WHERE uuid = $1 AND fleet_org_id = $2::bigint AND deleted_at IS NULL
FOR UPDATE
`

type GetFleetVehicleForUpdateParams struct {
	Uuid       uuid.UUID `json:"uuid"`
	FleetOrgID int64     `json:"fleet_org_id"`
}

// A vehicle of the fleet, locked (PATCH, removal).
func (q *Queries) GetFleetVehicleForUpdate(ctx context.Context, arg GetFleetVehicleForUpdateParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getFleetVehicleForUpdate, arg.Uuid, arg.FleetOrgID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.OrganizationID,
		&i.BrandID,
		&i.CarBrandID,
		&i.CarModelID,
		&i.ModelYear,
		&i.Plate,
		&i.PlateNormalized,
		&i.PlateCountry,
		&i.Vin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FleetOrgID,
	)
	return i, err
}

const getVehicleByIDForUpdate = `-- name: GetVehicleByIDForUpdate :one
SELECT id, uuid, user_id, organization_id, brand_id, car_brand_id, car_model_id, model_year, plate, plate_normalized, plate_country, vin, created_at, updated_at, deleted_at, fleet_org_id FROM vehicles WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetVehicleByIDForUpdate(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByIDForUpdate, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.OrganizationID,
		&i.BrandID,
		&i.CarBrandID,
		&i.CarModelID,
		&i.ModelYear,
		&i.Plate,
		&i.PlateNormalized,
		&i.PlateCountry,
		&i.Vin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FleetOrgID,
	)
	return i, err
}

const listActiveFleetLinksInScope = `-- name: ListActiveFleetLinksInScope :many
SELECT id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at FROM fleet_dealer_links
WHERE fleet_org_id = $1 AND status = 'active'
  AND ($2::bigint[] IS NULL OR dealer_org_id = ANY ($2::bigint[]))
ORDER BY id
`

type ListActiveFleetLinksInScopeParams struct {
	FleetOrgID int64   `json:"fleet_org_id"`
	OrgIds     []int64 `json:"org_ids"`
}

// The active links of a fleet to the organizations in scope (org_ids NULL:
// every organization of the brand). A dealer reaches a fleet only through
// an active link.
func (q *Queries) ListActiveFleetLinksInScope(ctx context.Context, arg ListActiveFleetLinksInScopeParams) ([]FleetDealerLink, error) {
	rows, err := q.db.Query(ctx, listActiveFleetLinksInScope, arg.FleetOrgID, arg.OrgIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetDealerLink{}
	for rows.Next() {
		var i FleetDealerLink
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FleetOrgID,
			&i.DealerOrgID,
			&i.BrandID,
			&i.Status,
			&i.CreatedByOrgID,
			&i.CreatedByUserID,
			&i.CariAccountID,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFleetUserIDs = `-- name: ListActiveFleetUserIDs :many
SELECT fu.user_id
FROM fleet_users fu
JOIN users u ON u.id = fu.user_id AND u.deleted_at IS NULL AND u.status = 'active'
WHERE fu.fleet_org_id = $1 AND fu.status = 'active'
ORDER BY fu.id
`

// Recipients of fleet notifications (link requests).
func (q *Queries) ListActiveFleetUserIDs(ctx context.Context, fleetOrgID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listActiveFleetUserIDs, fleetOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetPlanAppointmentRefs = `-- name: ListFleetPlanAppointmentRefs :many
SELECT a.uuid AS appointment_uuid, v.uuid AS vehicle_uuid, v.plate,
    cb.name AS car_brand_name, cm.name AS car_model_name, s.uuid AS service_uuid
FROM appointments a
LEFT JOIN vehicles v ON v.id = a.vehicle_id
LEFT JOIN car_brands cb ON cb.id = v.car_brand_id
LEFT JOIN car_models cm ON cm.id = v.car_model_id
LEFT JOIN services s ON s.id = a.service_id
WHERE a.plan_id = $1::bigint
  AND a.organization_id = $2::bigint
  AND a.deleted_at IS NULL
`

type ListFleetPlanAppointmentRefsParams struct {
	PlanID         int64 `json:"plan_id"`
	OrganizationID int64 `json:"organization_id"`
}

type ListFleetPlanAppointmentRefsRow struct {
	AppointmentUuid uuid.UUID   `json:"appointment_uuid"`
	VehicleUuid     pgtype.UUID `json:"vehicle_uuid"`
	Plate           pgtype.Text `json:"plate"`
	CarBrandName    pgtype.Text `json:"car_brand_name"`
	CarModelName    pgtype.Text `json:"car_model_name"`
	ServiceUuid     pgtype.UUID `json:"service_uuid"`
}

// Vehicle and draft service references of a plan's appointments (plan
// detail).
func (q *Queries) ListFleetPlanAppointmentRefs(ctx context.Context, arg ListFleetPlanAppointmentRefsParams) ([]ListFleetPlanAppointmentRefsRow, error) {
	rows, err := q.db.Query(ctx, listFleetPlanAppointmentRefs, arg.PlanID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetPlanAppointmentRefsRow{}
	for rows.Next() {
		var i ListFleetPlanAppointmentRefsRow
		if err := rows.Scan(
			&i.AppointmentUuid,
			&i.VehicleUuid,
			&i.Plate,
			&i.CarBrandName,
			&i.CarModelName,
			&i.ServiceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetPlanVehicles = `-- name: ListFleetPlanVehicles :many
SELECT v.id, v.uuid, v.user_id, v.organization_id, v.brand_id, v.car_brand_id, v.car_model_id, v.model_year, v.plate, v.plate_normalized, v.plate_country, v.vin, v.created_at, v.updated_at, v.deleted_at, v.fleet_org_id, u.uuid AS customer_uuid
FROM vehicles v
JOIN fleet_users fu ON fu.user_id = v.user_id AND fu.fleet_org_id = v.fleet_org_id AND fu.status = 'active'
JOIN users u ON u.id = v.user_id AND u.deleted_at IS NULL
WHERE v.fleet_org_id = $1::bigint
  AND v.uuid = ANY($2::uuid[])
  AND v.deleted_at IS NULL
ORDER BY array_position($2::uuid[], v.uuid)
`

type ListFleetPlanVehiclesParams struct {
	FleetOrgID   int64       `json:"fleet_org_id"`
	VehicleUuids []uuid.UUID `json:"vehicle_uuids"`
}

type ListFleetPlanVehiclesRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	UserID          int64              `json:"user_id"`
	OrganizationID  pgtype.Int8        `json:"organization_id"`
	BrandID         int64              `json:"brand_id"`
	CarBrandID      pgtype.Int8        `json:"car_brand_id"`
	CarModelID      pgtype.Int8        `json:"car_model_id"`
	ModelYear       pgtype.Int2        `json:"model_year"`
	Plate           pgtype.Text        `json:"plate"`
	PlateNormalized pgtype.Text        `json:"plate_normalized"`
	PlateCountry    pgtype.Text        `json:"plate_country"`
	Vin             pgtype.Text        `json:"vin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	FleetOrgID      pgtype.Int8        `json:"fleet_org_id"`
	CustomerUuid    uuid.UUID          `json:"customer_uuid"`
}

func (q *Queries) ListFleetPlanVehicles(ctx context.Context, arg ListFleetPlanVehiclesParams) ([]ListFleetPlanVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listFleetPlanVehicles, arg.FleetOrgID, arg.VehicleUuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetPlanVehiclesRow{}
	for rows.Next() {
		var i ListFleetPlanVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.OrganizationID,
			&i.BrandID,
			&i.CarBrandID,
			&i.CarModelID,
			&i.ModelYear,
			&i.Plate,
			&i.PlateNormalized,
			&i.PlateCountry,
			&i.Vin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FleetOrgID,
			&i.CustomerUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetRecentServices = `-- name: ListFleetRecentServices :many
SELECT s.uuid, s.service_no, s.status, s.created_at, s.completed_at, s.plate,
       v.uuid AS vehicle_uuid, o.uuid AS organization_uuid, o.name AS organization_name
FROM services s
JOIN vehicles v ON v.id = s.vehicle_id
JOIN organizations o ON o.id = s.organization_id
WHERE v.fleet_org_id = $1::bigint
  AND ($2::bigint[] IS NULL
       OR s.organization_id = ANY ($2::bigint[]))
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
`

type ListFleetRecentServicesParams struct {
	FleetOrgID    int64   `json:"fleet_org_id"`
	ServiceOrgIds []int64 `json:"service_org_ids"`
	LimitCount    int32   `json:"limit_count"`
}

type ListFleetRecentServicesRow struct {
	Uuid             uuid.UUID          `json:"uuid"`
	ServiceNo        string             `json:"service_no"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Plate            pgtype.Text        `json:"plate"`
	VehicleUuid      uuid.UUID          `json:"vehicle_uuid"`
	OrganizationUuid uuid.UUID          `json:"organization_uuid"`
	OrganizationName string             `json:"organization_name"`
}

// The latest services on the fleet's vehicles, limited to service_org_ids
// (NULL: all organizations).
func (q *Queries) ListFleetRecentServices(ctx context.Context, arg ListFleetRecentServicesParams) ([]ListFleetRecentServicesRow, error) {
	rows, err := q.db.Query(ctx, listFleetRecentServices, arg.FleetOrgID, arg.ServiceOrgIds, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetRecentServicesRow{}
	for rows.Next() {
		var i ListFleetRecentServicesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ServiceNo,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Plate,
			&i.VehicleUuid,
			&i.OrganizationUuid,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetReportsSorted = `-- name: ListFleetReportsSorted :many
SELECT id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at FROM fleet_reports
WHERE fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR status = ANY ($2::text[])
  )
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR period_kind = ANY ($3::text[])
  )
ORDER BY
  CASE WHEN NOT $4::bool THEN period_start END ASC,
  CASE WHEN $4::bool THEN period_start END DESC,
  CASE WHEN $4::bool THEN id END DESC,
  id ASC
LIMIT $6 OFFSET $5
`

type ListFleetReportsSortedParams struct {
	FleetOrgID  int64    `json:"fleet_org_id"`
	Statuses    []string `json:"statuses"`
	PeriodKinds []string `json:"period_kinds"`
	SortDesc    bool     `json:"sort_desc"`
	OffsetCount int32    `json:"offset_count"`
	LimitCount  int32    `json:"limit_count"`
}

// Reports of the fleet for the panel (every status). Sort period_start,
// default -period_start; id tiebreak.
func (q *Queries) ListFleetReportsSorted(ctx context.Context, arg ListFleetReportsSortedParams) ([]FleetReport, error) {
	rows, err := q.db.Query(ctx, listFleetReportsSorted,
		arg.FleetOrgID,
		arg.Statuses,
		arg.PeriodKinds,
		arg.SortDesc,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetReport{}
	for rows.Next() {
		var i FleetReport
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FleetOrgID,
			&i.BrandID,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Locale,
			&i.StorageKey,
			&i.Status,
			&i.Error,
			&i.EmailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetServicePlansOfOrg = `-- name: ListFleetServicePlansOfOrg :many

SELECT p.id, p.uuid, p.organization_id, p.brand_id, p.fleet_org_id, p.fleet_link_id, p.title, p.service_type, p.note, p.start_date, p.daily_vehicle_limit, p.preferred_times, p.status, p.idempotency_key, p.cancel_reason, p.created_by_user_id, p.cancelled_by_user_id, p.cancelled_at, p.created_at, p.updated_at,
    (SELECT COUNT(*) FROM appointments a
     WHERE a.plan_id = p.id AND a.organization_id = p.organization_id AND a.deleted_at IS NULL)::bigint AS appointment_count,
    (SELECT COUNT(*) FROM appointments a
     WHERE a.plan_id = p.id AND a.organization_id = p.organization_id AND a.deleted_at IS NULL
       AND a.service_id IS NOT NULL)::bigint AS intake_count
FROM fleet_service_plans p
WHERE p.organization_id = $1::bigint
  AND p.fleet_org_id = $2::bigint
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR p.status = ANY ($3::text[])
  )
ORDER BY
  CASE WHEN $4::text = 'created_at' AND NOT $5::bool THEN p.created_at END ASC,
  CASE WHEN $4::text = 'created_at' AND $5::bool THEN p.created_at END DESC,
  CASE WHEN $4::text = 'start_date' AND NOT $5::bool THEN p.start_date END ASC,
  CASE WHEN $4::text = 'start_date' AND $5::bool THEN p.start_date END DESC,
  CASE WHEN $5::bool THEN p.id END DESC,
  p.id ASC
LIMIT $7 OFFSET $6
`

type ListFleetServicePlansOfOrgParams struct {
	OrganizationID int64    `json:"organization_id"`
	FleetOrgID     int64    `json:"fleet_org_id"`
	Statuses       []string `json:"statuses"`
	SortField      string   `json:"sort_field"`
	SortDesc       bool     `json:"sort_desc"`
	OffsetCount    int32    `json:"offset_count"`
	LimitCount     int32    `json:"limit_count"`
}

type ListFleetServicePlansOfOrgRow struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	OrganizationID    int64              `json:"organization_id"`
	BrandID           int64              `json:"brand_id"`
	FleetOrgID        int64              `json:"fleet_org_id"`
	FleetLinkID       int64              `json:"fleet_link_id"`
	Title             string             `json:"title"`
	ServiceType       string             `json:"service_type"`
	Note              string             `json:"note"`
	StartDate         pgtype.Date        `json:"start_date"`
	DailyVehicleLimit int32              `json:"daily_vehicle_limit"`
	PreferredTimes    []byte             `json:"preferred_times"`
	Status            string             `json:"status"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	CancelReason      pgtype.Text        `json:"cancel_reason"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
	CancelledByUserID pgtype.Int8        `json:"cancelled_by_user_id"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AppointmentCount  int64              `json:"appointment_count"`
	IntakeCount       int64              `json:"intake_count"`
}

// TEC-477 (F5-02f): the panel reads its plans of a fleet.
// Plans of one fleet made by the organization. Sort created_at (default
// -created_at) or start_date; id tiebreak.
func (q *Queries) ListFleetServicePlansOfOrg(ctx context.Context, arg ListFleetServicePlansOfOrgParams) ([]ListFleetServicePlansOfOrgRow, error) {
	rows, err := q.db.Query(ctx, listFleetServicePlansOfOrg,
		arg.OrganizationID,
		arg.FleetOrgID,
		arg.Statuses,
		arg.SortField,
		arg.SortDesc,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetServicePlansOfOrgRow{}
	for rows.Next() {
		var i ListFleetServicePlansOfOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.FleetOrgID,
			&i.FleetLinkID,
			&i.Title,
			&i.ServiceType,
			&i.Note,
			&i.StartDate,
			&i.DailyVehicleLimit,
			&i.PreferredTimes,
			&i.Status,
			&i.IdempotencyKey,
			&i.CancelReason,
			&i.CreatedByUserID,
			&i.CancelledByUserID,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentCount,
			&i.IntakeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetStatementEntries = `-- name: ListFleetStatementEntries :many
SELECT fe.uuid, fe.direction, fe.category, fe.amount, fe.currency, fe.source_type, fe.source_uuid,
       fe.description, fe.created_at, (fe.reversal_of_id IS NOT NULL)::bool AS is_reversal,
       s.uuid AS service_uuid, s.service_no, s.plate, s.completed_at AS service_completed_at,
       v.uuid AS vehicle_uuid
FROM finance_entries fe
LEFT JOIN services s
    ON fe.source_type = 'service_income' AND s.uuid = fe.source_uuid AND s.organization_id = fe.organization_id
LEFT JOIN vehicles v ON v.id = s.vehicle_id
WHERE fe.cari_id = $1::bigint AND fe.organization_id = $2
  AND fe.created_at >= $3 AND fe.created_at < $4
ORDER BY fe.created_at, fe.id
`

type ListFleetStatementEntriesParams struct {
	CariID         int64              `json:"cari_id"`
	OrganizationID int64              `json:"organization_id"`
	PeriodFrom     pgtype.Timestamptz `json:"period_from"`
	PeriodTo       pgtype.Timestamptz `json:"period_to"`
}

type ListFleetStatementEntriesRow struct {
	Uuid               uuid.UUID          `json:"uuid"`
	Direction          string             `json:"direction"`
	Category           string             `json:"category"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	SourceType         pgtype.Text        `json:"source_type"`
	SourceUuid         pgtype.UUID        `json:"source_uuid"`
	Description        pgtype.Text        `json:"description"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	IsReversal         bool               `json:"is_reversal"`
	ServiceUuid        pgtype.UUID        `json:"service_uuid"`
	ServiceNo          pgtype.Text        `json:"service_no"`
	Plate              pgtype.Text        `json:"plate"`
	ServiceCompletedAt pgtype.Timestamptz `json:"service_completed_at"`
	VehicleUuid        pgtype.UUID        `json:"vehicle_uuid"`
}

// The ledger rows of one fleet cari in [period_from, period_to): service
// income with its service and vehicle, collections and the other cari
// movements. Reversals stay as their own (negative) rows.
func (q *Queries) ListFleetStatementEntries(ctx context.Context, arg ListFleetStatementEntriesParams) ([]ListFleetStatementEntriesRow, error) {
	rows, err := q.db.Query(ctx, listFleetStatementEntries,
		arg.CariID,
		arg.OrganizationID,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetStatementEntriesRow{}
	for rows.Next() {
		var i ListFleetStatementEntriesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Direction,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.SourceType,
			&i.SourceUuid,
			&i.Description,
			&i.CreatedAt,
			&i.IsReversal,
			&i.ServiceUuid,
			&i.ServiceNo,
			&i.Plate,
			&i.ServiceCompletedAt,
			&i.VehicleUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetUsers = `-- name: ListFleetUsers :many
SELECT fu.id, fu.uuid, fu.is_primary, fu.status, fu.created_at, fu.disabled_at,
       u.uuid AS user_uuid, u.email, u.name, u.surname, u.last_login_at
FROM fleet_users fu
JOIN users u ON u.id = fu.user_id
WHERE fu.fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR fu.status = ANY ($2::text[])
  )
  AND (
    $3::text IS NULL
    OR u.name ILIKE '%' || $3 || '%'
    OR u.surname ILIKE '%' || $3 || '%'
    OR u.email ILIKE '%' || $3 || '%'
  )
ORDER BY
  CASE WHEN NOT $4::bool AND $5::text = 'name' THEN u.name END ASC,
  CASE WHEN $4::bool AND $5::text = 'name' THEN u.name END DESC,
  CASE WHEN NOT $4::bool AND $5::text = 'email' THEN u.email END ASC NULLS LAST,
  CASE WHEN $4::bool AND $5::text = 'email' THEN u.email END DESC NULLS LAST,
  CASE WHEN NOT $4::bool AND $5::text = 'status' THEN fu.status END ASC,
  CASE WHEN $4::bool AND $5::text = 'status' THEN fu.status END DESC,
  CASE WHEN NOT $4::bool AND $5::text = 'created_at' THEN fu.created_at END ASC,
  CASE WHEN $4::bool AND $5::text = 'created_at' THEN fu.created_at END DESC,
  CASE WHEN $4::bool THEN fu.id END DESC,
  fu.id ASC
LIMIT $7 OFFSET $6
`

type ListFleetUsersParams struct {
	FleetOrgID  int64       `json:"fleet_org_id"`
	Statuses    []string    `json:"statuses"`
	Q           pgtype.Text `json:"q"`
	SortDesc    bool        `json:"sort_desc"`
	SortKey     string      `json:"sort_key"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListFleetUsersRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	IsPrimary   bool               `json:"is_primary"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	UserUuid    uuid.UUID          `json:"user_uuid"`
	Email       pgtype.Text        `json:"email"`
	Name        string             `json:"name"`
	Surname     string             `json:"surname"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// Users of a fleet. Sort (docs/list-contract.md): name | email | status |
// created_at, default created_at, id tiebreak. Filters: q (name, surname,
// e-mail), multi-value status.
func (q *Queries) ListFleetUsers(ctx context.Context, arg ListFleetUsersParams) ([]ListFleetUsersRow, error) {
	rows, err := q.db.Query(ctx, listFleetUsers,
		arg.FleetOrgID,
		arg.Statuses,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetUsersRow{}
	for rows.Next() {
		var i ListFleetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.IsPrimary,
			&i.Status,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.UserUuid,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vehicleHasServices = `-- name: VehicleHasServices :one
SELECT EXISTS (SELECT 1 FROM services WHERE vehicle_id = $1)::bool
`

func (q *Queries) VehicleHasServices(ctx context.Context, vehicleID int64) (bool, error) {
	row := q.db.QueryRow(ctx, vehicleHasServices, vehicleID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
