// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDealerFleets = `-- name: CountDealerFleets :one
SELECT COUNT(*)::bigint
FROM fleet_dealer_links l
JOIN organizations f ON f.id = l.fleet_org_id AND f.deleted_at IS NULL
JOIN fleet_profiles fp ON fp.organization_id = f.id
WHERE l.brand_id = $1
  AND ($2::bigint[] IS NULL OR l.dealer_org_id = ANY ($2::bigint[]))
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR l.status = ANY ($3::text[])
  )
  AND (
    $4::text IS NULL
    OR f.name ILIKE '%' || $4 || '%'
    OR fp.legal_name ILIKE '%' || $4 || '%'
    OR fp.tax_number LIKE $4 || '%'
  )
  AND (
    ($5::bigint IS NULL AND $6::bigint IS NULL)
    OR (
      SELECT COUNT(*) FROM vehicles v WHERE v.fleet_org_id = f.id AND v.deleted_at IS NULL
    ) BETWEEN COALESCE($5::bigint, 0)
          AND COALESCE($6::bigint, 9223372036854775807)
  )
`

type CountDealerFleetsParams struct {
	BrandID         int64       `json:"brand_id"`
	DealerOrgIds    []int64     `json:"dealer_org_ids"`
	Statuses        []string    `json:"statuses"`
	Q               pgtype.Text `json:"q"`
	VehicleCountMin pgtype.Int8 `json:"vehicle_count_min"`
	VehicleCountMax pgtype.Int8 `json:"vehicle_count_max"`
}

// Same filter block as ListDealerFleets.
func (q *Queries) CountDealerFleets(ctx context.Context, arg CountDealerFleetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDealerFleets,
		arg.BrandID,
		arg.DealerOrgIds,
		arg.Statuses,
		arg.Q,
		arg.VehicleCountMin,
		arg.VehicleCountMax,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetReports = `-- name: CountFleetReports :one
SELECT COUNT(*)::bigint FROM fleet_reports
WHERE fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR status = ANY ($2::text[])
  )
`

type CountFleetReportsParams struct {
	FleetOrgID int64    `json:"fleet_org_id"`
	Statuses   []string `json:"statuses"`
}

func (q *Queries) CountFleetReports(ctx context.Context, arg CountFleetReportsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetReports, arg.FleetOrgID, arg.Statuses)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFleetVehicles = `-- name: CountFleetVehicles :one
SELECT COUNT(*)::bigint
FROM vehicles v
LEFT JOIN car_brands cb ON cb.id = v.car_brand_id
LEFT JOIN car_models cm ON cm.id = v.car_model_id
WHERE v.fleet_org_id = $1::bigint AND v.deleted_at IS NULL
  AND (
    $2::text IS NULL
    OR v.plate ILIKE '%' || $2 || '%'
    OR v.plate_normalized LIKE $3::text || '%'
    OR v.vin ILIKE $2 || '%'
    OR cb.name ILIKE '%' || $2 || '%'
    OR cm.name ILIKE '%' || $2 || '%'
  )
`

type CountFleetVehiclesParams struct {
	FleetOrgID int64       `json:"fleet_org_id"`
	Q          pgtype.Text `json:"q"`
	QPlate     pgtype.Text `json:"q_plate"`
}

// Same filter block as ListFleetVehicles.
func (q *Queries) CountFleetVehicles(ctx context.Context, arg CountFleetVehiclesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetVehicles, arg.FleetOrgID, arg.Q, arg.QPlate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFleetDealerLink = `-- name: CreateFleetDealerLink :one
INSERT INTO fleet_dealer_links (
    fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id,
    cari_account_id, started_at
) VALUES (
    $1, $2, $3, $4::text,
    $5, $6, $7,
    CASE WHEN $4::text = 'active' THEN NOW() END
)
RETURNING id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at
`

type CreateFleetDealerLinkParams struct {
	FleetOrgID      int64       `json:"fleet_org_id"`
	DealerOrgID     int64       `json:"dealer_org_id"`
	BrandID         int64       `json:"brand_id"`
	Status          string      `json:"status"`
	CreatedByOrgID  int64       `json:"created_by_org_id"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
	CariAccountID   pgtype.Int8 `json:"cari_account_id"`
}

func (q *Queries) CreateFleetDealerLink(ctx context.Context, arg CreateFleetDealerLinkParams) (FleetDealerLink, error) {
	row := q.db.QueryRow(ctx, createFleetDealerLink,
		arg.FleetOrgID,
		arg.DealerOrgID,
		arg.BrandID,
		arg.Status,
		arg.CreatedByOrgID,
		arg.CreatedByUserID,
		arg.CariAccountID,
	)
	var i FleetDealerLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.DealerOrgID,
		&i.BrandID,
		&i.Status,
		&i.CreatedByOrgID,
		&i.CreatedByUserID,
		&i.CariAccountID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFleetProfile = `-- name: CreateFleetProfile :one

INSERT INTO fleet_profiles (
    organization_id, brand_id, tax_number, tax_office, legal_name,
    contact_name, contact_phone, billing_email, report_frequency, report_locale,
    primary_user_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11, $12
)
RETURNING id, uuid, organization_id, brand_id, tax_number, tax_office, legal_name, contact_name, contact_phone, billing_email, report_frequency, report_locale, primary_user_id, created_by_user_id, created_at, updated_at
`

type CreateFleetProfileParams struct {
	OrganizationID  int64       `json:"organization_id"`
	BrandID         int64       `json:"brand_id"`
	TaxNumber       string      `json:"tax_number"`
	TaxOffice       pgtype.Text `json:"tax_office"`
	LegalName       string      `json:"legal_name"`
	ContactName     pgtype.Text `json:"contact_name"`
	ContactPhone    pgtype.Text `json:"contact_phone"`
	BillingEmail    pgtype.Text `json:"billing_email"`
	ReportFrequency string      `json:"report_frequency"`
	ReportLocale    string      `json:"report_locale"`
	PrimaryUserID   pgtype.Int8 `json:"primary_user_id"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

// TEC-472 (F5-02a): fleets. A fleet is an organization of type 'fleet'
// with a fleet_profiles row; dealers reach it through fleet_dealer_links.
func (q *Queries) CreateFleetProfile(ctx context.Context, arg CreateFleetProfileParams) (FleetProfile, error) {
	row := q.db.QueryRow(ctx, createFleetProfile,
		arg.OrganizationID,
		arg.BrandID,
		arg.TaxNumber,
		arg.TaxOffice,
		arg.LegalName,
		arg.ContactName,
		arg.ContactPhone,
		arg.BillingEmail,
		arg.ReportFrequency,
		arg.ReportLocale,
		arg.PrimaryUserID,
		arg.CreatedByUserID,
	)
	var i FleetProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.LegalName,
		&i.ContactName,
		&i.ContactPhone,
		&i.BillingEmail,
		&i.ReportFrequency,
		&i.ReportLocale,
		&i.PrimaryUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFleetByTaxNumber = `-- name: FindFleetByTaxNumber :one
SELECT o.id, o.uuid, o.slug, o.name, o.city, o.district, o.phone, o.address, o.logo_object_key, o.status, o.plan_code, o.access_starts_at, o.access_ends_at, o.created_at, o.updated_at, o.deleted_at, o.email, o.website, o.tagline, o.footer_text, o.paper_size, o.primary_color, o.type, o.parent_id, o.brand_id, o.currency, o.locale, o.timezone, o.country_id, o.contract_pdf_key, o.contract_valid_until, o.settings, o.province_id, o.district_id, o.phone_raw, o.google_business_url, o.latitude, o.longitude, o.invoice_vkn, o.invoice_tckn, o.invoice_tax_office, o.invoice_legal_name, o.einvoice_registered, o.einvoice_alias, o.invoice_email, fp.id, fp.uuid, fp.organization_id, fp.brand_id, fp.tax_number, fp.tax_office, fp.legal_name, fp.contact_name, fp.contact_phone, fp.billing_email, fp.report_frequency, fp.report_locale, fp.primary_user_id, fp.created_by_user_id, fp.created_at, fp.updated_at
FROM fleet_profiles fp
JOIN organizations o ON o.id = fp.organization_id AND o.deleted_at IS NULL
WHERE fp.brand_id = $1 AND fp.tax_number = $2
`

type FindFleetByTaxNumberParams struct {
	BrandID   int64  `json:"brand_id"`
	TaxNumber string `json:"tax_number"`
}

type FindFleetByTaxNumberRow struct {
	Organization Organization `json:"organization"`
	FleetProfile FleetProfile `json:"fleet_profile"`
}

// Exact VKN/TCKN match within the brand (a second dealer finds the fleet
// and requests a link instead of opening a duplicate).
func (q *Queries) FindFleetByTaxNumber(ctx context.Context, arg FindFleetByTaxNumberParams) (FindFleetByTaxNumberRow, error) {
	row := q.db.QueryRow(ctx, findFleetByTaxNumber, arg.BrandID, arg.TaxNumber)
	var i FindFleetByTaxNumberRow
	err := row.Scan(
		&i.Organization.ID,
		&i.Organization.Uuid,
		&i.Organization.Slug,
		&i.Organization.Name,
		&i.Organization.City,
		&i.Organization.District,
		&i.Organization.Phone,
		&i.Organization.Address,
		&i.Organization.LogoObjectKey,
		&i.Organization.Status,
		&i.Organization.PlanCode,
		&i.Organization.AccessStartsAt,
		&i.Organization.AccessEndsAt,
		&i.Organization.CreatedAt,
		&i.Organization.UpdatedAt,
		&i.Organization.DeletedAt,
		&i.Organization.Email,
		&i.Organization.Website,
		&i.Organization.Tagline,
		&i.Organization.FooterText,
		&i.Organization.PaperSize,
		&i.Organization.PrimaryColor,
		&i.Organization.Type,
		&i.Organization.ParentID,
		&i.Organization.BrandID,
		&i.Organization.Currency,
		&i.Organization.Locale,
		&i.Organization.Timezone,
		&i.Organization.CountryID,
		&i.Organization.ContractPdfKey,
		&i.Organization.ContractValidUntil,
		&i.Organization.Settings,
		&i.Organization.ProvinceID,
		&i.Organization.DistrictID,
		&i.Organization.PhoneRaw,
		&i.Organization.GoogleBusinessUrl,
		&i.Organization.Latitude,
		&i.Organization.Longitude,
		&i.Organization.InvoiceVkn,
		&i.Organization.InvoiceTckn,
		&i.Organization.InvoiceTaxOffice,
		&i.Organization.InvoiceLegalName,
		&i.Organization.EinvoiceRegistered,
		&i.Organization.EinvoiceAlias,
		&i.Organization.InvoiceEmail,
		&i.FleetProfile.ID,
		&i.FleetProfile.Uuid,
		&i.FleetProfile.OrganizationID,
		&i.FleetProfile.BrandID,
		&i.FleetProfile.TaxNumber,
		&i.FleetProfile.TaxOffice,
		&i.FleetProfile.LegalName,
		&i.FleetProfile.ContactName,
		&i.FleetProfile.ContactPhone,
		&i.FleetProfile.BillingEmail,
		&i.FleetProfile.ReportFrequency,
		&i.FleetProfile.ReportLocale,
		&i.FleetProfile.PrimaryUserID,
		&i.FleetProfile.CreatedByUserID,
		&i.FleetProfile.CreatedAt,
		&i.FleetProfile.UpdatedAt,
	)
	return i, err
}

const getFleetByUUID = `-- name: GetFleetByUUID :one
SELECT o.id, o.uuid, o.slug, o.name, o.city, o.district, o.phone, o.address, o.logo_object_key, o.status, o.plan_code, o.access_starts_at, o.access_ends_at, o.created_at, o.updated_at, o.deleted_at, o.email, o.website, o.tagline, o.footer_text, o.paper_size, o.primary_color, o.type, o.parent_id, o.brand_id, o.currency, o.locale, o.timezone, o.country_id, o.contract_pdf_key, o.contract_valid_until, o.settings, o.province_id, o.district_id, o.phone_raw, o.google_business_url, o.latitude, o.longitude, o.invoice_vkn, o.invoice_tckn, o.invoice_tax_office, o.invoice_legal_name, o.einvoice_registered, o.einvoice_alias, o.invoice_email, fp.id, fp.uuid, fp.organization_id, fp.brand_id, fp.tax_number, fp.tax_office, fp.legal_name, fp.contact_name, fp.contact_phone, fp.billing_email, fp.report_frequency, fp.report_locale, fp.primary_user_id, fp.created_by_user_id, fp.created_at, fp.updated_at
FROM organizations o
JOIN fleet_profiles fp ON fp.organization_id = o.id
WHERE o.uuid = $1 AND o.type = 'fleet' AND o.deleted_at IS NULL
`

type GetFleetByUUIDRow struct {
	Organization Organization `json:"organization"`
	FleetProfile FleetProfile `json:"fleet_profile"`
}

func (q *Queries) GetFleetByUUID(ctx context.Context, argUuid uuid.UUID) (GetFleetByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getFleetByUUID, argUuid)
	var i GetFleetByUUIDRow
	err := row.Scan(
		&i.Organization.ID,
		&i.Organization.Uuid,
		&i.Organization.Slug,
		&i.Organization.Name,
		&i.Organization.City,
		&i.Organization.District,
		&i.Organization.Phone,
		&i.Organization.Address,
		&i.Organization.LogoObjectKey,
		&i.Organization.Status,
		&i.Organization.PlanCode,
		&i.Organization.AccessStartsAt,
		&i.Organization.AccessEndsAt,
		&i.Organization.CreatedAt,
		&i.Organization.UpdatedAt,
		&i.Organization.DeletedAt,
		&i.Organization.Email,
		&i.Organization.Website,
		&i.Organization.Tagline,
		&i.Organization.FooterText,
		&i.Organization.PaperSize,
		&i.Organization.PrimaryColor,
		&i.Organization.Type,
		&i.Organization.ParentID,
		&i.Organization.BrandID,
		&i.Organization.Currency,
		&i.Organization.Locale,
		&i.Organization.Timezone,
		&i.Organization.CountryID,
		&i.Organization.ContractPdfKey,
		&i.Organization.ContractValidUntil,
		&i.Organization.Settings,
		&i.Organization.ProvinceID,
		&i.Organization.DistrictID,
		&i.Organization.PhoneRaw,
		&i.Organization.GoogleBusinessUrl,
		&i.Organization.Latitude,
		&i.Organization.Longitude,
		&i.Organization.InvoiceVkn,
		&i.Organization.InvoiceTckn,
		&i.Organization.InvoiceTaxOffice,
		&i.Organization.InvoiceLegalName,
		&i.Organization.EinvoiceRegistered,
		&i.Organization.EinvoiceAlias,
		&i.Organization.InvoiceEmail,
		&i.FleetProfile.ID,
		&i.FleetProfile.Uuid,
		&i.FleetProfile.OrganizationID,
		&i.FleetProfile.BrandID,
		&i.FleetProfile.TaxNumber,
		&i.FleetProfile.TaxOffice,
		&i.FleetProfile.LegalName,
		&i.FleetProfile.ContactName,
		&i.FleetProfile.ContactPhone,
		&i.FleetProfile.BillingEmail,
		&i.FleetProfile.ReportFrequency,
		&i.FleetProfile.ReportLocale,
		&i.FleetProfile.PrimaryUserID,
		&i.FleetProfile.CreatedByUserID,
		&i.FleetProfile.CreatedAt,
		&i.FleetProfile.UpdatedAt,
	)
	return i, err
}

const getFleetDealerLinkByUUID = `-- name: GetFleetDealerLinkByUUID :one
SELECT id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at FROM fleet_dealer_links WHERE uuid = $1
`

func (q *Queries) GetFleetDealerLinkByUUID(ctx context.Context, argUuid uuid.UUID) (FleetDealerLink, error) {
	row := q.db.QueryRow(ctx, getFleetDealerLinkByUUID, argUuid)
	var i FleetDealerLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.DealerOrgID,
		&i.BrandID,
		&i.Status,
		&i.CreatedByOrgID,
		&i.CreatedByUserID,
		&i.CariAccountID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetProfileByOrg = `-- name: GetFleetProfileByOrg :one
SELECT id, uuid, organization_id, brand_id, tax_number, tax_office, legal_name, contact_name, contact_phone, billing_email, report_frequency, report_locale, primary_user_id, created_by_user_id, created_at, updated_at FROM fleet_profiles WHERE organization_id = $1
`

func (q *Queries) GetFleetProfileByOrg(ctx context.Context, organizationID int64) (FleetProfile, error) {
	row := q.db.QueryRow(ctx, getFleetProfileByOrg, organizationID)
	var i FleetProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.LegalName,
		&i.ContactName,
		&i.ContactPhone,
		&i.BillingEmail,
		&i.ReportFrequency,
		&i.ReportLocale,
		&i.PrimaryUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetReportByUUID = `-- name: GetFleetReportByUUID :one
SELECT id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at FROM fleet_reports WHERE uuid = $1
`

func (q *Queries) GetFleetReportByUUID(ctx context.Context, argUuid uuid.UUID) (FleetReport, error) {
	row := q.db.QueryRow(ctx, getFleetReportByUUID, argUuid)
	var i FleetReport
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Locale,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.EmailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenFleetDealerLink = `-- name: GetOpenFleetDealerLink :one
SELECT id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at FROM fleet_dealer_links
WHERE fleet_org_id = $1 AND dealer_org_id = $2
  AND status <> 'ended'
`

type GetOpenFleetDealerLinkParams struct {
	FleetOrgID  int64 `json:"fleet_org_id"`
	DealerOrgID int64 `json:"dealer_org_id"`
}

// The pending or active link of (fleet, dealer), if any.
func (q *Queries) GetOpenFleetDealerLink(ctx context.Context, arg GetOpenFleetDealerLinkParams) (FleetDealerLink, error) {
	row := q.db.QueryRow(ctx, getOpenFleetDealerLink, arg.FleetOrgID, arg.DealerOrgID)
	var i FleetDealerLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.DealerOrgID,
		&i.BrandID,
		&i.Status,
		&i.CreatedByOrgID,
		&i.CreatedByUserID,
		&i.CariAccountID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDealerFleets = `-- name: ListDealerFleets :many
WITH fl AS (
    SELECT l.id AS link_id, l.uuid AS link_uuid, l.status AS link_status,
           l.started_at, l.ended_at, l.created_at,
           l.cari_account_id, l.dealer_org_id,
           d.uuid AS dealer_uuid, d.name AS dealer_name,
           f.id AS fleet_org_id, f.uuid AS fleet_uuid, f.name, f.status AS fleet_status,
           fp.tax_number, fp.legal_name,
           (SELECT COUNT(*) FROM vehicles v
            WHERE v.fleet_org_id = f.id AND v.deleted_at IS NULL)::bigint AS vehicle_count,
           (SELECT MAX(s.completed_at) FROM services s
            JOIN vehicles v ON v.id = s.vehicle_id
            WHERE v.fleet_org_id = f.id AND s.organization_id = l.dealer_org_id
              AND s.status = 'completed')::timestamptz AS last_service_at
    FROM fleet_dealer_links l
    JOIN organizations f ON f.id = l.fleet_org_id AND f.deleted_at IS NULL
    JOIN organizations d ON d.id = l.dealer_org_id
    JOIN fleet_profiles fp ON fp.organization_id = f.id
    WHERE l.brand_id = $7
      AND ($8::bigint[] IS NULL OR l.dealer_org_id = ANY ($8::bigint[]))
      AND (
        COALESCE(cardinality($9::text[]), 0) = 0
        OR l.status = ANY ($9::text[])
      )
      AND (
        $10::text IS NULL
        OR f.name ILIKE '%' || $10 || '%'
        OR fp.legal_name ILIKE '%' || $10 || '%'
        OR fp.tax_number LIKE $10 || '%'
      )
)
SELECT link_id, link_uuid, link_status, started_at, ended_at, created_at, cari_account_id, dealer_org_id, dealer_uuid, dealer_name, fleet_org_id, fleet_uuid, name, fleet_status, tax_number, legal_name, vehicle_count, last_service_at FROM fl
WHERE ($1::bigint IS NULL OR fl.vehicle_count >= $1)
  AND ($2::bigint IS NULL OR fl.vehicle_count <= $2)
ORDER BY
  CASE WHEN NOT $3::bool AND $4::text = 'name' THEN fl.name END ASC,
  CASE WHEN $3::bool AND $4::text = 'name' THEN fl.name END DESC,
  CASE WHEN NOT $3::bool AND $4::text = 'vehicle_count' THEN fl.vehicle_count END ASC,
  CASE WHEN $3::bool AND $4::text = 'vehicle_count' THEN fl.vehicle_count END DESC,
  CASE WHEN NOT $3::bool AND $4::text = 'created_at' THEN fl.created_at END ASC,
  CASE WHEN $3::bool AND $4::text = 'created_at' THEN fl.created_at END DESC,
  -- Nullable column: its own pair so NULLS LAST does not affect the others.
  CASE WHEN NOT $3::bool AND $4::text = 'last_service_at' THEN fl.last_service_at END ASC NULLS LAST,
  CASE WHEN $3::bool AND $4::text = 'last_service_at' THEN fl.last_service_at END DESC NULLS LAST,
  CASE WHEN $3::bool THEN fl.link_id END DESC,
  fl.link_id ASC
LIMIT $6 OFFSET $5
`

type ListDealerFleetsParams struct {
	VehicleCountMin pgtype.Int8 `json:"vehicle_count_min"`
	VehicleCountMax pgtype.Int8 `json:"vehicle_count_max"`
	SortDesc        bool        `json:"sort_desc"`
	SortKey         string      `json:"sort_key"`
	OffsetCount     int32       `json:"offset_count"`
	LimitCount      int32       `json:"limit_count"`
	BrandID         int64       `json:"brand_id"`
	DealerOrgIds    []int64     `json:"dealer_org_ids"`
	Statuses        []string    `json:"statuses"`
	Q               pgtype.Text `json:"q"`
}

type ListDealerFleetsRow struct {
	LinkID        int64              `json:"link_id"`
	LinkUuid      uuid.UUID          `json:"link_uuid"`
	LinkStatus    string             `json:"link_status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CariAccountID pgtype.Int8        `json:"cari_account_id"`
	DealerOrgID   int64              `json:"dealer_org_id"`
	DealerUuid    uuid.UUID          `json:"dealer_uuid"`
	DealerName    string             `json:"dealer_name"`
	FleetOrgID    int64              `json:"fleet_org_id"`
	FleetUuid     uuid.UUID          `json:"fleet_uuid"`
	Name          string             `json:"name"`
	FleetStatus   string             `json:"fleet_status"`
	TaxNumber     string             `json:"tax_number"`
	LegalName     string             `json:"legal_name"`
	VehicleCount  int64              `json:"vehicle_count"`
	LastServiceAt pgtype.Timestamptz `json:"last_service_at"`
}

// Fleets linked to the dealers in scope, one row per link. dealer_org_ids
// NULL: every dealer of the brand (brand/all scope). Sort: docs/list-contract.md,
// keys name | vehicle_count | last_service_at | created_at (the link's),
// default name. last_service_at is the last completed service of a fleet
// vehicle at the linked dealer.
func (q *Queries) ListDealerFleets(ctx context.Context, arg ListDealerFleetsParams) ([]ListDealerFleetsRow, error) {
	rows, err := q.db.Query(ctx, listDealerFleets,
		arg.VehicleCountMin,
		arg.VehicleCountMax,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
		arg.BrandID,
		arg.DealerOrgIds,
		arg.Statuses,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealerFleetsRow{}
	for rows.Next() {
		var i ListDealerFleetsRow
		if err := rows.Scan(
			&i.LinkID,
			&i.LinkUuid,
			&i.LinkStatus,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.CariAccountID,
			&i.DealerOrgID,
			&i.DealerUuid,
			&i.DealerName,
			&i.FleetOrgID,
			&i.FleetUuid,
			&i.Name,
			&i.FleetStatus,
			&i.TaxNumber,
			&i.LegalName,
			&i.VehicleCount,
			&i.LastServiceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetDealerLinks = `-- name: ListFleetDealerLinks :many
SELECT l.id, l.uuid, l.fleet_org_id, l.dealer_org_id, l.brand_id, l.status, l.created_by_org_id, l.created_by_user_id, l.cari_account_id, l.started_at, l.ended_at, l.created_at, l.updated_at, d.uuid AS dealer_uuid, d.name AS dealer_name, d.type AS dealer_type
FROM fleet_dealer_links l
JOIN organizations d ON d.id = l.dealer_org_id
WHERE l.fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR l.status = ANY ($2::text[])
  )
ORDER BY l.created_at DESC, l.id DESC
`

type ListFleetDealerLinksParams struct {
	FleetOrgID int64    `json:"fleet_org_id"`
	Statuses   []string `json:"statuses"`
}

type ListFleetDealerLinksRow struct {
	FleetDealerLink FleetDealerLink `json:"fleet_dealer_link"`
	DealerUuid      uuid.UUID       `json:"dealer_uuid"`
	DealerName      string          `json:"dealer_name"`
	DealerType      string          `json:"dealer_type"`
}

// Links of a fleet with the dealer names (fleet card, portal).
func (q *Queries) ListFleetDealerLinks(ctx context.Context, arg ListFleetDealerLinksParams) ([]ListFleetDealerLinksRow, error) {
	rows, err := q.db.Query(ctx, listFleetDealerLinks, arg.FleetOrgID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetDealerLinksRow{}
	for rows.Next() {
		var i ListFleetDealerLinksRow
		if err := rows.Scan(
			&i.FleetDealerLink.ID,
			&i.FleetDealerLink.Uuid,
			&i.FleetDealerLink.FleetOrgID,
			&i.FleetDealerLink.DealerOrgID,
			&i.FleetDealerLink.BrandID,
			&i.FleetDealerLink.Status,
			&i.FleetDealerLink.CreatedByOrgID,
			&i.FleetDealerLink.CreatedByUserID,
			&i.FleetDealerLink.CariAccountID,
			&i.FleetDealerLink.StartedAt,
			&i.FleetDealerLink.EndedAt,
			&i.FleetDealerLink.CreatedAt,
			&i.FleetDealerLink.UpdatedAt,
			&i.DealerUuid,
			&i.DealerName,
			&i.DealerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetReports = `-- name: ListFleetReports :many
SELECT id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at FROM fleet_reports
WHERE fleet_org_id = $1
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR status = ANY ($2::text[])
  )
ORDER BY period_start DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListFleetReportsParams struct {
	FleetOrgID  int64    `json:"fleet_org_id"`
	Statuses    []string `json:"statuses"`
	OffsetCount int32    `json:"offset_count"`
	LimitCount  int32    `json:"limit_count"`
}

func (q *Queries) ListFleetReports(ctx context.Context, arg ListFleetReportsParams) ([]FleetReport, error) {
	rows, err := q.db.Query(ctx, listFleetReports,
		arg.FleetOrgID,
		arg.Statuses,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FleetReport{}
	for rows.Next() {
		var i FleetReport
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FleetOrgID,
			&i.BrandID,
			&i.PeriodKind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Locale,
			&i.StorageKey,
			&i.Status,
			&i.Error,
			&i.EmailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetVehicles = `-- name: ListFleetVehicles :many
WITH fv AS (
    SELECT v.id, v.uuid, v.user_id, v.plate, v.plate_country, v.vin, v.model_year, v.created_at,
           cb.uuid AS car_brand_uuid, cb.name AS car_brand_name,
           cm.uuid AS car_model_uuid, cm.name AS car_model_name,
           (SELECT MAX(s.completed_at) FROM services s
            WHERE s.vehicle_id = v.id AND s.status = 'completed'
              AND ($5::bigint[] IS NULL
                   OR s.organization_id = ANY ($5::bigint[])))::timestamptz AS last_service_at,
           (SELECT COUNT(*) FROM warranties w
            WHERE w.vehicle_id = v.id AND w.status = 'active' AND w.end_at > NOW()
              AND ($5::bigint[] IS NULL
                   OR w.organization_id = ANY ($5::bigint[])))::bigint AS active_warranty_count
    FROM vehicles v
    LEFT JOIN car_brands cb ON cb.id = v.car_brand_id
    LEFT JOIN car_models cm ON cm.id = v.car_model_id
    WHERE v.fleet_org_id = $6::bigint AND v.deleted_at IS NULL
      AND (
        $7::text IS NULL
        OR v.plate ILIKE '%' || $7 || '%'
        OR v.plate_normalized LIKE $8::text || '%'
        OR v.vin ILIKE $7 || '%'
        OR cb.name ILIKE '%' || $7 || '%'
        OR cm.name ILIKE '%' || $7 || '%'
      )
)
SELECT id, uuid, user_id, plate, plate_country, vin, model_year, created_at, car_brand_uuid, car_brand_name, car_model_uuid, car_model_name, last_service_at, active_warranty_count FROM fv
ORDER BY
  CASE WHEN NOT $1::bool AND $2::text = 'plate' THEN fv.plate END ASC NULLS LAST,
  CASE WHEN $1::bool AND $2::text = 'plate' THEN fv.plate END DESC NULLS LAST,
  CASE WHEN NOT $1::bool AND $2::text = 'car_brand' THEN fv.car_brand_name END ASC NULLS LAST,
  CASE WHEN $1::bool AND $2::text = 'car_brand' THEN fv.car_brand_name END DESC NULLS LAST,
  CASE WHEN NOT $1::bool AND $2::text = 'last_service_at' THEN fv.last_service_at END ASC NULLS LAST,
  CASE WHEN $1::bool AND $2::text = 'last_service_at' THEN fv.last_service_at END DESC NULLS LAST,
  CASE WHEN NOT $1::bool AND $2::text = 'active_warranty_count' THEN fv.active_warranty_count END ASC,
  CASE WHEN $1::bool AND $2::text = 'active_warranty_count' THEN fv.active_warranty_count END DESC,
  CASE WHEN NOT $1::bool AND $2::text = 'created_at' THEN fv.created_at END ASC,
  CASE WHEN $1::bool AND $2::text = 'created_at' THEN fv.created_at END DESC,
  CASE WHEN $1::bool THEN fv.id END DESC,
  fv.id ASC
LIMIT $4 OFFSET $3
`

type ListFleetVehiclesParams struct {
	SortDesc      bool        `json:"sort_desc"`
	SortKey       string      `json:"sort_key"`
	OffsetCount   int32       `json:"offset_count"`
	LimitCount    int32       `json:"limit_count"`
	ServiceOrgIds []int64     `json:"service_org_ids"`
	FleetOrgID    int64       `json:"fleet_org_id"`
	Q             pgtype.Text `json:"q"`
	QPlate        pgtype.Text `json:"q_plate"`
}

type ListFleetVehiclesRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	Plate               pgtype.Text        `json:"plate"`
	PlateCountry        pgtype.Text        `json:"plate_country"`
	Vin                 pgtype.Text        `json:"vin"`
	ModelYear           pgtype.Int2        `json:"model_year"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CarBrandUuid        pgtype.UUID        `json:"car_brand_uuid"`
	CarBrandName        pgtype.Text        `json:"car_brand_name"`
	CarModelUuid        pgtype.UUID        `json:"car_model_uuid"`
	CarModelName        pgtype.Text        `json:"car_model_name"`
	LastServiceAt       pgtype.Timestamptz `json:"last_service_at"`
	ActiveWarrantyCount int64              `json:"active_warranty_count"`
}

// Vehicles of a fleet. service_org_ids limits last_service_at and
// active_warranty_count to services of those organizations (a dealer sees
// its own work); NULL counts every service (portal, center). Sort keys
// plate | car_brand | last_service_at | active_warranty_count | created_at,
// default plate.
func (q *Queries) ListFleetVehicles(ctx context.Context, arg ListFleetVehiclesParams) ([]ListFleetVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listFleetVehicles,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
		arg.ServiceOrgIds,
		arg.FleetOrgID,
		arg.Q,
		arg.QPlate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFleetVehiclesRow{}
	for rows.Next() {
		var i ListFleetVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Plate,
			&i.PlateCountry,
			&i.Vin,
			&i.ModelYear,
			&i.CreatedAt,
			&i.CarBrandUuid,
			&i.CarBrandName,
			&i.CarModelUuid,
			&i.CarModelName,
			&i.LastServiceAt,
			&i.ActiveWarrantyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFleetReportEmailed = `-- name: MarkFleetReportEmailed :one
UPDATE fleet_reports
SET emailed_at = NOW()
WHERE id = $1 AND status = 'ready' AND emailed_at IS NULL
RETURNING id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at
`

func (q *Queries) MarkFleetReportEmailed(ctx context.Context, id int64) (FleetReport, error) {
	row := q.db.QueryRow(ctx, markFleetReportEmailed, id)
	var i FleetReport
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Locale,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.EmailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFleetReportFailed = `-- name: MarkFleetReportFailed :one
UPDATE fleet_reports
SET status = 'failed', error = $1
WHERE id = $2 AND status = 'pending'
RETURNING id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at
`

type MarkFleetReportFailedParams struct {
	Error pgtype.Text `json:"error"`
	ID    int64       `json:"id"`
}

func (q *Queries) MarkFleetReportFailed(ctx context.Context, arg MarkFleetReportFailedParams) (FleetReport, error) {
	row := q.db.QueryRow(ctx, markFleetReportFailed, arg.Error, arg.ID)
	var i FleetReport
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Locale,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.EmailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFleetReportReady = `-- name: MarkFleetReportReady :one
UPDATE fleet_reports
SET status = 'ready', storage_key = $1, error = NULL
WHERE id = $2 AND status = 'pending'
RETURNING id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at
`

type MarkFleetReportReadyParams struct {
	StorageKey pgtype.Text `json:"storage_key"`
	ID         int64       `json:"id"`
}

func (q *Queries) MarkFleetReportReady(ctx context.Context, arg MarkFleetReportReadyParams) (FleetReport, error) {
	row := q.db.QueryRow(ctx, markFleetReportReady, arg.StorageKey, arg.ID)
	var i FleetReport
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Locale,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.EmailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setFleetDealerLinkCari = `-- name: SetFleetDealerLinkCari :one
UPDATE fleet_dealer_links
SET cari_account_id = $1
WHERE id = $2 AND cari_account_id IS NULL
RETURNING id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at
`

type SetFleetDealerLinkCariParams struct {
	CariAccountID pgtype.Int8 `json:"cari_account_id"`
	ID            int64       `json:"id"`
}

// Records the fleet cari in the dealer's ledger once (CAS on NULL).
func (q *Queries) SetFleetDealerLinkCari(ctx context.Context, arg SetFleetDealerLinkCariParams) (FleetDealerLink, error) {
	row := q.db.QueryRow(ctx, setFleetDealerLinkCari, arg.CariAccountID, arg.ID)
	var i FleetDealerLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.DealerOrgID,
		&i.BrandID,
		&i.Status,
		&i.CreatedByOrgID,
		&i.CreatedByUserID,
		&i.CariAccountID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setVehicleFleet = `-- name: SetVehicleFleet :one
UPDATE vehicles
SET fleet_org_id = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, uuid, user_id, organization_id, brand_id, car_brand_id, car_model_id, model_year, plate, plate_normalized, plate_country, vin, created_at, updated_at, deleted_at, fleet_org_id
`

type SetVehicleFleetParams struct {
	FleetOrgID pgtype.Int8 `json:"fleet_org_id"`
	ID         int64       `json:"id"`
}

// Assigns a vehicle to a fleet (NULL: removes it).
func (q *Queries) SetVehicleFleet(ctx context.Context, arg SetVehicleFleetParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, setVehicleFleet, arg.FleetOrgID, arg.ID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.OrganizationID,
		&i.BrandID,
		&i.CarBrandID,
		&i.CarModelID,
		&i.ModelYear,
		&i.Plate,
		&i.PlateNormalized,
		&i.PlateCountry,
		&i.Vin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FleetOrgID,
	)
	return i, err
}

const transitionFleetDealerLink = `-- name: TransitionFleetDealerLink :one
UPDATE fleet_dealer_links
SET status = $1::text,
    started_at = CASE WHEN $1::text = 'active' THEN COALESCE(started_at, NOW()) ELSE started_at END,
    ended_at = CASE WHEN $1::text = 'ended' THEN NOW() ELSE ended_at END
WHERE uuid = $2 AND status = $3::text AND status <> 'ended'
RETURNING id, uuid, fleet_org_id, dealer_org_id, brand_id, status, created_by_org_id, created_by_user_id, cari_account_id, started_at, ended_at, created_at, updated_at
`

type TransitionFleetDealerLinkParams struct {
	ToStatus   string    `json:"to_status"`
	Uuid       uuid.UUID `json:"uuid"`
	FromStatus string    `json:"from_status"`
}

// Compare-and-set of the link status: the row changes only while it is
// still in from_status (no rows: a concurrent change won). active stamps
// started_at, ended stamps ended_at. ended is final: a new link replaces
// it.
func (q *Queries) TransitionFleetDealerLink(ctx context.Context, arg TransitionFleetDealerLinkParams) (FleetDealerLink, error) {
	row := q.db.QueryRow(ctx, transitionFleetDealerLink, arg.ToStatus, arg.Uuid, arg.FromStatus)
	var i FleetDealerLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.DealerOrgID,
		&i.BrandID,
		&i.Status,
		&i.CreatedByOrgID,
		&i.CreatedByUserID,
		&i.CariAccountID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFleetProfile = `-- name: UpdateFleetProfile :one
UPDATE fleet_profiles
SET tax_office = CASE WHEN $1::bool THEN NULL
                      ELSE COALESCE($2, tax_office) END,
    legal_name = COALESCE($3, legal_name),
    contact_name = CASE WHEN $4::bool THEN NULL
                        ELSE COALESCE($5, contact_name) END,
    contact_phone = CASE WHEN $6::bool THEN NULL
                         ELSE COALESCE($7, contact_phone) END,
    billing_email = CASE WHEN $8::bool THEN NULL
                         ELSE COALESCE($9, billing_email) END,
    report_frequency = COALESCE($10, report_frequency),
    report_locale = COALESCE($11, report_locale),
    primary_user_id = COALESCE($12, primary_user_id)
WHERE organization_id = $13
RETURNING id, uuid, organization_id, brand_id, tax_number, tax_office, legal_name, contact_name, contact_phone, billing_email, report_frequency, report_locale, primary_user_id, created_by_user_id, created_at, updated_at
`

type UpdateFleetProfileParams struct {
	ClearTaxOffice    bool        `json:"clear_tax_office"`
	TaxOffice         pgtype.Text `json:"tax_office"`
	LegalName         pgtype.Text `json:"legal_name"`
	ClearContactName  bool        `json:"clear_contact_name"`
	ContactName       pgtype.Text `json:"contact_name"`
	ClearContactPhone bool        `json:"clear_contact_phone"`
	ContactPhone      pgtype.Text `json:"contact_phone"`
	ClearBillingEmail bool        `json:"clear_billing_email"`
	BillingEmail      pgtype.Text `json:"billing_email"`
	ReportFrequency   pgtype.Text `json:"report_frequency"`
	ReportLocale      pgtype.Text `json:"report_locale"`
	PrimaryUserID     pgtype.Int8 `json:"primary_user_id"`
	OrganizationID    int64       `json:"organization_id"`
}

// NULL keeps a column; the optional text columns are cleared by the
// matching clear_* flag.
func (q *Queries) UpdateFleetProfile(ctx context.Context, arg UpdateFleetProfileParams) (FleetProfile, error) {
	row := q.db.QueryRow(ctx, updateFleetProfile,
		arg.ClearTaxOffice,
		arg.TaxOffice,
		arg.LegalName,
		arg.ClearContactName,
		arg.ContactName,
		arg.ClearContactPhone,
		arg.ContactPhone,
		arg.ClearBillingEmail,
		arg.BillingEmail,
		arg.ReportFrequency,
		arg.ReportLocale,
		arg.PrimaryUserID,
		arg.OrganizationID,
	)
	var i FleetProfile
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.TaxNumber,
		&i.TaxOffice,
		&i.LegalName,
		&i.ContactName,
		&i.ContactPhone,
		&i.BillingEmail,
		&i.ReportFrequency,
		&i.ReportLocale,
		&i.PrimaryUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFleetReport = `-- name: UpsertFleetReport :one
INSERT INTO fleet_reports (fleet_org_id, brand_id, period_kind, period_start, period_end, locale)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (fleet_org_id, period_kind, period_start) DO UPDATE
SET status = CASE WHEN fleet_reports.status = 'failed' THEN 'pending' ELSE fleet_reports.status END,
    error = CASE WHEN fleet_reports.status = 'failed' THEN NULL ELSE fleet_reports.error END,
    locale = CASE WHEN fleet_reports.status = 'failed' THEN EXCLUDED.locale ELSE fleet_reports.locale END
RETURNING id, uuid, fleet_org_id, brand_id, period_kind, period_start, period_end, locale, storage_key, status, error, emailed_at, created_at, updated_at
`

type UpsertFleetReportParams struct {
	FleetOrgID  int64       `json:"fleet_org_id"`
	BrandID     int64       `json:"brand_id"`
	PeriodKind  string      `json:"period_kind"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	Locale      string      `json:"locale"`
}

// One row per (fleet, period); a rerun of a failed period goes back to
// pending, a ready report is kept.
func (q *Queries) UpsertFleetReport(ctx context.Context, arg UpsertFleetReportParams) (FleetReport, error) {
	row := q.db.QueryRow(ctx, upsertFleetReport,
		arg.FleetOrgID,
		arg.BrandID,
		arg.PeriodKind,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Locale,
	)
	var i FleetReport
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FleetOrgID,
		&i.BrandID,
		&i.PeriodKind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Locale,
		&i.StorageKey,
		&i.Status,
		&i.Error,
		&i.EmailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
