// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: glorian_order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGlorianOutboundOrder = `-- name: GetGlorianOutboundOrder :one

SELECT id, uuid, order_no, organization_id, brand_id, seller_org_id, buyer_org_id, seller_warehouse_location_id, buyer_warehouse_location_id, status, currency, rate_snapshot, try_rate, subtotal, tax_total, total, delivery_mode, tracking_no, shipping_document_key, receipt_document_key, external_reference, note, cancel_reason, created_by_user_id, approved_by_user_id, submitted_at, approved_at, ready_at, shipped_at, delivered_at, received_at, cancel_requested_at, cancelled_at, created_at, updated_at FROM orders
WHERE id = $1
`

// TEC-271 (F2-02f): Glorian order outbound. An order of the glorian brand
// whose lines hold products synced from a connection is sent to that
// connection's hub as one order per connection (order_outbounds).
func (q *Queries) GetGlorianOutboundOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getGlorianOutboundOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrderNo,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.BuyerOrgID,
		&i.SellerWarehouseLocationID,
		&i.BuyerWarehouseLocationID,
		&i.Status,
		&i.Currency,
		&i.RateSnapshot,
		&i.TryRate,
		&i.Subtotal,
		&i.TaxTotal,
		&i.Total,
		&i.DeliveryMode,
		&i.TrackingNo,
		&i.ShippingDocumentKey,
		&i.ReceiptDocumentKey,
		&i.ExternalReference,
		&i.Note,
		&i.CancelReason,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ReadyAt,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.ReceivedAt,
		&i.CancelRequestedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderOutboundByID = `-- name: GetOrderOutboundByID :one
SELECT id, uuid, organization_id, brand_id, order_id, connection_id, external_reference, state, held_reason, attempts, last_error, created_at, updated_at FROM order_outbounds
WHERE id = $1
`

func (q *Queries) GetOrderOutboundByID(ctx context.Context, id int64) (OrderOutbound, error) {
	row := q.db.QueryRow(ctx, getOrderOutboundByID, id)
	var i OrderOutbound
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.OrderID,
		&i.ConnectionID,
		&i.ExternalReference,
		&i.State,
		&i.HeldReason,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlorianOrderUnits = `-- name: ListGlorianOrderUnits :many
SELECT i.id AS order_item_id,
       p.connection_id::bigint AS connection_id,
       p.external_id::text AS product_external_id,
       u.barcode
FROM order_items i
JOIN products p ON p.id = i.product_id
JOIN order_item_units oiu ON oiu.order_item_id = i.id
JOIN units u ON u.id = oiu.unit_id
WHERE i.order_id = $1
  AND p.connection_id IS NOT NULL
  AND p.external_id IS NOT NULL
  AND u.unit_kind = 'serial'
ORDER BY i.id, oiu.id
`

type ListGlorianOrderUnitsRow struct {
	OrderItemID       int64  `json:"order_item_id"`
	ConnectionID      int64  `json:"connection_id"`
	ProductExternalID string `json:"product_external_id"`
	Barcode           string `json:"barcode"`
}

// Serial units assigned to the order's lines whose product is synced from
// a connection, in line order. Olex and local products have no connection
// and never appear.
func (q *Queries) ListGlorianOrderUnits(ctx context.Context, orderID int64) ([]ListGlorianOrderUnitsRow, error) {
	rows, err := q.db.Query(ctx, listGlorianOrderUnits, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlorianOrderUnitsRow{}
	for rows.Next() {
		var i ListGlorianOrderUnitsRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.ConnectionID,
			&i.ProductExternalID,
			&i.Barcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlorianPartiesByPhone = `-- name: ListGlorianPartiesByPhone :many
SELECT id, uuid, organization_id, brand_id, connection_id, remote_id, name, phone_e164, active, synced_at, created_at, updated_at FROM integration_external_parties
WHERE connection_id = $1
  AND phone_e164 = $2
  AND active
ORDER BY id
LIMIT 2
`

type ListGlorianPartiesByPhoneParams struct {
	ConnectionID int64       `json:"connection_id"`
	PhoneE164    pgtype.Text `json:"phone_e164"`
}

// Active dealers of the connection with the buyer's phone: the order's
// customer link (exactly one match links, none or several hold).
func (q *Queries) ListGlorianPartiesByPhone(ctx context.Context, arg ListGlorianPartiesByPhoneParams) ([]IntegrationExternalParty, error) {
	rows, err := q.db.Query(ctx, listGlorianPartiesByPhone, arg.ConnectionID, arg.PhoneE164)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationExternalParty{}
	for rows.Next() {
		var i IntegrationExternalParty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.ConnectionID,
			&i.RemoteID,
			&i.Name,
			&i.PhoneE164,
			&i.Active,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldOrderOutbounds = `-- name: ListHeldOrderOutbounds :many
SELECT id, uuid, organization_id, brand_id, order_id, connection_id, external_reference, state, held_reason, attempts, last_error, created_at, updated_at FROM order_outbounds
WHERE state = 'held'
  AND ($1::bigint = 0 OR connection_id = $1::bigint)
  AND id > $2::bigint
ORDER BY id
LIMIT $3
`

type ListHeldOrderOutboundsParams struct {
	ConnectionID int64 `json:"connection_id"`
	AfterID      int64 `json:"after_id"`
	RowLimit     int32 `json:"row_limit"`
}

// Held outbounds of a connection (0: every connection) after the keyset
// id, oldest first.
func (q *Queries) ListHeldOrderOutbounds(ctx context.Context, arg ListHeldOrderOutboundsParams) ([]OrderOutbound, error) {
	rows, err := q.db.Query(ctx, listHeldOrderOutbounds, arg.ConnectionID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOutbound{}
	for rows.Next() {
		var i OrderOutbound
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.OrderID,
			&i.ConnectionID,
			&i.ExternalReference,
			&i.State,
			&i.HeldReason,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderOutboundsByOrder = `-- name: ListOrderOutboundsByOrder :many
SELECT id, uuid, organization_id, brand_id, order_id, connection_id, external_reference, state, held_reason, attempts, last_error, created_at, updated_at FROM order_outbounds
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderOutboundsByOrder(ctx context.Context, orderID int64) ([]OrderOutbound, error) {
	rows, err := q.db.Query(ctx, listOrderOutboundsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOutbound{}
	for rows.Next() {
		var i OrderOutbound
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.OrderID,
			&i.ConnectionID,
			&i.ExternalReference,
			&i.State,
			&i.HeldReason,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
