// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countImportJobsFiltered = `-- name: CountImportJobsFiltered :one
SELECT COUNT(*)::bigint
FROM import_jobs i
WHERE (
    ($1::bigint IS NULL AND i.organization_id IS NULL)
    OR i.organization_id = $1
  )
  AND ($2::bigint IS NULL OR i.actor_id = $2)
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR i.status = ANY ($3::text[])
  )
  AND (
    COALESCE(cardinality($4::text[]), 0) = 0
    OR i.resource = ANY ($4::text[])
  )
  AND (
    COALESCE(cardinality($5::text[]), 0) = 0
    OR i.format = ANY ($5::text[])
  )
  AND ($6::timestamptz IS NULL OR i.created_at >= $6)
  AND ($7::timestamptz IS NULL OR i.created_at < $7)
  AND (
    $8::text IS NULL
    OR i.resource ILIKE '%' || $8 || '%'
    OR i.source_filename ILIKE '%' || $8 || '%'
  )
`

type CountImportJobsFilteredParams struct {
	OrganizationID pgtype.Int8        `json:"organization_id"`
	ActorID        pgtype.Int8        `json:"actor_id"`
	Statuses       []string           `json:"statuses"`
	Resources      []string           `json:"resources"`
	Formats        []string           `json:"formats"`
	CreatedFrom    pgtype.Timestamptz `json:"created_from"`
	CreatedBefore  pgtype.Timestamptz `json:"created_before"`
	Q              pgtype.Text        `json:"q"`
}

func (q *Queries) CountImportJobsFiltered(ctx context.Context, arg CountImportJobsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobsFiltered,
		arg.OrganizationID,
		arg.ActorID,
		arg.Statuses,
		arg.Resources,
		arg.Formats,
		arg.CreatedFrom,
		arg.CreatedBefore,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (resource, actor_id, format, locale, status, file_key, organization_id, source_filename)
VALUES ($1, $2, $3, $4, 'uploaded', $5, $6, $7)
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type CreateImportJobParams struct {
	Resource       string      `json:"resource"`
	ActorID        int64       `json:"actor_id"`
	Format         string      `json:"format"`
	Locale         string      `json:"locale"`
	FileKey        pgtype.Text `json:"file_key"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	SourceFilename string      `json:"source_filename"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.Resource,
		arg.ActorID,
		arg.Format,
		arg.Locale,
		arg.FileKey,
		arg.OrganizationID,
		arg.SourceFilename,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const getImportJobByUUID = `-- name: GetImportJobByUUID :one
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename FROM import_jobs WHERE uuid = $1
`

func (q *Queries) GetImportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByUUID, argUuid)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const insertImportChange = `-- name: InsertImportChange :one
INSERT INTO import_changes (job_id, entity_type, entity_uuid, op, previous_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, job_id, entity_type, entity_uuid, op, previous_json, created_at
`

type InsertImportChangeParams struct {
	JobID        int64     `json:"job_id"`
	EntityType   string    `json:"entity_type"`
	EntityUuid   uuid.UUID `json:"entity_uuid"`
	Op           string    `json:"op"`
	PreviousJson []byte    `json:"previous_json"`
}

func (q *Queries) InsertImportChange(ctx context.Context, arg InsertImportChangeParams) (ImportChange, error) {
	row := q.db.QueryRow(ctx, insertImportChange,
		arg.JobID,
		arg.EntityType,
		arg.EntityUuid,
		arg.Op,
		arg.PreviousJson,
	)
	var i ImportChange
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.JobID,
		&i.EntityType,
		&i.EntityUuid,
		&i.Op,
		&i.PreviousJson,
		&i.CreatedAt,
	)
	return i, err
}

const listImportChangesForJob = `-- name: ListImportChangesForJob :many
SELECT id, uuid, job_id, entity_type, entity_uuid, op, previous_json, created_at FROM import_changes
WHERE job_id = $1
ORDER BY id ASC
`

func (q *Queries) ListImportChangesForJob(ctx context.Context, jobID int64) ([]ImportChange, error) {
	rows, err := q.db.Query(ctx, listImportChangesForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportChange{}
	for rows.Next() {
		var i ImportChange
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.JobID,
			&i.EntityType,
			&i.EntityUuid,
			&i.Op,
			&i.PreviousJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobsFiltered = `-- name: ListImportJobsFiltered :many
SELECT i.id, i.uuid, i.resource, i.actor_id, i.format, i.locale, i.status, i.file_key, i.mapping_json, i.defaults_json, i.preview_json, i.error, i.rollback_until, i.applied_at, i.created_at, i.updated_at, i.organization_id, i.source_filename, u.uuid AS actor_uuid, u.name AS actor_name, u.surname AS actor_surname
FROM import_jobs i
JOIN users u ON u.id = i.actor_id
WHERE (
    ($1::bigint IS NULL AND i.organization_id IS NULL)
    OR i.organization_id = $1
  )
  AND ($2::bigint IS NULL OR i.actor_id = $2)
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR i.status = ANY ($3::text[])
  )
  AND (
    COALESCE(cardinality($4::text[]), 0) = 0
    OR i.resource = ANY ($4::text[])
  )
  AND (
    COALESCE(cardinality($5::text[]), 0) = 0
    OR i.format = ANY ($5::text[])
  )
  AND ($6::timestamptz IS NULL OR i.created_at >= $6)
  AND ($7::timestamptz IS NULL OR i.created_at < $7)
  AND (
    $8::text IS NULL
    OR i.resource ILIKE '%' || $8 || '%'
    OR i.source_filename ILIKE '%' || $8 || '%'
  )
ORDER BY
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'status' THEN i.status WHEN 'resource' THEN i.resource WHEN 'format' THEN i.format END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'status' THEN i.status WHEN 'resource' THEN i.resource WHEN 'format' THEN i.format END
  END DESC,
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'created_at' THEN i.created_at WHEN 'updated_at' THEN i.updated_at END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'created_at' THEN i.created_at WHEN 'updated_at' THEN i.updated_at END
  END DESC,
  CASE WHEN $9::bool THEN i.id END DESC,
  i.id ASC
LIMIT $12 OFFSET $11
`

type ListImportJobsFilteredParams struct {
	OrganizationID pgtype.Int8        `json:"organization_id"`
	ActorID        pgtype.Int8        `json:"actor_id"`
	Statuses       []string           `json:"statuses"`
	Resources      []string           `json:"resources"`
	Formats        []string           `json:"formats"`
	CreatedFrom    pgtype.Timestamptz `json:"created_from"`
	CreatedBefore  pgtype.Timestamptz `json:"created_before"`
	Q              pgtype.Text        `json:"q"`
	SortDesc       bool               `json:"sort_desc"`
	SortKey        string             `json:"sort_key"`
	OffsetCount    int32              `json:"offset_count"`
	LimitCount     int32              `json:"limit_count"`
}

type ListImportJobsFilteredRow struct {
	ImportJob    ImportJob `json:"import_job"`
	ActorUuid    uuid.UUID `json:"actor_uuid"`
	ActorName    string    `json:"actor_name"`
	ActorSurname string    `json:"actor_surname"`
}

// TEC-365: platform jobs (organization_id NULL; actor_id = own jobs, or NULL
// for admins) and tenant jobs (organization_id). Sort:
// docs/list-contract.md, keys from imports/usecase.SortSpec.
func (q *Queries) ListImportJobsFiltered(ctx context.Context, arg ListImportJobsFilteredParams) ([]ListImportJobsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listImportJobsFiltered,
		arg.OrganizationID,
		arg.ActorID,
		arg.Statuses,
		arg.Resources,
		arg.Formats,
		arg.CreatedFrom,
		arg.CreatedBefore,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportJobsFilteredRow{}
	for rows.Next() {
		var i ListImportJobsFilteredRow
		if err := rows.Scan(
			&i.ImportJob.ID,
			&i.ImportJob.Uuid,
			&i.ImportJob.Resource,
			&i.ImportJob.ActorID,
			&i.ImportJob.Format,
			&i.ImportJob.Locale,
			&i.ImportJob.Status,
			&i.ImportJob.FileKey,
			&i.ImportJob.MappingJson,
			&i.ImportJob.DefaultsJson,
			&i.ImportJob.PreviewJson,
			&i.ImportJob.Error,
			&i.ImportJob.RollbackUntil,
			&i.ImportJob.AppliedAt,
			&i.ImportJob.CreatedAt,
			&i.ImportJob.UpdatedAt,
			&i.ImportJob.OrganizationID,
			&i.ImportJob.SourceFilename,
			&i.ActorUuid,
			&i.ActorName,
			&i.ActorSurname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImportJobApplied = `-- name: MarkImportJobApplied :one
UPDATE import_jobs
SET status = 'applied',
    applied_at = NOW(),
    rollback_until = NOW() + INTERVAL '24 hours',
    preview_json = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type MarkImportJobAppliedParams struct {
	ID          int64  `json:"id"`
	PreviewJson []byte `json:"preview_json"`
}

func (q *Queries) MarkImportJobApplied(ctx context.Context, arg MarkImportJobAppliedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobApplied, arg.ID, arg.PreviewJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const markImportJobApplying = `-- name: MarkImportJobApplying :one
UPDATE import_jobs
SET status = 'applying'
WHERE id = $1 AND status = 'queued'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

func (q *Queries) MarkImportJobApplying(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobApplying, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const markImportJobFailed = `-- name: MarkImportJobFailed :one
UPDATE import_jobs
SET status = 'failed',
    error = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type MarkImportJobFailedParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) MarkImportJobFailed(ctx context.Context, arg MarkImportJobFailedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobFailed, arg.ID, arg.Error)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const markImportJobRolledBack = `-- name: MarkImportJobRolledBack :one
UPDATE import_jobs
SET status = 'rolled_back'
WHERE id = $1 AND status = 'applied'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

func (q *Queries) MarkImportJobRolledBack(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobRolledBack, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const queueImportJob = `-- name: QueueImportJob :one
UPDATE import_jobs
SET status = 'queued'
WHERE uuid = $1 AND status = 'previewed'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

func (q *Queries) QueueImportJob(ctx context.Context, argUuid uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, queueImportJob, argUuid)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const setImportJobPreview = `-- name: SetImportJobPreview :one
UPDATE import_jobs
SET preview_json = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type SetImportJobPreviewParams struct {
	ID          int64  `json:"id"`
	PreviewJson []byte `json:"preview_json"`
}

// TEC-158: staged importers keep their apply/undo report in preview_json.
func (q *Queries) SetImportJobPreview(ctx context.Context, arg SetImportJobPreviewParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, setImportJobPreview, arg.ID, arg.PreviewJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const updateImportJobFileKey = `-- name: UpdateImportJobFileKey :one
UPDATE import_jobs
SET file_key = $2
WHERE uuid = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type UpdateImportJobFileKeyParams struct {
	Uuid    uuid.UUID   `json:"uuid"`
	FileKey pgtype.Text `json:"file_key"`
}

func (q *Queries) UpdateImportJobFileKey(ctx context.Context, arg UpdateImportJobFileKeyParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobFileKey, arg.Uuid, arg.FileKey)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const updateImportJobMapping = `-- name: UpdateImportJobMapping :one
UPDATE import_jobs
SET mapping_json = $2,
    defaults_json = $3,
    status = 'mapped'
WHERE uuid = $1 AND status IN ('uploaded', 'mapped', 'previewed')
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type UpdateImportJobMappingParams struct {
	Uuid         uuid.UUID `json:"uuid"`
	MappingJson  []byte    `json:"mapping_json"`
	DefaultsJson []byte    `json:"defaults_json"`
}

func (q *Queries) UpdateImportJobMapping(ctx context.Context, arg UpdateImportJobMappingParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobMapping, arg.Uuid, arg.MappingJson, arg.DefaultsJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}

const updateImportJobPreview = `-- name: UpdateImportJobPreview :one
UPDATE import_jobs
SET preview_json = $2,
    status = 'previewed'
WHERE uuid = $1 AND status IN ('mapped', 'previewed')
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id, source_filename
`

type UpdateImportJobPreviewParams struct {
	Uuid        uuid.UUID `json:"uuid"`
	PreviewJson []byte    `json:"preview_json"`
}

func (q *Queries) UpdateImportJobPreview(ctx context.Context, arg UpdateImportJobPreviewParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobPreview, arg.Uuid, arg.PreviewJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceFilename,
	)
	return i, err
}
