// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsentForText = `-- name: GetConsentForText :one
SELECT id, uuid, user_id, legal_text_id, kind, locale, text_version, accepted, decided_at, ip, user_agent FROM consents
WHERE user_id = $1 AND legal_text_id = $2
`

type GetConsentForTextParams struct {
	UserID      int64 `json:"user_id"`
	LegalTextID int64 `json:"legal_text_id"`
}

func (q *Queries) GetConsentForText(ctx context.Context, arg GetConsentForTextParams) (Consent, error) {
	row := q.db.QueryRow(ctx, getConsentForText, arg.UserID, arg.LegalTextID)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalTextID,
		&i.Kind,
		&i.Locale,
		&i.TextVersion,
		&i.Accepted,
		&i.DecidedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getLatestConsent = `-- name: GetLatestConsent :one
SELECT id, uuid, user_id, legal_text_id, kind, locale, text_version, accepted, decided_at, ip, user_agent FROM consents
WHERE user_id = $1 AND kind = $2
ORDER BY decided_at DESC, id DESC
LIMIT 1
`

type GetLatestConsentParams struct {
	UserID int64  `json:"user_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) GetLatestConsent(ctx context.Context, arg GetLatestConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, getLatestConsent, arg.UserID, arg.Kind)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalTextID,
		&i.Kind,
		&i.Locale,
		&i.TextVersion,
		&i.Accepted,
		&i.DecidedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getLatestLegalText = `-- name: GetLatestLegalText :one

SELECT id, uuid, kind, locale, version, body, created_by, created_at FROM legal_texts
WHERE kind = $1 AND locale = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestLegalTextParams struct {
	Kind   string `json:"kind"`
	Locale string `json:"locale"`
}

// Portal legal texts and consents (TEC-90).
func (q *Queries) GetLatestLegalText(ctx context.Context, arg GetLatestLegalTextParams) (LegalText, error) {
	row := q.db.QueryRow(ctx, getLatestLegalText, arg.Kind, arg.Locale)
	var i LegalText
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Locale,
		&i.Version,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertConsent = `-- name: InsertConsent :one
INSERT INTO consents (user_id, legal_text_id, kind, locale, text_version, accepted, ip, user_agent)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
ON CONFLICT (user_id, legal_text_id) DO NOTHING
RETURNING id, uuid, user_id, legal_text_id, kind, locale, text_version, accepted, decided_at, ip, user_agent
`

type InsertConsentParams struct {
	UserID      int64       `json:"user_id"`
	LegalTextID int64       `json:"legal_text_id"`
	Kind        string      `json:"kind"`
	Locale      string      `json:"locale"`
	TextVersion int32       `json:"text_version"`
	Accepted    bool        `json:"accepted"`
	Ip          pgtype.Text `json:"ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, insertConsent,
		arg.UserID,
		arg.LegalTextID,
		arg.Kind,
		arg.Locale,
		arg.TextVersion,
		arg.Accepted,
		arg.Ip,
		arg.UserAgent,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LegalTextID,
		&i.Kind,
		&i.Locale,
		&i.TextVersion,
		&i.Accepted,
		&i.DecidedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const insertLegalText = `-- name: InsertLegalText :one
INSERT INTO legal_texts (kind, locale, version, body, created_by)
SELECT $1::text, $2::text, COALESCE(MAX(version), 0) + 1,
       $3::text, $4::bigint
FROM legal_texts
WHERE kind = $1::text AND locale = $2::text
RETURNING id, uuid, kind, locale, version, body, created_by, created_at
`

type InsertLegalTextParams struct {
	Kind      string      `json:"kind"`
	Locale    string      `json:"locale"`
	Body      string      `json:"body"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) InsertLegalText(ctx context.Context, arg InsertLegalTextParams) (LegalText, error) {
	row := q.db.QueryRow(ctx, insertLegalText,
		arg.Kind,
		arg.Locale,
		arg.Body,
		arg.CreatedBy,
	)
	var i LegalText
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Kind,
		&i.Locale,
		&i.Version,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestLegalTexts = `-- name: ListLatestLegalTexts :many
SELECT DISTINCT ON (locale) id, uuid, kind, locale, version, body, created_by, created_at
FROM legal_texts
WHERE kind = $1
ORDER BY locale, version DESC
`

func (q *Queries) ListLatestLegalTexts(ctx context.Context, kind string) ([]LegalText, error) {
	rows, err := q.db.Query(ctx, listLatestLegalTexts, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalText{}
	for rows.Next() {
		var i LegalText
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Kind,
			&i.Locale,
			&i.Version,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalTextVersions = `-- name: ListLegalTextVersions :many
SELECT id, uuid, kind, locale, version, body, created_by, created_at FROM legal_texts
WHERE kind = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListLegalTextVersionsParams struct {
	Kind  string `json:"kind"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListLegalTextVersions(ctx context.Context, arg ListLegalTextVersionsParams) ([]LegalText, error) {
	rows, err := q.db.Query(ctx, listLegalTextVersions, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalText{}
	for rows.Next() {
		var i LegalText
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Kind,
			&i.Locale,
			&i.Version,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
