// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrator_measurements.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const migratorInsertMeasurementDevice = `-- name: MigratorInsertMeasurementDevice :one
INSERT INTO measurement_devices (uuid, organization_id, brand_id, serial, label, created_at, updated_at)
VALUES (
    $1, $2::bigint, $3::bigint, $4::varchar,
    $5::varchar, COALESCE($6::timestamptz, NOW()),
    COALESCE($6::timestamptz, NOW())
)
ON CONFLICT (organization_id, serial) DO NOTHING
RETURNING id
`

type MigratorInsertMeasurementDeviceParams struct {
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	Serial         string             `json:"serial"`
	Label          pgtype.Text        `json:"label"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// A device the organization already holds under the serial is left alone
// (no row then).
func (q *Queries) MigratorInsertMeasurementDevice(ctx context.Context, arg MigratorInsertMeasurementDeviceParams) (int64, error) {
	row := q.db.QueryRow(ctx, migratorInsertMeasurementDevice,
		arg.Uuid,
		arg.OrganizationID,
		arg.BrandID,
		arg.Serial,
		arg.Label,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const migratorInsertMeasurementResult = `-- name: MigratorInsertMeasurementResult :one
INSERT INTO measurement_results (
    uuid, organization_id, brand_id, service_id, vehicle_id, vin, status, raw, device_serial, source,
    created_by, created_at
) VALUES (
    $1, $2::bigint, $3::bigint, $4::bigint,
    $5::bigint, $6::varchar, $7::varchar, $8::jsonb,
    $9::varchar, 'legacy_import', $10::bigint,
    COALESCE($11::timestamptz, NOW())
)
ON CONFLICT (uuid) DO NOTHING
RETURNING id
`

type MigratorInsertMeasurementResultParams struct {
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	ServiceID      pgtype.Int8        `json:"service_id"`
	VehicleID      pgtype.Int8        `json:"vehicle_id"`
	Vin            pgtype.Text        `json:"vin"`
	Status         string             `json:"status"`
	Raw            []byte             `json:"raw"`
	DeviceSerial   pgtype.Text        `json:"device_serial"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Legacy reports carry no idempotency key / client id; the uuid (from
// migration_map) makes a rerun find the row.
func (q *Queries) MigratorInsertMeasurementResult(ctx context.Context, arg MigratorInsertMeasurementResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, migratorInsertMeasurementResult,
		arg.Uuid,
		arg.OrganizationID,
		arg.BrandID,
		arg.ServiceID,
		arg.VehicleID,
		arg.Vin,
		arg.Status,
		arg.Raw,
		arg.DeviceSerial,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const migratorMeasurementDeviceBySerial = `-- name: MigratorMeasurementDeviceBySerial :one
SELECT id, uuid FROM measurement_devices
WHERE organization_id = $1::bigint AND serial = $2::varchar
`

type MigratorMeasurementDeviceBySerialParams struct {
	OrganizationID int64  `json:"organization_id"`
	Serial         string `json:"serial"`
}

type MigratorMeasurementDeviceBySerialRow struct {
	ID   int64     `json:"id"`
	Uuid uuid.UUID `json:"uuid"`
}

func (q *Queries) MigratorMeasurementDeviceBySerial(ctx context.Context, arg MigratorMeasurementDeviceBySerialParams) (MigratorMeasurementDeviceBySerialRow, error) {
	row := q.db.QueryRow(ctx, migratorMeasurementDeviceBySerial, arg.OrganizationID, arg.Serial)
	var i MigratorMeasurementDeviceBySerialRow
	err := row.Scan(&i.ID, &i.Uuid)
	return i, err
}

const migratorMeasurementDeviceByUUID = `-- name: MigratorMeasurementDeviceByUUID :one
SELECT id, organization_id, serial, label FROM measurement_devices WHERE uuid = $1
`

type MigratorMeasurementDeviceByUUIDRow struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	Serial         string      `json:"serial"`
	Label          pgtype.Text `json:"label"`
}

func (q *Queries) MigratorMeasurementDeviceByUUID(ctx context.Context, argUuid uuid.UUID) (MigratorMeasurementDeviceByUUIDRow, error) {
	row := q.db.QueryRow(ctx, migratorMeasurementDeviceByUUID, argUuid)
	var i MigratorMeasurementDeviceByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Serial,
		&i.Label,
	)
	return i, err
}

const migratorMeasurementResultIDByUUID = `-- name: MigratorMeasurementResultIDByUUID :one
SELECT id FROM measurement_results WHERE uuid = $1
`

func (q *Queries) MigratorMeasurementResultIDByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, migratorMeasurementResultIDByUUID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const migratorServiceForMeasurement = `-- name: MigratorServiceForMeasurement :one

SELECT id, organization_id, brand_id, vehicle_id FROM services WHERE uuid = $1
`

type MigratorServiceForMeasurementRow struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
	BrandID        int64 `json:"brand_id"`
	VehicleID      int64 `json:"vehicle_id"`
}

// TEC-262: migrator step 8 (hub nexptg_api_users -> measurement_devices,
// nexptg_reports + nexptg_report_measurements + service_nexptg_report ->
// measurement_results). Written only by cmd/migrator inside a step
// transaction.
func (q *Queries) MigratorServiceForMeasurement(ctx context.Context, argUuid uuid.UUID) (MigratorServiceForMeasurementRow, error) {
	row := q.db.QueryRow(ctx, migratorServiceForMeasurement, argUuid)
	var i MigratorServiceForMeasurementRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
	)
	return i, err
}

const migratorUpdateMeasurementDevice = `-- name: MigratorUpdateMeasurementDevice :exec
UPDATE measurement_devices
SET organization_id = $1::bigint,
    brand_id        = $2::bigint,
    serial          = $3::varchar,
    label           = $4::varchar
WHERE id = $5::bigint
`

type MigratorUpdateMeasurementDeviceParams struct {
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	Serial         string      `json:"serial"`
	Label          pgtype.Text `json:"label"`
	ID             int64       `json:"id"`
}

func (q *Queries) MigratorUpdateMeasurementDevice(ctx context.Context, arg MigratorUpdateMeasurementDeviceParams) error {
	_, err := q.db.Exec(ctx, migratorUpdateMeasurementDevice,
		arg.OrganizationID,
		arg.BrandID,
		arg.Serial,
		arg.Label,
		arg.ID,
	)
	return err
}

const migratorUpdateMeasurementResult = `-- name: MigratorUpdateMeasurementResult :exec
UPDATE measurement_results
SET organization_id = $1::bigint,
    brand_id        = $2::bigint,
    service_id      = $3::bigint,
    vehicle_id      = $4::bigint,
    vin             = $5::varchar,
    status          = $6::varchar,
    raw             = $7::jsonb,
    device_serial   = $8::varchar,
    created_by      = $9::bigint
WHERE id = $10::bigint AND source = 'legacy_import'
`

type MigratorUpdateMeasurementResultParams struct {
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	ServiceID      pgtype.Int8 `json:"service_id"`
	VehicleID      pgtype.Int8 `json:"vehicle_id"`
	Vin            pgtype.Text `json:"vin"`
	Status         string      `json:"status"`
	Raw            []byte      `json:"raw"`
	DeviceSerial   pgtype.Text `json:"device_serial"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
	ID             int64       `json:"id"`
}

func (q *Queries) MigratorUpdateMeasurementResult(ctx context.Context, arg MigratorUpdateMeasurementResultParams) error {
	_, err := q.db.Exec(ctx, migratorUpdateMeasurementResult,
		arg.OrganizationID,
		arg.BrandID,
		arg.ServiceID,
		arg.VehicleID,
		arg.Vin,
		arg.Status,
		arg.Raw,
		arg.DeviceSerial,
		arg.CreatedBy,
		arg.ID,
	)
	return err
}
