// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignMemberRoleBySlug(ctx context.Context, arg AssignMemberRoleBySlugParams) error
	AssignUserRoleBySlug(ctx context.Context, arg AssignUserRoleBySlugParams) error
	AttachNotificationDelivery(ctx context.Context, arg AttachNotificationDeliveryParams) error
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	ClearAppSettingsLogo(ctx context.Context) (AppSetting, error)
	ClearOrganizationLogo(ctx context.Context, argUuid uuid.UUID) (Organization, error)
	ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) (UserTotp, error)
	ConsumeOTP(ctx context.Context, id int64) error
	ConsumeOTPAt(ctx context.Context, arg ConsumeOTPAtParams) error
	ConsumeQRLoginChallenge(ctx context.Context, code string) (QrLoginChallenge, error)
	CountActivityEvents(ctx context.Context, arg CountActivityEventsParams) (int64, error)
	CountAllBulkJobs(ctx context.Context) (int64, error)
	CountAllExportJobs(ctx context.Context) (int64, error)
	CountAllImportJobs(ctx context.Context) (int64, error)
	CountAppLogs(ctx context.Context, arg CountAppLogsParams) (int64, error)
	CountAppLogsByLevel(ctx context.Context) ([]CountAppLogsByLevelRow, error)
	CountBulkJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountDistributorPriceOverrides(ctx context.Context, arg CountDistributorPriceOverridesParams) (int64, error)
	CountDocumentTemplates(ctx context.Context, arg CountDocumentTemplatesParams) (int64, error)
	CountExportJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountExportJobsForOrganization(ctx context.Context, organizationID pgtype.Int8) (int64, error)
	CountImportJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountImportJobsForOrganization(ctx context.Context, organizationID int64) (int64, error)
	CountMessagesByExternalID(ctx context.Context, arg CountMessagesByExternalIDParams) (int64, error)
	CountNotificationDeliveries(ctx context.Context, arg CountNotificationDeliveriesParams) (int64, error)
	CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error)
	CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error)
	CountOutboxByStatus(ctx context.Context, status string) (int64, error)
	CountPermissions(ctx context.Context, q_ pgtype.Text) (int64, error)
	CountPhoneOTPsSince(ctx context.Context, arg CountPhoneOTPsSinceParams) (int64, error)
	CountPlatformNotifications(ctx context.Context, arg CountPlatformNotificationsParams) (int64, error)
	CountProductCategories(ctx context.Context, arg CountProductCategoriesParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountRoles(ctx context.Context, q_ pgtype.Text) (int64, error)
	CountStorageActivity(ctx context.Context, objectKey string) (int64, error)
	CountStorageTrash(ctx context.Context) (int64, error)
	CountUnreadInappForUser(ctx context.Context, userID pgtype.Int8) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersWithRole(ctx context.Context, roleSlug string) (int64, error)
	CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (BulkJob, error)
	CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error)
	CreateDocumentTemplate(ctx context.Context, arg CreateDocumentTemplateParams) (DocumentTemplate, error)
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error)
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error)
	CreateLogPurgeRule(ctx context.Context, arg CreateLogPurgeRuleParams) (LogPurgeRule, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error)
	CreatePhoneOTP(ctx context.Context, arg CreatePhoneOTPParams) (OtpCode, error)
	CreatePlateFormat(ctx context.Context, arg CreatePlateFormatParams) (PlateFormat, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// TEC-144: product categories and products. Every query is brand-filtered;
	// callers pass the active brand (K1/K20). Writes are center-only (K4) and
	// are checked in the use case layer.
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error)
	// TEC-91: QR web sign-in challenges.
	CreateQRLoginChallenge(ctx context.Context, arg CreateQRLoginChallengeParams) (QrLoginChallenge, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTerritory(ctx context.Context, arg CreateTerritoryParams) (Territory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error)
	DeactivateDocumentTemplates(ctx context.Context, arg DeactivateDocumentTemplatesParams) error
	DecideQRLoginChallenge(ctx context.Context, arg DecideQRLoginChallengeParams) (QrLoginChallenge, error)
	DeleteAppLogByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteAppLogsByUUIDs(ctx context.Context, uuids []uuid.UUID) (int64, error)
	DeleteAppLogsMatching(ctx context.Context, arg DeleteAppLogsMatchingParams) (int64, error)
	DeleteDistributorPriceOverride(ctx context.Context, arg DeleteDistributorPriceOverrideParams) (int64, error)
	DeleteDistrict(ctx context.Context, id int64) (int64, error)
	DeleteLogPurgeRule(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteManualExchangeRate(ctx context.Context, arg DeleteManualExchangeRateParams) (int64, error)
	DeleteMemberRoles(ctx context.Context, memberID int64) error
	DeleteNotificationPreferenceRow(ctx context.Context, arg DeleteNotificationPreferenceRowParams) error
	DeleteOAuthAccountByProviderAccount(ctx context.Context, arg DeleteOAuthAccountByProviderAccountParams) error
	DeleteOAuthAccountByUserProvider(ctx context.Context, arg DeleteOAuthAccountByUserProviderParams) error
	DeleteOrgModuleFlag(ctx context.Context, arg DeleteOrgModuleFlagParams) (int64, error)
	DeletePermissionBySlug(ctx context.Context, slug string) error
	DeletePlateFormat(ctx context.Context, countryID int64) (int64, error)
	DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error)
	// Fails with a foreign key violation while products still use the category.
	DeleteProductCategory(ctx context.Context, arg DeleteProductCategoryParams) (int64, error)
	DeleteProductPrice(ctx context.Context, arg DeleteProductPriceParams) (int64, error)
	DeleteProvince(ctx context.Context, id int64) (int64, error)
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteRole(ctx context.Context, argUuid uuid.UUID) error
	DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error
	DeleteStaleQRLoginChallenges(ctx context.Context) (int64, error)
	DeleteStorageShare(ctx context.Context, argUuid uuid.UUID) error
	DeleteStorageStar(ctx context.Context, arg DeleteStorageStarParams) error
	DeleteStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) error
	DeleteSystemModuleFlag(ctx context.Context, moduleKey string) (int64, error)
	DeleteTerritory(ctx context.Context, arg DeleteTerritoryParams) (int64, error)
	DeleteUserTOTP(ctx context.Context, userID int64) error
	DeleteWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) error
	DeleteWebAuthnCredentialByUUID(ctx context.Context, arg DeleteWebAuthnCredentialByUUIDParams) error
	// Every organization below the given one (not including itself).
	Descendants(ctx context.Context, id int64) ([]Organization, error)
	ExtensionExists(ctx context.Context, extname string) (bool, error)
	// The rate of a pair (either direction) on the latest day within
	// [min_date, on_date]; on that day manual > tcmb > ecb, direct before inverse.
	FindPairRate(ctx context.Context, arg FindPairRateParams) (FindPairRateRow, error)
	GetActiveDocumentTemplate(ctx context.Context, arg GetActiveDocumentTemplateParams) (DocumentTemplate, error)
	GetActiveOTPByEmailType(ctx context.Context, arg GetActiveOTPByEmailTypeParams) (OtpCode, error)
	GetActivePhoneOTP(ctx context.Context, arg GetActivePhoneOTPParams) (OtpCode, error)
	GetAppLogByUUID(ctx context.Context, argUuid uuid.UUID) (AppLog, error)
	GetAppSettings(ctx context.Context) (AppSetting, error)
	GetAuthSettings(ctx context.Context) (GetAuthSettingsRow, error)
	GetBrandByID(ctx context.Context, id int64) (Brand, error)
	GetBrandBySlug(ctx context.Context, slug string) (Brand, error)
	GetBrandCenter(ctx context.Context, brandID int64) (Organization, error)
	GetBulkJobByID(ctx context.Context, id int64) (BulkJob, error)
	GetBulkJobByUUID(ctx context.Context, argUuid uuid.UUID) (BulkJob, error)
	GetConsentForText(ctx context.Context, arg GetConsentForTextParams) (Consent, error)
	GetCountryByID(ctx context.Context, id int64) (Country, error)
	GetCountryByISO2(ctx context.Context, iso2 string) (Country, error)
	GetDistributorPriceOverride(ctx context.Context, arg GetDistributorPriceOverrideParams) (GetDistributorPriceOverrideRow, error)
	GetDistrictByID(ctx context.Context, id int64) (District, error)
	GetDocumentRenderByID(ctx context.Context, id int64) (DocumentRender, error)
	GetDocumentRenderByUUID(ctx context.Context, argUuid uuid.UUID) (DocumentRender, error)
	GetDocumentTemplateByID(ctx context.Context, id int64) (DocumentTemplate, error)
	GetDocumentTemplateByUUID(ctx context.Context, argUuid uuid.UUID) (DocumentTemplate, error)
	GetDraftDocumentTemplate(ctx context.Context, arg GetDraftDocumentTemplateParams) (DocumentTemplate, error)
	GetExportJobByID(ctx context.Context, id int64) (ExportJob, error)
	GetExportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ExportJob, error)
	GetGitHubAppSettings(ctx context.Context) (GithubAppSetting, error)
	GetImportJobByID(ctx context.Context, id int64) (ImportJob, error)
	GetImportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ImportJob, error)
	GetLatestConsent(ctx context.Context, arg GetLatestConsentParams) (Consent, error)
	GetLatestKVKKNotice(ctx context.Context, locale string) (KvkkNotice, error)
	// Portal legal texts and consents (TEC-90).
	GetLatestLegalText(ctx context.Context, arg GetLatestLegalTextParams) (LegalText, error)
	GetLatestPhoneOTP(ctx context.Context, arg GetLatestPhoneOTPParams) (OtpCode, error)
	// Stored locale/timezone preferences for i18n.Resolve: the user, the active
	// organization (when given) and the center of its brand, or of the request
	// brand when there is no active organization.
	GetLocaleSources(ctx context.Context, arg GetLocaleSourcesParams) (GetLocaleSourcesRow, error)
	GetLogPurgeRuleByUUID(ctx context.Context, argUuid uuid.UUID) (LogPurgeRule, error)
	GetModule(ctx context.Context, key string) (Module, error)
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	GetNotificationByUUID(ctx context.Context, argUuid uuid.UUID) (Notification, error)
	// Notification center (TEC-87): recipients, templates, preferences,
	// deliveries, channel switches, event catalog mirror, Expo push tokens.
	// Everything Dispatch needs about one recipient: addresses, stored locale
	// sources (user -> organization -> brand center) and the template role.
	// The organization is the user's membership (the event organization first),
	// else the event organization itself (customers of a dealer).
	GetNotificationRecipient(ctx context.Context, arg GetNotificationRecipientParams) (GetNotificationRecipientRow, error)
	GetOAuthAccountByProviderAccount(ctx context.Context, arg GetOAuthAccountByProviderAccountParams) (GetOAuthAccountByProviderAccountRow, error)
	GetOAuthAccountByUserProvider(ctx context.Context, arg GetOAuthAccountByUserProviderParams) (GetOAuthAccountByUserProviderRow, error)
	GetOAuthProviderSettings(ctx context.Context, provider string) (OauthProviderSetting, error)
	GetOTPByUUID(ctx context.Context, argUuid uuid.UUID) (OtpCode, error)
	GetOrgModuleFlag(ctx context.Context, arg GetOrgModuleFlagParams) (ModuleFlag, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOrganizationByUUID(ctx context.Context, argUuid uuid.UUID) (Organization, error)
	GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error)
	GetOrganizationMemberByUserAndOrgUUID(ctx context.Context, arg GetOrganizationMemberByUserAndOrgUUIDParams) (GetOrganizationMemberByUserAndOrgUUIDRow, error)
	GetOrganizationMemberByUserAndSlug(ctx context.Context, arg GetOrganizationMemberByUserAndSlugParams) (GetOrganizationMemberByUserAndSlugRow, error)
	GetOrganizationMemberByUserUUID(ctx context.Context, arg GetOrganizationMemberByUserUUIDParams) (GetOrganizationMemberByUserUUIDRow, error)
	GetOrganizationTreeByUUID(ctx context.Context, argUuid uuid.UUID) (GetOrganizationTreeByUUIDRow, error)
	GetPermissionBySlug(ctx context.Context, slug string) (Permission, error)
	GetPlateFormatByCountry(ctx context.Context, iso2 string) (GetPlateFormatByCountryRow, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	GetProductByUUID(ctx context.Context, arg GetProductByUUIDParams) (Product, error)
	// Search indexer only. Every document carries its brand_id and the search
	// query filters on it (K1/K20).
	GetProductByUUIDForIndex(ctx context.Context, argUuid uuid.UUID) (Product, error)
	GetProductCategory(ctx context.Context, arg GetProductCategoryParams) (ProductCategory, error)
	// TEC-145: catalog API helpers.
	GetProductCategoryByName(ctx context.Context, arg GetProductCategoryByNameParams) (ProductCategory, error)
	GetProductCategoryByUUID(ctx context.Context, arg GetProductCategoryByUUIDParams) (ProductCategory, error)
	GetProductPrice(ctx context.Context, arg GetProductPriceParams) (GetProductPriceRow, error)
	GetProvinceByID(ctx context.Context, id int64) (Province, error)
	GetQRLoginChallengeByCode(ctx context.Context, code string) (QrLoginChallenge, error)
	GetRefreshTokenByHashAny(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByUUID(ctx context.Context, argUuid uuid.UUID) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetRoleByUUID(ctx context.Context, argUuid uuid.UUID) (Role, error)
	GetStepupSettings(ctx context.Context) (StepupSetting, error)
	GetStorageLinkBySlug(ctx context.Context, slug pgtype.Text) (StorageLink, error)
	GetStorageLinkByTokenHash(ctx context.Context, tokenHash pgtype.Text) (StorageLink, error)
	GetStorageLinkByUUID(ctx context.Context, argUuid uuid.UUID) (StorageLink, error)
	GetStorageTrashByOriginalKey(ctx context.Context, originalKey string) (StorageTrash, error)
	GetStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) (StorageTrash, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phoneE164 pgtype.Text) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserTOTPByUserID(ctx context.Context, userID int64) (UserTotp, error)
	GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) (WebauthnCredential, error)
	GetWebAuthnCredentialByUUID(ctx context.Context, arg GetWebAuthnCredentialByUUIDParams) (WebauthnCredential, error)
	// WhatsApp gateway, KVKK notices, conversations and messages (TEC-92).
	GetWhatsAppSettings(ctx context.Context) (WhatsappSetting, error)
	IncrementOTPAttempts(ctx context.Context, id int64) (OtpCode, error)
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error)
	InsertAppLog(ctx context.Context, arg InsertAppLogParams) error
	InsertBulkChange(ctx context.Context, arg InsertBulkChangeParams) (BulkChange, error)
	InsertConsent(ctx context.Context, arg InsertConsentParams) (Consent, error)
	InsertImportChange(ctx context.Context, arg InsertImportChangeParams) (ImportChange, error)
	InsertKVKKNotice(ctx context.Context, arg InsertKVKKNoticeParams) (KvkkNotice, error)
	InsertLegalText(ctx context.Context, arg InsertLegalTextParams) (LegalText, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	// Idempotent on (event_id, user_id, channel): a replayed event returns no row.
	InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (NotificationDelivery, error)
	InsertNotificationHistory(ctx context.Context, arg InsertNotificationHistoryParams) (NotificationHistory, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error
	InsertStorageActivity(ctx context.Context, arg InsertStorageActivityParams) (StorageActivity, error)
	InsertStorageLink(ctx context.Context, arg InsertStorageLinkParams) (StorageLink, error)
	InsertStorageShare(ctx context.Context, arg InsertStorageShareParams) (StorageShare, error)
	InsertStorageStar(ctx context.Context, arg InsertStorageStarParams) (StorageStar, error)
	InsertStorageTrash(ctx context.Context, arg InsertStorageTrashParams) (StorageTrash, error)
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error
	InsertWhatsAppConnectionEvent(ctx context.Context, arg InsertWhatsAppConnectionEventParams) (WhatsappConnectionEvent, error)
	InvalidateActiveOTPs(ctx context.Context, arg InvalidateActiveOTPsParams) error
	InvalidateActivePhoneOTPs(ctx context.Context, arg InvalidateActivePhoneOTPsParams) error
	LatestExchangeRateDate(ctx context.Context, onDate pgtype.Date) (pgtype.Date, error)
	ListActiveDevicePushTokens(ctx context.Context, userID int64) ([]DevicePushToken, error)
	ListActiveMobileSessionUUIDsForDevice(ctx context.Context, arg ListActiveMobileSessionUUIDsForDeviceParams) ([]uuid.UUID, error)
	ListActivePublicKeys(ctx context.Context, keys []string) ([]string, error)
	ListActivePublicLinks(ctx context.Context) ([]StorageLink, error)
	ListActiveRefreshTokenUUIDsByFamily(ctx context.Context, familyID pgtype.UUID) ([]uuid.UUID, error)
	ListActiveRefreshTokensByUserID(ctx context.Context, userID int64) ([]RefreshToken, error)
	// Candidates for one event x channel; the usecase picks role/language/brand.
	ListActiveTemplatesForEvent(ctx context.Context, arg ListActiveTemplatesForEventParams) ([]NotificationTemplate, error)
	ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error)
	ListAllBulkJobs(ctx context.Context, arg ListAllBulkJobsParams) ([]BulkJob, error)
	ListAllExportJobs(ctx context.Context, arg ListAllExportJobsParams) ([]ExportJob, error)
	ListAllImportJobs(ctx context.Context, arg ListAllImportJobsParams) ([]ImportJob, error)
	ListAllPermissionSlugs(ctx context.Context) ([]string, error)
	ListAllPermissions(ctx context.Context) ([]Permission, error)
	ListAllRoles(ctx context.Context) ([]Role, error)
	ListAppLogSources(ctx context.Context) ([]string, error)
	ListAppLogs(ctx context.Context, arg ListAppLogsParams) ([]AppLog, error)
	ListBrandDomains(ctx context.Context) ([]ListBrandDomainsRow, error)
	ListBrands(ctx context.Context) ([]Brand, error)
	ListBulkChangesForJob(ctx context.Context, jobID int64) ([]BulkChange, error)
	ListBulkJobsForActor(ctx context.Context, arg ListBulkJobsForActorParams) ([]BulkJob, error)
	// TEC-84: countries > provinces > districts, territories, plate formats.
	ListCountries(ctx context.Context, activeOnly bool) ([]ListCountriesRow, error)
	// TEC-84: currencies and daily exchange rates. Rates travel as text so no
	// precision is lost between NUMERIC and Go.
	ListCurrencies(ctx context.Context, activeOnly bool) ([]Currency, error)
	ListDistributorPriceOverrides(ctx context.Context, arg ListDistributorPriceOverridesParams) ([]ListDistributorPriceOverridesRow, error)
	ListDistrictsByProvince(ctx context.Context, provinceID int64) ([]District, error)
	ListDocumentTemplateVersions(ctx context.Context, arg ListDocumentTemplateVersionsParams) ([]DocumentTemplate, error)
	ListDocumentTemplates(ctx context.Context, arg ListDocumentTemplatesParams) ([]ListDocumentTemplatesRow, error)
	ListEnabledLogPurgeRules(ctx context.Context) ([]LogPurgeRule, error)
	ListExchangeRatesByDate(ctx context.Context, arg ListExchangeRatesByDateParams) ([]ListExchangeRatesByDateRow, error)
	ListExportJobsForActor(ctx context.Context, arg ListExportJobsForActorParams) ([]ExportJob, error)
	ListExportJobsForOrganization(ctx context.Context, arg ListExportJobsForOrganizationParams) ([]ExportJob, error)
	// Grants of global roles (user_roles / JWT roles claim).
	ListGrantsByRoleSlugs(ctx context.Context, roleSlugs []string) ([]ListGrantsByRoleSlugsRow, error)
	ListImportChangesForJob(ctx context.Context, jobID int64) ([]ImportChange, error)
	ListImportJobsForActor(ctx context.Context, arg ListImportJobsForActorParams) ([]ImportJob, error)
	ListImportJobsForOrganization(ctx context.Context, arg ListImportJobsForOrganizationParams) ([]ImportJob, error)
	ListLatestKVKKNotices(ctx context.Context) ([]KvkkNotice, error)
	ListLatestLegalTexts(ctx context.Context, kind string) ([]LegalText, error)
	ListLegalTextVersions(ctx context.Context, arg ListLegalTextVersionsParams) ([]LegalText, error)
	ListLogPurgeRules(ctx context.Context) ([]LogPurgeRule, error)
	// Grants of the user's roles in one organization (active org context).
	ListMemberGrants(ctx context.Context, arg ListMemberGrantsParams) ([]ListMemberGrantsRow, error)
	ListMemberRoleSlugs(ctx context.Context, arg ListMemberRoleSlugsParams) ([]string, error)
	ListMemberRolesByOrganization(ctx context.Context, organizationID int64) ([]ListMemberRolesByOrganizationRow, error)
	// System rows plus the org / dealer_standard rows of the given organizations.
	ListModuleFlagsForOrgs(ctx context.Context, orgIds []int64) ([]ListModuleFlagsForOrgsRow, error)
	ListModules(ctx context.Context) ([]Module, error)
	ListNotificationChannelSettings(ctx context.Context) ([]NotificationChannelSetting, error)
	ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]ListNotificationDeliveriesRow, error)
	ListNotificationPreferenceRows(ctx context.Context, userID int64) ([]NotificationPreference, error)
	ListNotificationTemplates(ctx context.Context, arg ListNotificationTemplatesParams) ([]NotificationTemplate, error)
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error)
	ListOAuthAccountsByUserID(ctx context.Context, userID int64) ([]ListOAuthAccountsByUserIDRow, error)
	ListOAuthAccountsForUserIDs(ctx context.Context, userIds []int64) ([]ListOAuthAccountsForUserIDsRow, error)
	ListOAuthProviderSettings(ctx context.Context) ([]OauthProviderSetting, error)
	ListOrganizationChildren(ctx context.Context, parentID pgtype.Int8) ([]ListOrganizationChildrenRow, error)
	ListOrganizationMemberOptions(ctx context.Context, organizationID int64) ([]ListOrganizationMemberOptionsRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID int64) ([]ListOrganizationMembersRow, error)
	ListOrganizationMembersByUserID(ctx context.Context, arg ListOrganizationMembersByUserIDParams) ([]ListOrganizationMembersByUserIDRow, error)
	ListOrganizationOwnerUserIDs(ctx context.Context, organizationID int64) ([]int64, error)
	ListOrganizationsFiltered(ctx context.Context, arg ListOrganizationsFilteredParams) ([]ListOrganizationsFilteredRow, error)
	// Organizations reachable by a scope filter: an explicit id set
	// (managed/subtree) or a whole brand (brand), or every brand (all, both NULL).
	ListOrganizationsInScope(ctx context.Context, arg ListOrganizationsInScopeParams) ([]ListOrganizationsInScopeRow, error)
	// Territories of the brand that overlap an area: the same area, an ancestor
	// (the country or the province of a district) or a descendant.
	ListOverlappingTerritories(ctx context.Context, arg ListOverlappingTerritoriesParams) ([]ListOverlappingTerritoriesRow, error)
	ListPermissionSlugsByRoleID(ctx context.Context, roleID int64) ([]string, error)
	ListPermissionSlugsByRoleSlug(ctx context.Context, slug string) ([]string, error)
	ListPermissionsFiltered(ctx context.Context, arg ListPermissionsFilteredParams) ([]Permission, error)
	ListPlateFormats(ctx context.Context, activeOnly bool) ([]ListPlateFormatsRow, error)
	ListPlatformNotifications(ctx context.Context, arg ListPlatformNotificationsParams) ([]Notification, error)
	ListPlatformNotificationsForExport(ctx context.Context, arg ListPlatformNotificationsForExportParams) ([]Notification, error)
	ListProductCategories(ctx context.Context, arg ListProductCategoriesParams) ([]ProductCategory, error)
	ListProductPrices(ctx context.Context, arg ListProductPricesParams) ([]ListProductPricesRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	// Search indexer only (full reindex across brands).
	ListProductsForIndex(ctx context.Context) ([]Product, error)
	ListProvincesByCountry(ctx context.Context, countryID int64) ([]ListProvincesByCountryRow, error)
	ListPushSubscriptionsByUser(ctx context.Context, userID int64) ([]PushSubscription, error)
	ListRoleGrantsByRoleID(ctx context.Context, roleID int64) ([]ListRoleGrantsByRoleIDRow, error)
	ListRoleGrantsByRoleUUID(ctx context.Context, argUuid uuid.UUID) ([]ListRoleGrantsByRoleUUIDRow, error)
	ListRolePermissionSlugsByRoleUUID(ctx context.Context, argUuid uuid.UUID) ([]string, error)
	ListRoleUUIDsForBulk(ctx context.Context, q_ pgtype.Text) ([]uuid.UUID, error)
	ListRolesFiltered(ctx context.Context, arg ListRolesFilteredParams) ([]Role, error)
	ListRolesForExport(ctx context.Context, q_ pgtype.Text) ([]Role, error)
	ListRolesForUserIDs(ctx context.Context, userIds []int64) ([]ListRolesForUserIDsRow, error)
	ListSharedKeys(ctx context.Context, keys []string) ([]string, error)
	ListStorageActivity(ctx context.Context, arg ListStorageActivityParams) ([]ListStorageActivityRow, error)
	ListStorageLinksByKey(ctx context.Context, objectKey string) ([]StorageLink, error)
	ListStorageSharesByKey(ctx context.Context, objectKey string) ([]ListStorageSharesByKeyRow, error)
	ListStorageSharesForUser(ctx context.Context, userID int64) ([]StorageShare, error)
	ListStorageStarsByKeys(ctx context.Context, arg ListStorageStarsByKeysParams) ([]StorageStar, error)
	ListStorageStarsByUser(ctx context.Context, userID int64) ([]StorageStar, error)
	ListStorageTrash(ctx context.Context, arg ListStorageTrashParams) ([]StorageTrash, error)
	ListStuckProcessingNotificationIDs(ctx context.Context, staleMinutes int32) ([]int64, error)
	ListTerritories(ctx context.Context, arg ListTerritoriesParams) ([]ListTerritoriesRow, error)
	ListUserIDsByRoleSlug(ctx context.Context, slug string) ([]int64, error)
	ListUserRoleSlugs(ctx context.Context, userID int64) ([]string, error)
	ListUserRolesByUserID(ctx context.Context, userID int64) ([]Role, error)
	ListUserRolesByUserUUID(ctx context.Context, argUuid uuid.UUID) ([]Role, error)
	ListUserUUIDsForBulk(ctx context.Context, arg ListUserUUIDsForBulkParams) ([]uuid.UUID, error)
	ListUsersFiltered(ctx context.Context, arg ListUsersFilteredParams) ([]User, error)
	ListUsersForExport(ctx context.Context, arg ListUsersForExportParams) ([]User, error)
	ListWebAuthnCredentialsByUserID(ctx context.Context, userID int64) ([]WebauthnCredential, error)
	ListWebAuthnCredentialsForUserIDs(ctx context.Context, userIds []int64) ([]WebauthnCredential, error)
	ListWhatsAppAlarmRecipients(ctx context.Context) ([]ListWhatsAppAlarmRecipientsRow, error)
	ListWhatsAppConnectionEvents(ctx context.Context, limit int32) ([]WhatsappConnectionEvent, error)
	// Phone OTP (TEC-92). Timestamps are passed in so tests can drive the clock.
	LockOTPSubject(ctx context.Context, subject string) error
	// Serializes territory writes of one (brand, country) inside a transaction.
	LockTerritoryArea(ctx context.Context, arg LockTerritoryAreaParams) error
	MarkAllNotificationsReadForUser(ctx context.Context, userID pgtype.Int8) (int64, error)
	MarkBulkJobCompleted(ctx context.Context, arg MarkBulkJobCompletedParams) (BulkJob, error)
	MarkBulkJobFailed(ctx context.Context, arg MarkBulkJobFailedParams) (BulkJob, error)
	MarkBulkJobProcessing(ctx context.Context, id int64) (BulkJob, error)
	MarkBulkJobRolledBack(ctx context.Context, arg MarkBulkJobRolledBackParams) (BulkJob, error)
	MarkDeliveryProcessing(ctx context.Context, id int64) error
	MarkDeliveryResult(ctx context.Context, arg MarkDeliveryResultParams) error
	MarkDocumentRenderFailed(ctx context.Context, arg MarkDocumentRenderFailedParams) error
	MarkDocumentRenderProcessing(ctx context.Context, id int64) (DocumentRender, error)
	MarkDocumentRenderReady(ctx context.Context, arg MarkDocumentRenderReadyParams) (DocumentRender, error)
	MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) (ExportJob, error)
	MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) (ExportJob, error)
	MarkExportJobProcessing(ctx context.Context, id int64) (ExportJob, error)
	MarkImportJobApplied(ctx context.Context, arg MarkImportJobAppliedParams) (ImportJob, error)
	MarkImportJobApplying(ctx context.Context, id int64) (ImportJob, error)
	MarkImportJobFailed(ctx context.Context, arg MarkImportJobFailedParams) (ImportJob, error)
	MarkImportJobRolledBack(ctx context.Context, id int64) (ImportJob, error)
	MarkLogPurgeRuleRun(ctx context.Context, arg MarkLogPurgeRuleRunParams) (LogPurgeRule, error)
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) (Notification, error)
	MarkNotificationProcessing(ctx context.Context, id int64) (Notification, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	// Cast status on every use. Reusing an untyped param as both VARCHAR assignment
	// and IN ('delivered', 'read') makes Postgres raise 42P08
	// (inconsistent types deduced for parameter $2).
	MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) (Notification, error)
	MarkOTPDelivered(ctx context.Context, arg MarkOTPDeliveredParams) error
	MarkOTPDeliveryFailed(ctx context.Context, arg MarkOTPDeliveryFailedParams) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, id int64) error
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	MarkQRLoginChallengeScanned(ctx context.Context, code string) (QrLoginChallenge, error)
	MarkUserPhoneVerified(ctx context.Context, id int64) error
	NextDocumentTemplateVersion(ctx context.Context, arg NextDocumentTemplateVersionParams) (int32, error)
	PingDB(ctx context.Context) (int32, error)
	PublishDocumentTemplate(ctx context.Context, id int64) (DocumentTemplate, error)
	PurgeNotificationDeliveriesBefore(ctx context.Context, arg PurgeNotificationDeliveriesBeforeParams) (int64, error)
	PurgeNotificationsBefore(ctx context.Context, arg PurgeNotificationsBeforeParams) (int64, error)
	QueueImportJob(ctx context.Context, argUuid uuid.UUID) (ImportJob, error)
	RemoveUserRoleBySlug(ctx context.Context, arg RemoveUserRoleBySlugParams) error
	ReplaceUserRoles(ctx context.Context, userID int64) error
	// The most specific territory covering an address (district > province >
	// country) whose distributor is live.
	ResolveTerritory(ctx context.Context, arg ResolveTerritoryParams) (ResolveTerritoryRow, error)
	// A failed render is re-queued with a new attempt number (new task id).
	RetryDocumentRender(ctx context.Context, id int64) (DocumentRender, error)
	RevokeAllDevicePushTokensForUser(ctx context.Context, userID int64) (int64, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error
	RevokeDevicePushToken(ctx context.Context, arg RevokeDevicePushTokenParams) (int64, error)
	// TEC-91: mobile sign-out drops the device's Expo tokens.
	RevokeDevicePushTokensForDevice(ctx context.Context, arg RevokeDevicePushTokensForDeviceParams) (int64, error)
	RevokeMobileSessionsForDevice(ctx context.Context, arg RevokeMobileSessionsForDeviceParams) (int64, error)
	RevokeOtherRefreshTokensForUser(ctx context.Context, arg RevokeOtherRefreshTokensForUserParams) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error)
	RevokeRefreshTokenByUUIDForUser(ctx context.Context, arg RevokeRefreshTokenByUUIDForUserParams) (int64, error)
	RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) (int64, error)
	RevokeStorageLink(ctx context.Context, argUuid uuid.UUID) (StorageLink, error)
	// TEC-91: mobile refresh chains (rotation, reuse detection, device sign-out).
	RotateRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error)
	SetAppSettingsLogo(ctx context.Context, logoObjectKey pgtype.Text) (AppSetting, error)
	SetCountryActive(ctx context.Context, arg SetCountryActiveParams) (Country, error)
	SetNotificationChannelEnabled(ctx context.Context, arg SetNotificationChannelEnabledParams) (NotificationChannelSetting, error)
	SetOrganizationLogo(ctx context.Context, arg SetOrganizationLogoParams) (Organization, error)
	// Bulk activate/deactivate within one brand.
	SetProductsActive(ctx context.Context, arg SetProductsActiveParams) (int64, error)
	// Bulk activate/deactivate by public id within one brand. Returns the rows
	// that changed so the caller can reindex them.
	SetProductsActiveByUUIDs(ctx context.Context, arg SetProductsActiveByUUIDsParams) ([]uuid.UUID, error)
	SetRolePermissions(ctx context.Context, roleID int64) error
	SetUserEmailVerified(ctx context.Context, id int64) (User, error)
	SetWhatsAppInstance(ctx context.Context, arg SetWhatsAppInstanceParams) (WhatsappSetting, error)
	SetWhatsAppSMSFallback(ctx context.Context, smsFallbackEnabled bool) (WhatsappSetting, error)
	SlugExists(ctx context.Context, slug string) (bool, error)
	// The supplier of an organization is its parent in the tree (K9).
	// Returns no rows for a center.
	SupplierOf(ctx context.Context, id int64) (Organization, error)
	UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) (AppSetting, error)
	UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error)
	UpdateDocumentTemplateDraft(ctx context.Context, arg UpdateDocumentTemplateDraftParams) (DocumentTemplate, error)
	UpdateGitHubAppSettings(ctx context.Context, arg UpdateGitHubAppSettingsParams) (GithubAppSetting, error)
	UpdateImportJobFileKey(ctx context.Context, arg UpdateImportJobFileKeyParams) (ImportJob, error)
	UpdateImportJobMapping(ctx context.Context, arg UpdateImportJobMappingParams) (ImportJob, error)
	UpdateImportJobPreview(ctx context.Context, arg UpdateImportJobPreviewParams) (ImportJob, error)
	UpdateLogPurgeRule(ctx context.Context, arg UpdateLogPurgeRuleParams) (LogPurgeRule, error)
	UpdateMessageStatusByExternalIDs(ctx context.Context, arg UpdateMessageStatusByExternalIDsParams) (int64, error)
	UpdateModuleDefaults(ctx context.Context, arg UpdateModuleDefaultsParams) (Module, error)
	UpdateOAuthProviderSettings(ctx context.Context, arg UpdateOAuthProviderSettingsParams) (OauthProviderSetting, error)
	UpdateOrganizationLetterhead(ctx context.Context, arg UpdateOrganizationLetterheadParams) (Organization, error)
	UpdateOrganizationParent(ctx context.Context, arg UpdateOrganizationParentParams) (Organization, error)
	UpdateOrganizationPlatform(ctx context.Context, arg UpdateOrganizationPlatformParams) (Organization, error)
	UpdatePlateFormat(ctx context.Context, arg UpdatePlateFormatParams) (PlateFormat, error)
	// Full replacement of the editable fields (read-modify-write in the use case).
	// The F2 sync columns are not touched here.
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Full replacement of the editable fields (read-modify-write in the use case).
	UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateStepupSettings(ctx context.Context, arg UpdateStepupSettingsParams) (StepupSetting, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) error
	UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error
	UpdateUserPlatform(ctx context.Context, arg UpdateUserPlatformParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserProfileBasics(ctx context.Context, arg UpdateUserProfileBasicsParams) error
	UpdateUserProfileByUUID(ctx context.Context, arg UpdateUserProfileByUUIDParams) (User, error)
	UpdateUserTOTPRecoveryHashes(ctx context.Context, arg UpdateUserTOTPRecoveryHashesParams) error
	UpdateWebAuthnCredentialCounter(ctx context.Context, arg UpdateWebAuthnCredentialCounterParams) error
	UpdateWebAuthnCredentialName(ctx context.Context, arg UpdateWebAuthnCredentialNameParams) (WebauthnCredential, error)
	UpdateWhatsAppStatus(ctx context.Context, arg UpdateWhatsAppStatusParams) (WhatsappSetting, error)
	UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error)
	UpsertDevicePushToken(ctx context.Context, arg UpsertDevicePushTokenParams) (DevicePushToken, error)
	// The database refuses a target that is not a distributor of the brand.
	UpsertDistributorPriceOverride(ctx context.Context, arg UpsertDistributorPriceOverrideParams) (UpsertDistributorPriceOverrideRow, error)
	// One row per cache key: a repeated request returns the existing row.
	UpsertDocumentRender(ctx context.Context, arg UpsertDocumentRenderParams) (DocumentRender, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
	// Catalog sync: level and sort order follow the Go catalog; admin-edited
	// default_enabled / is_paid survive (a core module is always on).
	UpsertModuleCatalog(ctx context.Context, arg UpsertModuleCatalogParams) error
	UpsertNotificationEvent(ctx context.Context, arg UpsertNotificationEventParams) error
	UpsertNotificationPreferenceRow(ctx context.Context, arg UpsertNotificationPreferenceRowParams) (NotificationPreference, error)
	UpsertNotificationTemplate(ctx context.Context, arg UpsertNotificationTemplateParams) (NotificationTemplate, error)
	UpsertOrgModuleFlag(ctx context.Context, arg UpsertOrgModuleFlagParams) (ModuleFlag, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error
	// TEC-144: product price list and distributor-specific prices (K8). Prices
	// travel as text so no precision is lost between NUMERIC and Go. Field
	// masking by pricing.* permission happens in the use case layer.
	UpsertProductPrice(ctx context.Context, arg UpsertProductPriceParams) (UpsertProductPriceRow, error)
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error)
	UpsertSystemModuleFlag(ctx context.Context, arg UpsertSystemModuleFlagParams) (ModuleFlag, error)
	UpsertSystemRole(ctx context.Context, arg UpsertSystemRoleParams) (Role, error)
	UpsertUserTOTPSetup(ctx context.Context, arg UpsertUserTOTPSetupParams) (UserTotp, error)
	UserHasRoleSlug(ctx context.Context, arg UserHasRoleSlugParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
