// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceCatalogModule = `-- name: AddServiceCatalogModule :exec
INSERT INTO service_catalog_modules (item_id, module_key)
VALUES ($1, $2)
ON CONFLICT (item_id, module_key) DO NOTHING
`

type AddServiceCatalogModuleParams struct {
	ItemID    int64  `json:"item_id"`
	ModuleKey string `json:"module_key"`
}

func (q *Queries) AddServiceCatalogModule(ctx context.Context, arg AddServiceCatalogModuleParams) error {
	_, err := q.db.Exec(ctx, addServiceCatalogModule, arg.ItemID, arg.ModuleKey)
	return err
}

const countActiveServiceModuleSubscriptions = `-- name: CountActiveServiceModuleSubscriptions :one
SELECT count(*)
FROM service_subscriptions s
JOIN service_catalog_modules m ON m.item_id = s.item_id
WHERE s.organization_id = $1
  AND s.brand_id = $2
  AND m.module_key = $3
  AND s.status IN ('active', 'cancel_requested')
`

type CountActiveServiceModuleSubscriptionsParams struct {
	OrganizationID int64  `json:"organization_id"`
	BrandID        int64  `json:"brand_id"`
	ModuleKey      string `json:"module_key"`
}

func (q *Queries) CountActiveServiceModuleSubscriptions(ctx context.Context, arg CountActiveServiceModuleSubscriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveServiceModuleSubscriptions, arg.OrganizationID, arg.BrandID, arg.ModuleKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServiceSubscriptionsByItem = `-- name: CountServiceSubscriptionsByItem :one
SELECT count(*) FROM service_subscriptions
WHERE item_id = $1 AND brand_id = $2
`

type CountServiceSubscriptionsByItemParams struct {
	ItemID  int64 `json:"item_id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) CountServiceSubscriptionsByItem(ctx context.Context, arg CountServiceSubscriptionsByItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceSubscriptionsByItem, arg.ItemID, arg.BrandID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceCatalogItem = `-- name: CreateServiceCatalogItem :one

INSERT INTO service_catalog_items (
    organization_id, brand_id, name, description, category, default_price, currency,
    recurrence, cancellation_fee, contract_template_id, is_active
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, uuid, organization_id, brand_id, name, description, category, default_price, currency, recurrence, cancellation_fee, contract_template_id, is_active, created_at, updated_at
`

type CreateServiceCatalogItemParams struct {
	OrganizationID     int64          `json:"organization_id"`
	BrandID            int64          `json:"brand_id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	Category           string         `json:"category"`
	DefaultPrice       pgtype.Numeric `json:"default_price"`
	Currency           string         `json:"currency"`
	Recurrence         string         `json:"recurrence"`
	CancellationFee    pgtype.Numeric `json:"cancellation_fee"`
	ContractTemplateID pgtype.Int8    `json:"contract_template_id"`
	IsActive           bool           `json:"is_active"`
}

// TEC-305 (F3-08a): non-product service catalog, distributor price
// overrides, subscriptions, accounted periods and cancellation requests.
// Every read is bounded by the brand of the active organization.
func (q *Queries) CreateServiceCatalogItem(ctx context.Context, arg CreateServiceCatalogItemParams) (ServiceCatalogItem, error) {
	row := q.db.QueryRow(ctx, createServiceCatalogItem,
		arg.OrganizationID,
		arg.BrandID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.DefaultPrice,
		arg.Currency,
		arg.Recurrence,
		arg.CancellationFee,
		arg.ContractTemplateID,
		arg.IsActive,
	)
	var i ServiceCatalogItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultPrice,
		&i.Currency,
		&i.Recurrence,
		&i.CancellationFee,
		&i.ContractTemplateID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceSubscription = `-- name: CreateServiceSubscription :one
INSERT INTO service_subscriptions (
    organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id,
    starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, contract_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14
)
RETURNING id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at
`

type CreateServiceSubscriptionParams struct {
	OrganizationID   int64          `json:"organization_id"`
	BrandID          int64          `json:"brand_id"`
	SellerOrgID      int64          `json:"seller_org_id"`
	ItemID           int64          `json:"item_id"`
	AssignedByOrgID  int64          `json:"assigned_by_org_id"`
	AssignedByUserID pgtype.Int8    `json:"assigned_by_user_id"`
	StartsOn         pgtype.Date    `json:"starts_on"`
	EndsOn           pgtype.Date    `json:"ends_on"`
	Recurrence       string         `json:"recurrence"`
	Price            pgtype.Numeric `json:"price"`
	Currency         string         `json:"currency"`
	RateSnapshot     []byte         `json:"rate_snapshot"`
	CancellationFee  pgtype.Numeric `json:"cancellation_fee"`
	ContractID       pgtype.Int8    `json:"contract_id"`
}

func (q *Queries) CreateServiceSubscription(ctx context.Context, arg CreateServiceSubscriptionParams) (ServiceSubscription, error) {
	row := q.db.QueryRow(ctx, createServiceSubscription,
		arg.OrganizationID,
		arg.BrandID,
		arg.SellerOrgID,
		arg.ItemID,
		arg.AssignedByOrgID,
		arg.AssignedByUserID,
		arg.StartsOn,
		arg.EndsOn,
		arg.Recurrence,
		arg.Price,
		arg.Currency,
		arg.RateSnapshot,
		arg.CancellationFee,
		arg.ContractID,
	)
	var i ServiceSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.ItemID,
		&i.AssignedByOrgID,
		&i.AssignedByUserID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Recurrence,
		&i.Price,
		&i.Currency,
		&i.RateSnapshot,
		&i.CancellationFee,
		&i.Status,
		&i.ContractID,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceSubscriptionCancelRequest = `-- name: CreateServiceSubscriptionCancelRequest :one
INSERT INTO service_subscription_cancel_requests (
    subscription_id, organization_id, brand_id, requested_by_user_id, requested_by_org_id,
    reason, cancellation_fee, currency
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING id, uuid, subscription_id, organization_id, brand_id, requested_by_user_id, requested_by_org_id, reason, status, cancellation_fee, currency, decided_by_user_id, decided_at, decision_note, created_at, updated_at
`

type CreateServiceSubscriptionCancelRequestParams struct {
	SubscriptionID    int64          `json:"subscription_id"`
	OrganizationID    int64          `json:"organization_id"`
	BrandID           int64          `json:"brand_id"`
	RequestedByUserID pgtype.Int8    `json:"requested_by_user_id"`
	RequestedByOrgID  int64          `json:"requested_by_org_id"`
	Reason            string         `json:"reason"`
	CancellationFee   pgtype.Numeric `json:"cancellation_fee"`
	Currency          string         `json:"currency"`
}

func (q *Queries) CreateServiceSubscriptionCancelRequest(ctx context.Context, arg CreateServiceSubscriptionCancelRequestParams) (ServiceSubscriptionCancelRequest, error) {
	row := q.db.QueryRow(ctx, createServiceSubscriptionCancelRequest,
		arg.SubscriptionID,
		arg.OrganizationID,
		arg.BrandID,
		arg.RequestedByUserID,
		arg.RequestedByOrgID,
		arg.Reason,
		arg.CancellationFee,
		arg.Currency,
	)
	var i ServiceSubscriptionCancelRequest
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.BrandID,
		&i.RequestedByUserID,
		&i.RequestedByOrgID,
		&i.Reason,
		&i.Status,
		&i.CancellationFee,
		&i.Currency,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decideServiceSubscriptionCancelRequest = `-- name: DecideServiceSubscriptionCancelRequest :one
UPDATE service_subscription_cancel_requests
SET status = $1::text,
    decided_by_user_id = $2,
    decided_at = NOW(),
    decision_note = $3
WHERE id = $4 AND brand_id = $5 AND status = 'pending'
RETURNING id, uuid, subscription_id, organization_id, brand_id, requested_by_user_id, requested_by_org_id, reason, status, cancellation_fee, currency, decided_by_user_id, decided_at, decision_note, created_at, updated_at
`

type DecideServiceSubscriptionCancelRequestParams struct {
	Status          string      `json:"status"`
	DecidedByUserID pgtype.Int8 `json:"decided_by_user_id"`
	DecisionNote    pgtype.Text `json:"decision_note"`
	ID              int64       `json:"id"`
	BrandID         int64       `json:"brand_id"`
}

func (q *Queries) DecideServiceSubscriptionCancelRequest(ctx context.Context, arg DecideServiceSubscriptionCancelRequestParams) (ServiceSubscriptionCancelRequest, error) {
	row := q.db.QueryRow(ctx, decideServiceSubscriptionCancelRequest,
		arg.Status,
		arg.DecidedByUserID,
		arg.DecisionNote,
		arg.ID,
		arg.BrandID,
	)
	var i ServiceSubscriptionCancelRequest
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.BrandID,
		&i.RequestedByUserID,
		&i.RequestedByOrgID,
		&i.Reason,
		&i.Status,
		&i.CancellationFee,
		&i.Currency,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceCatalogModules = `-- name: DeleteServiceCatalogModules :execrows
DELETE FROM service_catalog_modules WHERE item_id = $1
`

func (q *Queries) DeleteServiceCatalogModules(ctx context.Context, itemID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceCatalogModules, itemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServicePriceOverride = `-- name: DeleteServicePriceOverride :execrows
DELETE FROM service_price_overrides
WHERE item_id = $1 AND organization_id = $2
  AND brand_id = $3
`

type DeleteServicePriceOverrideParams struct {
	ItemID         int64 `json:"item_id"`
	OrganizationID int64 `json:"organization_id"`
	BrandID        int64 `json:"brand_id"`
}

func (q *Queries) DeleteServicePriceOverride(ctx context.Context, arg DeleteServicePriceOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServicePriceOverride, arg.ItemID, arg.OrganizationID, arg.BrandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireServiceSubscriptions = `-- name: ExpireServiceSubscriptions :many
UPDATE service_subscriptions
SET status = 'expired', expired_at = NOW()
WHERE status IN ('active', 'cancel_requested') AND ends_on < $1::date
RETURNING id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at
`

func (q *Queries) ExpireServiceSubscriptions(ctx context.Context, today pgtype.Date) ([]ServiceSubscription, error) {
	rows, err := q.db.Query(ctx, expireServiceSubscriptions, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSubscription{}
	for rows.Next() {
		var i ServiceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.SellerOrgID,
			&i.ItemID,
			&i.AssignedByOrgID,
			&i.AssignedByUserID,
			&i.StartsOn,
			&i.EndsOn,
			&i.Recurrence,
			&i.Price,
			&i.Currency,
			&i.RateSnapshot,
			&i.CancellationFee,
			&i.Status,
			&i.ContractID,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceCatalogItem = `-- name: GetServiceCatalogItem :one
SELECT id, uuid, organization_id, brand_id, name, description, category, default_price, currency, recurrence, cancellation_fee, contract_template_id, is_active, created_at, updated_at FROM service_catalog_items
WHERE id = $1 AND brand_id = $2
`

type GetServiceCatalogItemParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) GetServiceCatalogItem(ctx context.Context, arg GetServiceCatalogItemParams) (ServiceCatalogItem, error) {
	row := q.db.QueryRow(ctx, getServiceCatalogItem, arg.ID, arg.BrandID)
	var i ServiceCatalogItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultPrice,
		&i.Currency,
		&i.Recurrence,
		&i.CancellationFee,
		&i.ContractTemplateID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceCatalogItemByUUID = `-- name: GetServiceCatalogItemByUUID :one
SELECT id, uuid, organization_id, brand_id, name, description, category, default_price, currency, recurrence, cancellation_fee, contract_template_id, is_active, created_at, updated_at FROM service_catalog_items
WHERE uuid = $1 AND brand_id = $2
`

type GetServiceCatalogItemByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetServiceCatalogItemByUUID(ctx context.Context, arg GetServiceCatalogItemByUUIDParams) (ServiceCatalogItem, error) {
	row := q.db.QueryRow(ctx, getServiceCatalogItemByUUID, arg.Uuid, arg.BrandID)
	var i ServiceCatalogItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultPrice,
		&i.Currency,
		&i.Recurrence,
		&i.CancellationFee,
		&i.ContractTemplateID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServicePriceOverride = `-- name: GetServicePriceOverride :one
SELECT id, item_id, organization_id, brand_id, price, currency, created_at, updated_at FROM service_price_overrides
WHERE item_id = $1 AND organization_id = $2
`

type GetServicePriceOverrideParams struct {
	ItemID         int64 `json:"item_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetServicePriceOverride(ctx context.Context, arg GetServicePriceOverrideParams) (ServicePriceOverride, error) {
	row := q.db.QueryRow(ctx, getServicePriceOverride, arg.ItemID, arg.OrganizationID)
	var i ServicePriceOverride
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OrganizationID,
		&i.BrandID,
		&i.Price,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceSubscriptionByUUID = `-- name: GetServiceSubscriptionByUUID :one
SELECT id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at FROM service_subscriptions
WHERE uuid = $1 AND brand_id = $2
`

type GetServiceSubscriptionByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetServiceSubscriptionByUUID(ctx context.Context, arg GetServiceSubscriptionByUUIDParams) (ServiceSubscription, error) {
	row := q.db.QueryRow(ctx, getServiceSubscriptionByUUID, arg.Uuid, arg.BrandID)
	var i ServiceSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.ItemID,
		&i.AssignedByOrgID,
		&i.AssignedByUserID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Recurrence,
		&i.Price,
		&i.Currency,
		&i.RateSnapshot,
		&i.CancellationFee,
		&i.Status,
		&i.ContractID,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceSubscriptionCancelRequestByUUID = `-- name: GetServiceSubscriptionCancelRequestByUUID :one
SELECT id, uuid, subscription_id, organization_id, brand_id, requested_by_user_id, requested_by_org_id, reason, status, cancellation_fee, currency, decided_by_user_id, decided_at, decision_note, created_at, updated_at FROM service_subscription_cancel_requests
WHERE uuid = $1 AND brand_id = $2
`

type GetServiceSubscriptionCancelRequestByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetServiceSubscriptionCancelRequestByUUID(ctx context.Context, arg GetServiceSubscriptionCancelRequestByUUIDParams) (ServiceSubscriptionCancelRequest, error) {
	row := q.db.QueryRow(ctx, getServiceSubscriptionCancelRequestByUUID, arg.Uuid, arg.BrandID)
	var i ServiceSubscriptionCancelRequest
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.BrandID,
		&i.RequestedByUserID,
		&i.RequestedByOrgID,
		&i.Reason,
		&i.Status,
		&i.CancellationFee,
		&i.Currency,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertServiceSubscriptionPeriod = `-- name: InsertServiceSubscriptionPeriod :one
INSERT INTO service_subscription_periods (subscription_id, organization_id, brand_id, period_start, period_end)
VALUES ($1, $2, $3,
        $4, $5)
ON CONFLICT (subscription_id, period_start) DO NOTHING
RETURNING id, subscription_id, organization_id, brand_id, period_start, period_end, posted_at, created_at
`

type InsertServiceSubscriptionPeriodParams struct {
	SubscriptionID int64       `json:"subscription_id"`
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	PeriodStart    pgtype.Date `json:"period_start"`
	PeriodEnd      pgtype.Date `json:"period_end"`
}

// Idempotent: a period already written returns no row.
func (q *Queries) InsertServiceSubscriptionPeriod(ctx context.Context, arg InsertServiceSubscriptionPeriodParams) (ServiceSubscriptionPeriod, error) {
	row := q.db.QueryRow(ctx, insertServiceSubscriptionPeriod,
		arg.SubscriptionID,
		arg.OrganizationID,
		arg.BrandID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i ServiceSubscriptionPeriod
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.BrandID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listServiceCatalogItems = `-- name: ListServiceCatalogItems :many
SELECT id, uuid, organization_id, brand_id, name, description, category, default_price, currency, recurrence, cancellation_fee, contract_template_id, is_active, created_at, updated_at FROM service_catalog_items
WHERE brand_id = $1
  AND ($2::text IS NULL OR category = $2::text)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
ORDER BY name, id
`

type ListServiceCatalogItemsParams struct {
	BrandID  int64       `json:"brand_id"`
	Category pgtype.Text `json:"category"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) ListServiceCatalogItems(ctx context.Context, arg ListServiceCatalogItemsParams) ([]ServiceCatalogItem, error) {
	rows, err := q.db.Query(ctx, listServiceCatalogItems, arg.BrandID, arg.Category, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCatalogItem{}
	for rows.Next() {
		var i ServiceCatalogItem
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.DefaultPrice,
			&i.Currency,
			&i.Recurrence,
			&i.CancellationFee,
			&i.ContractTemplateID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceCatalogModules = `-- name: ListServiceCatalogModules :many
SELECT module_key FROM service_catalog_modules
WHERE item_id = $1
ORDER BY module_key
`

func (q *Queries) ListServiceCatalogModules(ctx context.Context, itemID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listServiceCatalogModules, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var module_key string
		if err := rows.Scan(&module_key); err != nil {
			return nil, err
		}
		items = append(items, module_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePriceOverrides = `-- name: ListServicePriceOverrides :many
SELECT id, item_id, organization_id, brand_id, price, currency, created_at, updated_at FROM service_price_overrides
WHERE item_id = $1 AND brand_id = $2
ORDER BY organization_id
`

type ListServicePriceOverridesParams struct {
	ItemID  int64 `json:"item_id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) ListServicePriceOverrides(ctx context.Context, arg ListServicePriceOverridesParams) ([]ServicePriceOverride, error) {
	rows, err := q.db.Query(ctx, listServicePriceOverrides, arg.ItemID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePriceOverride{}
	for rows.Next() {
		var i ServicePriceOverride
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.OrganizationID,
			&i.BrandID,
			&i.Price,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePriceOverridesForItems = `-- name: ListServicePriceOverridesForItems :many
SELECT id, item_id, organization_id, brand_id, price, currency, created_at, updated_at FROM service_price_overrides
WHERE item_id = ANY($1::bigint[])
  AND organization_id = $2
  AND brand_id = $3
ORDER BY item_id
`

type ListServicePriceOverridesForItemsParams struct {
	ItemIds        []int64 `json:"item_ids"`
	OrganizationID int64   `json:"organization_id"`
	BrandID        int64   `json:"brand_id"`
}

func (q *Queries) ListServicePriceOverridesForItems(ctx context.Context, arg ListServicePriceOverridesForItemsParams) ([]ServicePriceOverride, error) {
	rows, err := q.db.Query(ctx, listServicePriceOverridesForItems, arg.ItemIds, arg.OrganizationID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePriceOverride{}
	for rows.Next() {
		var i ServicePriceOverride
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.OrganizationID,
			&i.BrandID,
			&i.Price,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSubscriptionCancelRequests = `-- name: ListServiceSubscriptionCancelRequests :many
SELECT id, uuid, subscription_id, organization_id, brand_id, requested_by_user_id, requested_by_org_id, reason, status, cancellation_fee, currency, decided_by_user_id, decided_at, decision_note, created_at, updated_at FROM service_subscription_cancel_requests
WHERE brand_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
`

type ListServiceSubscriptionCancelRequestsParams struct {
	BrandID int64       `json:"brand_id"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) ListServiceSubscriptionCancelRequests(ctx context.Context, arg ListServiceSubscriptionCancelRequestsParams) ([]ServiceSubscriptionCancelRequest, error) {
	rows, err := q.db.Query(ctx, listServiceSubscriptionCancelRequests, arg.BrandID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSubscriptionCancelRequest{}
	for rows.Next() {
		var i ServiceSubscriptionCancelRequest
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SubscriptionID,
			&i.OrganizationID,
			&i.BrandID,
			&i.RequestedByUserID,
			&i.RequestedByOrgID,
			&i.Reason,
			&i.Status,
			&i.CancellationFee,
			&i.Currency,
			&i.DecidedByUserID,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSubscriptionPeriods = `-- name: ListServiceSubscriptionPeriods :many
SELECT id, subscription_id, organization_id, brand_id, period_start, period_end, posted_at, created_at FROM service_subscription_periods
WHERE subscription_id = $1
ORDER BY period_start
`

func (q *Queries) ListServiceSubscriptionPeriods(ctx context.Context, subscriptionID int64) ([]ServiceSubscriptionPeriod, error) {
	rows, err := q.db.Query(ctx, listServiceSubscriptionPeriods, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSubscriptionPeriod{}
	for rows.Next() {
		var i ServiceSubscriptionPeriod
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.OrganizationID,
			&i.BrandID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSubscriptionsByBrand = `-- name: ListServiceSubscriptionsByBrand :many
SELECT id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at FROM service_subscriptions
WHERE brand_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
`

type ListServiceSubscriptionsByBrandParams struct {
	BrandID int64       `json:"brand_id"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) ListServiceSubscriptionsByBrand(ctx context.Context, arg ListServiceSubscriptionsByBrandParams) ([]ServiceSubscription, error) {
	rows, err := q.db.Query(ctx, listServiceSubscriptionsByBrand, arg.BrandID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSubscription{}
	for rows.Next() {
		var i ServiceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.SellerOrgID,
			&i.ItemID,
			&i.AssignedByOrgID,
			&i.AssignedByUserID,
			&i.StartsOn,
			&i.EndsOn,
			&i.Recurrence,
			&i.Price,
			&i.Currency,
			&i.RateSnapshot,
			&i.CancellationFee,
			&i.Status,
			&i.ContractID,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceSubscriptionsByOrgs = `-- name: ListServiceSubscriptionsByOrgs :many
SELECT id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at FROM service_subscriptions
WHERE brand_id = $1
  AND organization_id = ANY($2::bigint[])
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC, id DESC
`

type ListServiceSubscriptionsByOrgsParams struct {
	BrandID         int64       `json:"brand_id"`
	OrganizationIds []int64     `json:"organization_ids"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) ListServiceSubscriptionsByOrgs(ctx context.Context, arg ListServiceSubscriptionsByOrgsParams) ([]ServiceSubscription, error) {
	rows, err := q.db.Query(ctx, listServiceSubscriptionsByOrgs, arg.BrandID, arg.OrganizationIds, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSubscription{}
	for rows.Next() {
		var i ServiceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.SellerOrgID,
			&i.ItemID,
			&i.AssignedByOrgID,
			&i.AssignedByUserID,
			&i.StartsOn,
			&i.EndsOn,
			&i.Recurrence,
			&i.Price,
			&i.Currency,
			&i.RateSnapshot,
			&i.CancellationFee,
			&i.Status,
			&i.ContractID,
			&i.CancelledAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceSubscription = `-- name: LockServiceSubscription :one
SELECT id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at FROM service_subscriptions
WHERE id = $1 AND brand_id = $2
FOR UPDATE
`

type LockServiceSubscriptionParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) LockServiceSubscription(ctx context.Context, arg LockServiceSubscriptionParams) (ServiceSubscription, error) {
	row := q.db.QueryRow(ctx, lockServiceSubscription, arg.ID, arg.BrandID)
	var i ServiceSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.ItemID,
		&i.AssignedByOrgID,
		&i.AssignedByUserID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Recurrence,
		&i.Price,
		&i.Currency,
		&i.RateSnapshot,
		&i.CancellationFee,
		&i.Status,
		&i.ContractID,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markServiceSubscriptionPeriodPosted = `-- name: MarkServiceSubscriptionPeriodPosted :one
UPDATE service_subscription_periods
SET posted_at = NOW()
WHERE id = $1 AND posted_at IS NULL
RETURNING id, subscription_id, organization_id, brand_id, period_start, period_end, posted_at, created_at
`

func (q *Queries) MarkServiceSubscriptionPeriodPosted(ctx context.Context, id int64) (ServiceSubscriptionPeriod, error) {
	row := q.db.QueryRow(ctx, markServiceSubscriptionPeriodPosted, id)
	var i ServiceSubscriptionPeriod
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.BrandID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setServiceSubscriptionCancelRequested = `-- name: SetServiceSubscriptionCancelRequested :one
UPDATE service_subscriptions
SET status = 'cancel_requested'
WHERE id = $1 AND brand_id = $2 AND status = 'active'
RETURNING id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at
`

type SetServiceSubscriptionCancelRequestedParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) SetServiceSubscriptionCancelRequested(ctx context.Context, arg SetServiceSubscriptionCancelRequestedParams) (ServiceSubscription, error) {
	row := q.db.QueryRow(ctx, setServiceSubscriptionCancelRequested, arg.ID, arg.BrandID)
	var i ServiceSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.ItemID,
		&i.AssignedByOrgID,
		&i.AssignedByUserID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Recurrence,
		&i.Price,
		&i.Currency,
		&i.RateSnapshot,
		&i.CancellationFee,
		&i.Status,
		&i.ContractID,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setServiceSubscriptionStatus = `-- name: SetServiceSubscriptionStatus :one
UPDATE service_subscriptions
SET status = $1::text,
    cancelled_at = CASE WHEN $1::text = 'cancelled' THEN NOW() ELSE cancelled_at END,
    expired_at = CASE WHEN $1::text = 'expired' THEN NOW() ELSE expired_at END
WHERE id = $2 AND brand_id = $3
RETURNING id, uuid, organization_id, brand_id, seller_org_id, item_id, assigned_by_org_id, assigned_by_user_id, starts_on, ends_on, recurrence, price, currency, rate_snapshot, cancellation_fee, status, contract_id, cancelled_at, expired_at, created_at, updated_at
`

type SetServiceSubscriptionStatusParams struct {
	Status  string `json:"status"`
	ID      int64  `json:"id"`
	BrandID int64  `json:"brand_id"`
}

func (q *Queries) SetServiceSubscriptionStatus(ctx context.Context, arg SetServiceSubscriptionStatusParams) (ServiceSubscription, error) {
	row := q.db.QueryRow(ctx, setServiceSubscriptionStatus, arg.Status, arg.ID, arg.BrandID)
	var i ServiceSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SellerOrgID,
		&i.ItemID,
		&i.AssignedByOrgID,
		&i.AssignedByUserID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Recurrence,
		&i.Price,
		&i.Currency,
		&i.RateSnapshot,
		&i.CancellationFee,
		&i.Status,
		&i.ContractID,
		&i.CancelledAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceCatalogItem = `-- name: UpdateServiceCatalogItem :one
UPDATE service_catalog_items
SET name = $1,
    description = $2,
    category = $3,
    default_price = $4,
    currency = $5,
    recurrence = $6,
    cancellation_fee = $7,
    contract_template_id = $8,
    is_active = $9
WHERE id = $10 AND brand_id = $11
RETURNING id, uuid, organization_id, brand_id, name, description, category, default_price, currency, recurrence, cancellation_fee, contract_template_id, is_active, created_at, updated_at
`

type UpdateServiceCatalogItemParams struct {
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	Category           string         `json:"category"`
	DefaultPrice       pgtype.Numeric `json:"default_price"`
	Currency           string         `json:"currency"`
	Recurrence         string         `json:"recurrence"`
	CancellationFee    pgtype.Numeric `json:"cancellation_fee"`
	ContractTemplateID pgtype.Int8    `json:"contract_template_id"`
	IsActive           bool           `json:"is_active"`
	ID                 int64          `json:"id"`
	BrandID            int64          `json:"brand_id"`
}

func (q *Queries) UpdateServiceCatalogItem(ctx context.Context, arg UpdateServiceCatalogItemParams) (ServiceCatalogItem, error) {
	row := q.db.QueryRow(ctx, updateServiceCatalogItem,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.DefaultPrice,
		arg.Currency,
		arg.Recurrence,
		arg.CancellationFee,
		arg.ContractTemplateID,
		arg.IsActive,
		arg.ID,
		arg.BrandID,
	)
	var i ServiceCatalogItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.DefaultPrice,
		&i.Currency,
		&i.Recurrence,
		&i.CancellationFee,
		&i.ContractTemplateID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServicePriceOverride = `-- name: UpsertServicePriceOverride :one
INSERT INTO service_price_overrides (item_id, organization_id, brand_id, price, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (item_id, organization_id) DO UPDATE
SET price = EXCLUDED.price, currency = EXCLUDED.currency
RETURNING id, item_id, organization_id, brand_id, price, currency, created_at, updated_at
`

type UpsertServicePriceOverrideParams struct {
	ItemID         int64          `json:"item_id"`
	OrganizationID int64          `json:"organization_id"`
	BrandID        int64          `json:"brand_id"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
}

func (q *Queries) UpsertServicePriceOverride(ctx context.Context, arg UpsertServicePriceOverrideParams) (ServicePriceOverride, error) {
	row := q.db.QueryRow(ctx, upsertServicePriceOverride,
		arg.ItemID,
		arg.OrganizationID,
		arg.BrandID,
		arg.Price,
		arg.Currency,
	)
	var i ServicePriceOverride
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.OrganizationID,
		&i.BrandID,
		&i.Price,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
