// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_urls.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShortURL = `-- name: CreateShortURL :one

INSERT INTO short_urls (organization_id, brand_id, token, target_path, expires_at, created_by)
VALUES (
    $1::bigint,
    $2::bigint,
    $3::varchar,
    $4::varchar,
    $5::timestamptz,
    $6::bigint
)
ON CONFLICT (token) DO NOTHING
RETURNING id, uuid, token, target_path, expires_at, created_at
`

type CreateShortURLParams struct {
	OrganizationID pgtype.Int8        `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	Token          string             `json:"token"`
	TargetPath     string             `json:"target_path"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
}

type CreateShortURLRow struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Token      string             `json:"token"`
	TargetPath string             `json:"target_path"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// TEC-249 (F2-04d): short URLs behind /s/{token}.
// ON CONFLICT on the token returns no row: the caller draws a new token.
func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (CreateShortURLRow, error) {
	row := q.db.QueryRow(ctx, createShortURL,
		arg.OrganizationID,
		arg.BrandID,
		arg.Token,
		arg.TargetPath,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateShortURLRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Token,
		&i.TargetPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShortURLExpiry = `-- name: GetShortURLExpiry :one
SELECT expires_at
FROM short_urls
WHERE token = $1::varchar
  AND brand_id = $2::bigint
`

type GetShortURLExpiryParams struct {
	Token   string `json:"token"`
	BrandID int64  `json:"brand_id"`
}

// Tells an expired token of the brand apart from an unknown one.
func (q *Queries) GetShortURLExpiry(ctx context.Context, arg GetShortURLExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getShortURLExpiry, arg.Token, arg.BrandID)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getShortURLStats = `-- name: GetShortURLStats :one
SELECT hit_count, last_hit_at
FROM short_urls
WHERE token = $1::varchar
`

type GetShortURLStatsRow struct {
	HitCount  int64              `json:"hit_count"`
	LastHitAt pgtype.Timestamptz `json:"last_hit_at"`
}

func (q *Queries) GetShortURLStats(ctx context.Context, token string) (GetShortURLStatsRow, error) {
	row := q.db.QueryRow(ctx, getShortURLStats, token)
	var i GetShortURLStatsRow
	err := row.Scan(&i.HitCount, &i.LastHitAt)
	return i, err
}

const hitShortURL = `-- name: HitShortURL :one
UPDATE short_urls
SET hit_count = hit_count + 1,
    last_hit_at = $1::timestamptz
WHERE token = $2::varchar
  AND brand_id = $3::bigint
  AND (expires_at IS NULL OR expires_at > $1::timestamptz)
RETURNING target_path, expires_at
`

type HitShortURLParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	Token   string             `json:"token"`
	BrandID int64              `json:"brand_id"`
}

type HitShortURLRow struct {
	TargetPath string             `json:"target_path"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Resolves a live token of the brand and counts the hit in one statement.
func (q *Queries) HitShortURL(ctx context.Context, arg HitShortURLParams) (HitShortURLRow, error) {
	row := q.db.QueryRow(ctx, hitShortURL, arg.Now, arg.Token, arg.BrandID)
	var i HitShortURLRow
	err := row.Scan(&i.TargetPath, &i.ExpiresAt)
	return i, err
}
