// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_import.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStockImportBatchForJob = `-- name: CreateStockImportBatchForJob :one
INSERT INTO stock_import_batches (
    uuid, organization_id, brand_id, created_by_user_id, source_filename, import_job_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, uuid, organization_id, brand_id, created_by_user_id, status, source_filename, target_owner_type, target_owner_id, rows_total, rows_new, rows_duplicate, rows_invalid, rows_conflict, error, applied_at, undone_at, created_at, updated_at, import_job_id
`

type CreateStockImportBatchForJobParams struct {
	Uuid            uuid.UUID   `json:"uuid"`
	OrganizationID  int64       `json:"organization_id"`
	BrandID         int64       `json:"brand_id"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
	SourceFilename  pgtype.Text `json:"source_filename"`
	ImportJobID     pgtype.Int8 `json:"import_job_id"`
}

func (q *Queries) CreateStockImportBatchForJob(ctx context.Context, arg CreateStockImportBatchForJobParams) (StockImportBatch, error) {
	row := q.db.QueryRow(ctx, createStockImportBatchForJob,
		arg.Uuid,
		arg.OrganizationID,
		arg.BrandID,
		arg.CreatedByUserID,
		arg.SourceFilename,
		arg.ImportJobID,
	)
	var i StockImportBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.CreatedByUserID,
		&i.Status,
		&i.SourceFilename,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.RowsTotal,
		&i.RowsNew,
		&i.RowsDuplicate,
		&i.RowsInvalid,
		&i.RowsConflict,
		&i.Error,
		&i.AppliedAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportJobID,
	)
	return i, err
}

const deleteStockImportRows = `-- name: DeleteStockImportRows :execrows
DELETE FROM stock_import_rows WHERE batch_id = $1
`

func (q *Queries) DeleteStockImportRows(ctx context.Context, batchID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStockImportRows, batchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStockImportBatchByJob = `-- name: GetStockImportBatchByJob :one
SELECT id, uuid, organization_id, brand_id, created_by_user_id, status, source_filename, target_owner_type, target_owner_id, rows_total, rows_new, rows_duplicate, rows_invalid, rows_conflict, error, applied_at, undone_at, created_at, updated_at, import_job_id FROM stock_import_batches WHERE import_job_id = $1
`

func (q *Queries) GetStockImportBatchByJob(ctx context.Context, importJobID pgtype.Int8) (StockImportBatch, error) {
	row := q.db.QueryRow(ctx, getStockImportBatchByJob, importJobID)
	var i StockImportBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.CreatedByUserID,
		&i.Status,
		&i.SourceFilename,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.RowsTotal,
		&i.RowsNew,
		&i.RowsDuplicate,
		&i.RowsInvalid,
		&i.RowsConflict,
		&i.Error,
		&i.AppliedAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportJobID,
	)
	return i, err
}

const getWarehouseLocationByCode = `-- name: GetWarehouseLocationByCode :one
SELECT id, uuid, organization_id, parent_id, code, name, active, created_at, updated_at, warehouse_id, room_id, type, full_code, sort_order FROM warehouse_locations
WHERE organization_id = $1
  AND (full_code = $2::text OR (room_id IS NULL AND code = $2::text))
ORDER BY (room_id IS NOT NULL) DESC
LIMIT 1
`

type GetWarehouseLocationByCodeParams struct {
	OrganizationID int64  `json:"organization_id"`
	Code           string `json:"code"`
}

// TEC-201: typed locations (000059) repeat sibling codes, so they are
// addressed by full_code; legacy locations keep their organization-unique
// code.
func (q *Queries) GetWarehouseLocationByCode(ctx context.Context, arg GetWarehouseLocationByCodeParams) (WarehouseLocation, error) {
	row := q.db.QueryRow(ctx, getWarehouseLocationByCode, arg.OrganizationID, arg.Code)
	var i WarehouseLocation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarehouseID,
		&i.RoomID,
		&i.Type,
		&i.FullCode,
		&i.SortOrder,
	)
	return i, err
}

const lockStockImportBatchByJob = `-- name: LockStockImportBatchByJob :one

SELECT id, uuid, organization_id, brand_id, created_by_user_id, status, source_filename, target_owner_type, target_owner_id, rows_total, rows_new, rows_duplicate, rows_invalid, rows_conflict, error, applied_at, undone_at, created_at, updated_at, import_job_id FROM stock_import_batches
WHERE import_job_id = $1
FOR UPDATE
`

// TEC-158: safe bulk stock import (staging, dry run, batch, undo). The
// batch belongs to one ioengine import job; rows are staged by the preview
// and applied/undone through ledger.Post in one transaction.
func (q *Queries) LockStockImportBatchByJob(ctx context.Context, importJobID pgtype.Int8) (StockImportBatch, error) {
	row := q.db.QueryRow(ctx, lockStockImportBatchByJob, importJobID)
	var i StockImportBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.CreatedByUserID,
		&i.Status,
		&i.SourceFilename,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.RowsTotal,
		&i.RowsNew,
		&i.RowsDuplicate,
		&i.RowsInvalid,
		&i.RowsConflict,
		&i.Error,
		&i.AppliedAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportJobID,
	)
	return i, err
}

const markStockImportRowUndone = `-- name: MarkStockImportRowUndone :one
UPDATE stock_import_rows
SET row_status = 'undone',
    undo_movement_id = $1,
    errors = '[]'::jsonb
WHERE id = $2 AND row_status = 'applied'
RETURNING id, batch_id, row_number, barcode, product_sku, product_id, quantity, meters, target_owner_type, target_owner_id, raw, row_status, errors, unit_id, movement_id, created_at, updated_at, undo_movement_id
`

type MarkStockImportRowUndoneParams struct {
	UndoMovementID pgtype.Int8 `json:"undo_movement_id"`
	ID             int64       `json:"id"`
}

func (q *Queries) MarkStockImportRowUndone(ctx context.Context, arg MarkStockImportRowUndoneParams) (StockImportRow, error) {
	row := q.db.QueryRow(ctx, markStockImportRowUndone, arg.UndoMovementID, arg.ID)
	var i StockImportRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowNumber,
		&i.Barcode,
		&i.ProductSku,
		&i.ProductID,
		&i.Quantity,
		&i.Meters,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.Raw,
		&i.RowStatus,
		&i.Errors,
		&i.UnitID,
		&i.MovementID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UndoMovementID,
	)
	return i, err
}

const setStockImportBatchState = `-- name: SetStockImportBatchState :one
UPDATE stock_import_batches
SET status = $1::text,
    rows_total = $2,
    rows_new = $3,
    rows_duplicate = $4,
    rows_invalid = $5,
    rows_conflict = $6,
    error = $7,
    applied_at = CASE WHEN $1::text = 'applied' THEN NOW() ELSE applied_at END,
    undone_at = CASE WHEN $1::text IN ('undone', 'partially_undone') THEN NOW() ELSE undone_at END
WHERE id = $8
RETURNING id, uuid, organization_id, brand_id, created_by_user_id, status, source_filename, target_owner_type, target_owner_id, rows_total, rows_new, rows_duplicate, rows_invalid, rows_conflict, error, applied_at, undone_at, created_at, updated_at, import_job_id
`

type SetStockImportBatchStateParams struct {
	Status        string      `json:"status"`
	RowsTotal     int32       `json:"rows_total"`
	RowsNew       int32       `json:"rows_new"`
	RowsDuplicate int32       `json:"rows_duplicate"`
	RowsInvalid   int32       `json:"rows_invalid"`
	RowsConflict  int32       `json:"rows_conflict"`
	Error         pgtype.Text `json:"error"`
	ID            int64       `json:"id"`
}

func (q *Queries) SetStockImportBatchState(ctx context.Context, arg SetStockImportBatchStateParams) (StockImportBatch, error) {
	row := q.db.QueryRow(ctx, setStockImportBatchState,
		arg.Status,
		arg.RowsTotal,
		arg.RowsNew,
		arg.RowsDuplicate,
		arg.RowsInvalid,
		arg.RowsConflict,
		arg.Error,
		arg.ID,
	)
	var i StockImportBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.CreatedByUserID,
		&i.Status,
		&i.SourceFilename,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.RowsTotal,
		&i.RowsNew,
		&i.RowsDuplicate,
		&i.RowsInvalid,
		&i.RowsConflict,
		&i.Error,
		&i.AppliedAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportJobID,
	)
	return i, err
}

const setStockImportRowErrors = `-- name: SetStockImportRowErrors :one
UPDATE stock_import_rows
SET errors = $1
WHERE id = $2
RETURNING id, batch_id, row_number, barcode, product_sku, product_id, quantity, meters, target_owner_type, target_owner_id, raw, row_status, errors, unit_id, movement_id, created_at, updated_at, undo_movement_id
`

type SetStockImportRowErrorsParams struct {
	Errors []byte `json:"errors"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetStockImportRowErrors(ctx context.Context, arg SetStockImportRowErrorsParams) (StockImportRow, error) {
	row := q.db.QueryRow(ctx, setStockImportRowErrors, arg.Errors, arg.ID)
	var i StockImportRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowNumber,
		&i.Barcode,
		&i.ProductSku,
		&i.ProductID,
		&i.Quantity,
		&i.Meters,
		&i.TargetOwnerType,
		&i.TargetOwnerID,
		&i.Raw,
		&i.RowStatus,
		&i.Errors,
		&i.UnitID,
		&i.MovementID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UndoMovementID,
	)
	return i, err
}
