// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTaskComments = `-- name: CountTaskComments :one
SELECT COUNT(*)::bigint FROM task_comments WHERE task_id = $1
`

func (q *Queries) CountTaskComments(ctx context.Context, taskID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskComments, taskID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)::bigint FROM tasks t
WHERE t.brand_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND (NOT $3::boolean OR t.status IN ('open', 'in_progress'))
  AND ($4::text IS NULL OR t.priority = $4::text)
  AND ($5::bigint IS NULL OR t.subject_org_id = $5::bigint)
  AND ($6::bigint IS NULL OR t.assignee_user_id = $6::bigint)
`

type CountTasksParams struct {
	BrandID        int64       `json:"brand_id"`
	Status         pgtype.Text `json:"status"`
	OnlyOpen       bool        `json:"only_open"`
	Priority       pgtype.Text `json:"priority"`
	SubjectOrgID   pgtype.Int8 `json:"subject_org_id"`
	AssigneeUserID pgtype.Int8 `json:"assignee_user_id"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.BrandID,
		arg.Status,
		arg.OnlyOpen,
		arg.Priority,
		arg.SubjectOrgID,
		arg.AssigneeUserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCenterMemberByUUID = `-- name: GetCenterMemberByUUID :one
SELECT u.id, u.uuid, u.name, u.surname FROM users u
JOIN organization_members m ON m.user_id = u.id
WHERE u.uuid = $1 AND m.organization_id = $2 AND u.deleted_at IS NULL
`

type GetCenterMemberByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetCenterMemberByUUIDRow struct {
	ID      int64     `json:"id"`
	Uuid    uuid.UUID `json:"uuid"`
	Name    string    `json:"name"`
	Surname string    `json:"surname"`
}

// A user that is a member of the given (center) organization.
func (q *Queries) GetCenterMemberByUUID(ctx context.Context, arg GetCenterMemberByUUIDParams) (GetCenterMemberByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCenterMemberByUUID, arg.Uuid, arg.OrganizationID)
	var i GetCenterMemberByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Surname,
	)
	return i, err
}

const getTaskByUUID = `-- name: GetTaskByUUID :one
SELECT id, uuid, organization_id, brand_id, subject_org_id, title, description, assignee_user_id, priority, due_at, status, source, created_by_user_id, closed_by_user_id, closed_at, created_at, updated_at FROM tasks
WHERE uuid = $1 AND brand_id = $2
`

type GetTaskByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetTaskByUUID(ctx context.Context, arg GetTaskByUUIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUUID, arg.Uuid, arg.BrandID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskSubjectOrg = `-- name: GetTaskSubjectOrg :one
SELECT id, uuid, name, type, brand_id FROM organizations
WHERE uuid = $1 AND brand_id = $2 AND deleted_at IS NULL
`

type GetTaskSubjectOrgParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

type GetTaskSubjectOrgRow struct {
	ID      int64     `json:"id"`
	Uuid    uuid.UUID `json:"uuid"`
	Name    string    `json:"name"`
	Type    string    `json:"type"`
	BrandID int64     `json:"brand_id"`
}

// An organization of the brand by uuid (the use case checks the type).
func (q *Queries) GetTaskSubjectOrg(ctx context.Context, arg GetTaskSubjectOrgParams) (GetTaskSubjectOrgRow, error) {
	row := q.db.QueryRow(ctx, getTaskSubjectOrg, arg.Uuid, arg.BrandID)
	var i GetTaskSubjectOrgRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.BrandID,
	)
	return i, err
}

const getTaskView = `-- name: GetTaskView :one
SELECT t.id, t.uuid, t.organization_id, t.brand_id, t.subject_org_id, t.title, t.description, t.assignee_user_id, t.priority, t.due_at, t.status, t.source, t.created_by_user_id, t.closed_by_user_id, t.closed_at, t.created_at, t.updated_at,
       s.uuid AS subject_uuid, s.name AS subject_name, s.type AS subject_type,
       a.uuid AS assignee_uuid, a.name AS assignee_name, a.surname AS assignee_surname,
       c.uuid AS creator_uuid, c.name AS creator_name, c.surname AS creator_surname,
       (SELECT COUNT(*) FROM task_comments tc WHERE tc.task_id = t.id)::bigint AS comment_count
FROM tasks t
JOIN organizations s ON s.id = t.subject_org_id
LEFT JOIN users a ON a.id = t.assignee_user_id
LEFT JOIN users c ON c.id = t.created_by_user_id
WHERE t.uuid = $1 AND t.brand_id = $2
`

type GetTaskViewParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

type GetTaskViewRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	OrganizationID  int64              `json:"organization_id"`
	BrandID         int64              `json:"brand_id"`
	SubjectOrgID    int64              `json:"subject_org_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	AssigneeUserID  pgtype.Int8        `json:"assignee_user_id"`
	Priority        string             `json:"priority"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	Status          string             `json:"status"`
	Source          string             `json:"source"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	ClosedByUserID  pgtype.Int8        `json:"closed_by_user_id"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SubjectUuid     uuid.UUID          `json:"subject_uuid"`
	SubjectName     string             `json:"subject_name"`
	SubjectType     string             `json:"subject_type"`
	AssigneeUuid    pgtype.UUID        `json:"assignee_uuid"`
	AssigneeName    pgtype.Text        `json:"assignee_name"`
	AssigneeSurname pgtype.Text        `json:"assignee_surname"`
	CreatorUuid     pgtype.UUID        `json:"creator_uuid"`
	CreatorName     pgtype.Text        `json:"creator_name"`
	CreatorSurname  pgtype.Text        `json:"creator_surname"`
	CommentCount    int64              `json:"comment_count"`
}

func (q *Queries) GetTaskView(ctx context.Context, arg GetTaskViewParams) (GetTaskViewRow, error) {
	row := q.db.QueryRow(ctx, getTaskView, arg.Uuid, arg.BrandID)
	var i GetTaskViewRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubjectUuid,
		&i.SubjectName,
		&i.SubjectType,
		&i.AssigneeUuid,
		&i.AssigneeName,
		&i.AssigneeSurname,
		&i.CreatorUuid,
		&i.CreatorName,
		&i.CreatorSurname,
		&i.CommentCount,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one

INSERT INTO tasks (
    organization_id, brand_id, subject_org_id, title, description,
    assignee_user_id, priority, due_at, source, created_by_user_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
RETURNING id, uuid, organization_id, brand_id, subject_org_id, title, description, assignee_user_id, priority, due_at, status, source, created_by_user_id, closed_by_user_id, closed_at, created_at, updated_at
`

type InsertTaskParams struct {
	OrganizationID  int64              `json:"organization_id"`
	BrandID         int64              `json:"brand_id"`
	SubjectOrgID    int64              `json:"subject_org_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	AssigneeUserID  pgtype.Int8        `json:"assignee_user_id"`
	Priority        string             `json:"priority"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	Source          string             `json:"source"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
}

// TEC-214 (F1-11a): center tasks (tasks, task_comments). Every read is
// bounded by the brand of the active center organization.
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.OrganizationID,
		arg.BrandID,
		arg.SubjectOrgID,
		arg.Title,
		arg.Description,
		arg.AssigneeUserID,
		arg.Priority,
		arg.DueAt,
		arg.Source,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaskComment = `-- name: InsertTaskComment :one
INSERT INTO task_comments (task_id, organization_id, brand_id, author_user_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, task_id, organization_id, brand_id, author_user_id, body, created_at
`

type InsertTaskCommentParams struct {
	TaskID         int64       `json:"task_id"`
	OrganizationID int64       `json:"organization_id"`
	BrandID        int64       `json:"brand_id"`
	AuthorUserID   pgtype.Int8 `json:"author_user_id"`
	Body           string      `json:"body"`
}

func (q *Queries) InsertTaskComment(ctx context.Context, arg InsertTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, insertTaskComment,
		arg.TaskID,
		arg.OrganizationID,
		arg.BrandID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.TaskID,
		&i.OrganizationID,
		&i.BrandID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT tc.id, tc.uuid, tc.task_id, tc.organization_id, tc.brand_id, tc.author_user_id, tc.body, tc.created_at, u.uuid AS author_uuid, u.name AS author_name, u.surname AS author_surname
FROM task_comments tc
LEFT JOIN users u ON u.id = tc.author_user_id
WHERE tc.task_id = $1
ORDER BY tc.created_at, tc.id
LIMIT $3 OFFSET $2
`

type ListTaskCommentsParams struct {
	TaskID    int64 `json:"task_id"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

type ListTaskCommentsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	TaskID         int64              `json:"task_id"`
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	AuthorUserID   pgtype.Int8        `json:"author_user_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthorUuid     pgtype.UUID        `json:"author_uuid"`
	AuthorName     pgtype.Text        `json:"author_name"`
	AuthorSurname  pgtype.Text        `json:"author_surname"`
}

func (q *Queries) ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, arg.TaskID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommentsRow{}
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.TaskID,
			&i.OrganizationID,
			&i.BrandID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUuid,
			&i.AuthorName,
			&i.AuthorSurname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.uuid, t.organization_id, t.brand_id, t.subject_org_id, t.title, t.description, t.assignee_user_id, t.priority, t.due_at, t.status, t.source, t.created_by_user_id, t.closed_by_user_id, t.closed_at, t.created_at, t.updated_at,
       s.uuid AS subject_uuid, s.name AS subject_name, s.type AS subject_type,
       a.uuid AS assignee_uuid, a.name AS assignee_name, a.surname AS assignee_surname,
       c.uuid AS creator_uuid, c.name AS creator_name, c.surname AS creator_surname,
       (SELECT COUNT(*) FROM task_comments tc WHERE tc.task_id = t.id)::bigint AS comment_count
FROM tasks t
JOIN organizations s ON s.id = t.subject_org_id
LEFT JOIN users a ON a.id = t.assignee_user_id
LEFT JOIN users c ON c.id = t.created_by_user_id
WHERE t.brand_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
  AND (NOT $3::boolean OR t.status IN ('open', 'in_progress'))
  AND ($4::text IS NULL OR t.priority = $4::text)
  AND ($5::bigint IS NULL OR t.subject_org_id = $5::bigint)
  AND ($6::bigint IS NULL OR t.assignee_user_id = $6::bigint)
ORDER BY t.created_at DESC, t.id DESC
LIMIT $8 OFFSET $7
`

type ListTasksParams struct {
	BrandID        int64       `json:"brand_id"`
	Status         pgtype.Text `json:"status"`
	OnlyOpen       bool        `json:"only_open"`
	Priority       pgtype.Text `json:"priority"`
	SubjectOrgID   pgtype.Int8 `json:"subject_org_id"`
	AssigneeUserID pgtype.Int8 `json:"assignee_user_id"`
	RowOffset      int32       `json:"row_offset"`
	RowLimit       int32       `json:"row_limit"`
}

type ListTasksRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	OrganizationID  int64              `json:"organization_id"`
	BrandID         int64              `json:"brand_id"`
	SubjectOrgID    int64              `json:"subject_org_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	AssigneeUserID  pgtype.Int8        `json:"assignee_user_id"`
	Priority        string             `json:"priority"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	Status          string             `json:"status"`
	Source          string             `json:"source"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	ClosedByUserID  pgtype.Int8        `json:"closed_by_user_id"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SubjectUuid     uuid.UUID          `json:"subject_uuid"`
	SubjectName     string             `json:"subject_name"`
	SubjectType     string             `json:"subject_type"`
	AssigneeUuid    pgtype.UUID        `json:"assignee_uuid"`
	AssigneeName    pgtype.Text        `json:"assignee_name"`
	AssigneeSurname pgtype.Text        `json:"assignee_surname"`
	CreatorUuid     pgtype.UUID        `json:"creator_uuid"`
	CreatorName     pgtype.Text        `json:"creator_name"`
	CreatorSurname  pgtype.Text        `json:"creator_surname"`
	CommentCount    int64              `json:"comment_count"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.BrandID,
		arg.Status,
		arg.OnlyOpen,
		arg.Priority,
		arg.SubjectOrgID,
		arg.AssigneeUserID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.SubjectOrgID,
			&i.Title,
			&i.Description,
			&i.AssigneeUserID,
			&i.Priority,
			&i.DueAt,
			&i.Status,
			&i.Source,
			&i.CreatedByUserID,
			&i.ClosedByUserID,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubjectUuid,
			&i.SubjectName,
			&i.SubjectType,
			&i.AssigneeUuid,
			&i.AssigneeName,
			&i.AssigneeSurname,
			&i.CreatorUuid,
			&i.CreatorName,
			&i.CreatorSurname,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTask = `-- name: LockTask :one
SELECT id, uuid, organization_id, brand_id, subject_org_id, title, description, assignee_user_id, priority, due_at, status, source, created_by_user_id, closed_by_user_id, closed_at, created_at, updated_at FROM tasks
WHERE uuid = $1 AND brand_id = $2
FOR UPDATE
`

type LockTaskParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) LockTask(ctx context.Context, arg LockTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, lockTask, arg.Uuid, arg.BrandID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskAssignee = `-- name: SetTaskAssignee :one
UPDATE tasks
SET assignee_user_id = $1
WHERE id = $2
RETURNING id, uuid, organization_id, brand_id, subject_org_id, title, description, assignee_user_id, priority, due_at, status, source, created_by_user_id, closed_by_user_id, closed_at, created_at, updated_at
`

type SetTaskAssigneeParams struct {
	AssigneeUserID pgtype.Int8 `json:"assignee_user_id"`
	ID             int64       `json:"id"`
}

// TEC-212: bulk engine adapter (assign one task, logged + undoable).
func (q *Queries) SetTaskAssignee(ctx context.Context, arg SetTaskAssigneeParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskAssignee, arg.AssigneeUserID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET subject_org_id = $1,
    title = $2,
    description = $3,
    assignee_user_id = $4,
    priority = $5,
    due_at = $6,
    status = $7,
    closed_at = $8,
    closed_by_user_id = $9
WHERE id = $10
RETURNING id, uuid, organization_id, brand_id, subject_org_id, title, description, assignee_user_id, priority, due_at, status, source, created_by_user_id, closed_by_user_id, closed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	SubjectOrgID   int64              `json:"subject_org_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	AssigneeUserID pgtype.Int8        `json:"assignee_user_id"`
	Priority       string             `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	Status         string             `json:"status"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	ClosedByUserID pgtype.Int8        `json:"closed_by_user_id"`
	ID             int64              `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.SubjectOrgID,
		arg.Title,
		arg.Description,
		arg.AssigneeUserID,
		arg.Priority,
		arg.DueAt,
		arg.Status,
		arg.ClosedAt,
		arg.ClosedByUserID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.SubjectOrgID,
		&i.Title,
		&i.Description,
		&i.AssigneeUserID,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.Source,
		&i.CreatedByUserID,
		&i.ClosedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
