// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCarBrands = `-- name: CountCarBrands :one
SELECT COUNT(*)::bigint FROM car_brands b
WHERE ($1::bool IS NULL OR b.active = $1::bool)
  AND ($2::bool IS NULL OR (b.logo_object_key IS NOT NULL) = $2::bool)
  AND ($3::text IS NULL OR b.name ILIKE '%' || $3::text || '%'
       OR b.external_id = $3::text)
`

type CountCarBrandsParams struct {
	Active  pgtype.Bool `json:"active"`
	HasLogo pgtype.Bool `json:"has_logo"`
	Q       pgtype.Text `json:"q"`
}

func (q *Queries) CountCarBrands(ctx context.Context, arg CountCarBrandsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCarBrands, arg.Active, arg.HasLogo, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCarModels = `-- name: CountCarModels :one
SELECT COUNT(*)::bigint
FROM car_models m
JOIN car_brands b ON b.id = m.car_brand_id
WHERE ($1::bigint IS NULL OR m.car_brand_id = $1::bigint)
  AND ($2::bool IS NULL OR m.active = $2::bool)
  AND ($3::bool IS NULL OR b.active = $3::bool)
  AND (
    COALESCE(cardinality($4::text[]), 0) = 0
    OR m.body_type = ANY ($4::text[])
  )
  AND (
    COALESCE(cardinality($5::text[]), 0) = 0
    OR m.powertrain = ANY ($5::text[])
  )
  -- Model year range: the production span [year_start, year_stop] overlaps
  -- [year_min, year_max]; an open end (NULL) counts as unbounded.
  AND ($6::int IS NULL OR m.year_start IS NULL OR m.year_start <= $6::int)
  AND ($7::int IS NULL OR m.year_stop IS NULL OR m.year_stop >= $7::int)
  AND ($8::text IS NULL OR (b.name || ' ' || m.name) ILIKE '%' || $8::text || '%'
       OR m.external_id = $8::text)
`

type CountCarModelsParams struct {
	CarBrandID  pgtype.Int8 `json:"car_brand_id"`
	Active      pgtype.Bool `json:"active"`
	BrandActive pgtype.Bool `json:"brand_active"`
	BodyTypes   []string    `json:"body_types"`
	Powertrains []string    `json:"powertrains"`
	YearMax     pgtype.Int4 `json:"year_max"`
	YearMin     pgtype.Int4 `json:"year_min"`
	Q           pgtype.Text `json:"q"`
}

func (q *Queries) CountCarModels(ctx context.Context, arg CountCarModelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCarModels,
		arg.CarBrandID,
		arg.Active,
		arg.BrandActive,
		arg.BodyTypes,
		arg.Powertrains,
		arg.YearMax,
		arg.YearMin,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCarModelsByBrand = `-- name: CountCarModelsByBrand :one
SELECT COUNT(*)::bigint FROM car_models WHERE car_brand_id = $1
`

func (q *Queries) CountCarModelsByBrand(ctx context.Context, carBrandID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCarModelsByBrand, carBrandID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCarBrand = `-- name: CreateCarBrand :one

INSERT INTO car_brands (external_id, name, show_name, logo_height, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at
`

type CreateCarBrandParams struct {
	ExternalID pgtype.Text `json:"external_id"`
	Name       string      `json:"name"`
	ShowName   bool        `json:"show_name"`
	LogoHeight pgtype.Int2 `json:"logo_height"`
	Active     bool        `json:"active"`
}

// TEC-149: vehicle catalog (car brands and models). Global reference data:
// no organization/brand filter; only super_admin writes (use case + route).
func (q *Queries) CreateCarBrand(ctx context.Context, arg CreateCarBrandParams) (CarBrand, error) {
	row := q.db.QueryRow(ctx, createCarBrand,
		arg.ExternalID,
		arg.Name,
		arg.ShowName,
		arg.LogoHeight,
		arg.Active,
	)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCarModel = `-- name: CreateCarModel :one
INSERT INTO car_models (car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, active)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at
`

type CreateCarModelParams struct {
	CarBrandID int64       `json:"car_brand_id"`
	ExternalID pgtype.Text `json:"external_id"`
	Name       string      `json:"name"`
	BodyType   pgtype.Text `json:"body_type"`
	Powertrain pgtype.Text `json:"powertrain"`
	YearStart  pgtype.Int2 `json:"year_start"`
	YearStop   pgtype.Int2 `json:"year_stop"`
	Active     bool        `json:"active"`
}

func (q *Queries) CreateCarModel(ctx context.Context, arg CreateCarModelParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, createCarModel,
		arg.CarBrandID,
		arg.ExternalID,
		arg.Name,
		arg.BodyType,
		arg.Powertrain,
		arg.YearStart,
		arg.YearStop,
		arg.Active,
	)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCarBrand = `-- name: DeleteCarBrand :execrows
DELETE FROM car_brands WHERE id = $1
`

// Fails with a restrict/foreign key violation while models still use the brand.
func (q *Queries) DeleteCarBrand(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCarBrand, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCarModel = `-- name: DeleteCarModel :execrows
DELETE FROM car_models WHERE id = $1
`

func (q *Queries) DeleteCarModel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCarModel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCarBrandByID = `-- name: GetCarBrandByID :one
SELECT id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at FROM car_brands WHERE id = $1
`

func (q *Queries) GetCarBrandByID(ctx context.Context, id int64) (CarBrand, error) {
	row := q.db.QueryRow(ctx, getCarBrandByID, id)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarBrandByUUID = `-- name: GetCarBrandByUUID :one
SELECT id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at FROM car_brands WHERE uuid = $1
`

func (q *Queries) GetCarBrandByUUID(ctx context.Context, argUuid uuid.UUID) (CarBrand, error) {
	row := q.db.QueryRow(ctx, getCarBrandByUUID, argUuid)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarModelByUUID = `-- name: GetCarModelByUUID :one
SELECT id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at FROM car_models WHERE uuid = $1
`

func (q *Queries) GetCarModelByUUID(ctx context.Context, argUuid uuid.UUID) (CarModel, error) {
	row := q.db.QueryRow(ctx, getCarModelByUUID, argUuid)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarBrands = `-- name: ListCarBrands :many
SELECT b.id, b.uuid, b.external_id, b.name, b.logo_object_key, b.hero_object_key, b.show_name, b.logo_height, b.active, b.created_at, b.updated_at,
       (SELECT COUNT(*) FROM car_models m WHERE m.car_brand_id = b.id)::bigint AS model_count
FROM car_brands b
WHERE ($1::bool IS NULL OR b.active = $1::bool)
  AND ($2::bool IS NULL OR (b.logo_object_key IS NOT NULL) = $2::bool)
  AND ($3::text IS NULL OR b.name ILIKE '%' || $3::text || '%'
       OR b.external_id = $3::text)
ORDER BY
  CASE WHEN NOT $4::bool THEN
    CASE $5::text WHEN 'name' THEN lower(b.name) END
  END ASC,
  CASE WHEN $4::bool THEN
    CASE $5::text WHEN 'name' THEN lower(b.name) END
  END DESC,
  CASE WHEN NOT $4::bool THEN
    CASE $5::text WHEN 'model_count' THEN (SELECT COUNT(*) FROM car_models m WHERE m.car_brand_id = b.id) END
  END ASC,
  CASE WHEN $4::bool THEN
    CASE $5::text WHEN 'model_count' THEN (SELECT COUNT(*) FROM car_models m WHERE m.car_brand_id = b.id) END
  END DESC,
  CASE WHEN NOT $4::bool THEN
    CASE $5::text WHEN 'active' THEN b.active END
  END ASC,
  CASE WHEN $4::bool THEN
    CASE $5::text WHEN 'active' THEN b.active END
  END DESC,
  CASE WHEN NOT $4::bool THEN
    CASE $5::text WHEN 'created_at' THEN b.created_at WHEN 'updated_at' THEN b.updated_at END
  END ASC,
  CASE WHEN $4::bool THEN
    CASE $5::text WHEN 'created_at' THEN b.created_at WHEN 'updated_at' THEN b.updated_at END
  END DESC,
  lower(b.name) ASC,
  CASE WHEN $4::bool THEN b.id END DESC,
  b.id ASC
LIMIT $7 OFFSET $6
`

type ListCarBrandsParams struct {
	Active      pgtype.Bool `json:"active"`
	HasLogo     pgtype.Bool `json:"has_logo"`
	Q           pgtype.Text `json:"q"`
	SortDesc    bool        `json:"sort_desc"`
	SortKey     string      `json:"sort_key"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListCarBrandsRow struct {
	ID            int64              `json:"id"`
	Uuid          uuid.UUID          `json:"uuid"`
	ExternalID    pgtype.Text        `json:"external_id"`
	Name          string             `json:"name"`
	LogoObjectKey pgtype.Text        `json:"logo_object_key"`
	HeroObjectKey pgtype.Text        `json:"hero_object_key"`
	ShowName      bool               `json:"show_name"`
	LogoHeight    pgtype.Int2        `json:"logo_height"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ModelCount    int64              `json:"model_count"`
}

// TEC-369: sort keys from model.BrandSort (docs/list-contract.md); default name.
func (q *Queries) ListCarBrands(ctx context.Context, arg ListCarBrandsParams) ([]ListCarBrandsRow, error) {
	rows, err := q.db.Query(ctx, listCarBrands,
		arg.Active,
		arg.HasLogo,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarBrandsRow{}
	for rows.Next() {
		var i ListCarBrandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ExternalID,
			&i.Name,
			&i.LogoObjectKey,
			&i.HeroObjectKey,
			&i.ShowName,
			&i.LogoHeight,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarModelBodyTypeFacets = `-- name: ListCarModelBodyTypeFacets :many

SELECT m.body_type::text AS value, COUNT(*)::bigint AS count
FROM car_models m
JOIN car_brands b ON b.id = m.car_brand_id
WHERE m.body_type IS NOT NULL
  AND ($1::bigint IS NULL OR m.car_brand_id = $1::bigint)
  AND ($2::bool IS NULL OR m.active = $2::bool)
  AND ($3::bool IS NULL OR b.active = $3::bool)
GROUP BY m.body_type
ORDER BY lower(m.body_type), m.body_type
`

type ListCarModelBodyTypeFacetsParams struct {
	CarBrandID  pgtype.Int8 `json:"car_brand_id"`
	Active      pgtype.Bool `json:"active"`
	BrandActive pgtype.Bool `json:"brand_active"`
}

type ListCarModelBodyTypeFacetsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

// TEC-369: faceted filter options of the model list (distinct free-text
// values with counts), scoped like the list.
func (q *Queries) ListCarModelBodyTypeFacets(ctx context.Context, arg ListCarModelBodyTypeFacetsParams) ([]ListCarModelBodyTypeFacetsRow, error) {
	rows, err := q.db.Query(ctx, listCarModelBodyTypeFacets, arg.CarBrandID, arg.Active, arg.BrandActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarModelBodyTypeFacetsRow{}
	for rows.Next() {
		var i ListCarModelBodyTypeFacetsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarModelPowertrainFacets = `-- name: ListCarModelPowertrainFacets :many
SELECT m.powertrain::text AS value, COUNT(*)::bigint AS count
FROM car_models m
JOIN car_brands b ON b.id = m.car_brand_id
WHERE m.powertrain IS NOT NULL
  AND ($1::bigint IS NULL OR m.car_brand_id = $1::bigint)
  AND ($2::bool IS NULL OR m.active = $2::bool)
  AND ($3::bool IS NULL OR b.active = $3::bool)
GROUP BY m.powertrain
ORDER BY lower(m.powertrain), m.powertrain
`

type ListCarModelPowertrainFacetsParams struct {
	CarBrandID  pgtype.Int8 `json:"car_brand_id"`
	Active      pgtype.Bool `json:"active"`
	BrandActive pgtype.Bool `json:"brand_active"`
}

type ListCarModelPowertrainFacetsRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

func (q *Queries) ListCarModelPowertrainFacets(ctx context.Context, arg ListCarModelPowertrainFacetsParams) ([]ListCarModelPowertrainFacetsRow, error) {
	rows, err := q.db.Query(ctx, listCarModelPowertrainFacets, arg.CarBrandID, arg.Active, arg.BrandActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarModelPowertrainFacetsRow{}
	for rows.Next() {
		var i ListCarModelPowertrainFacetsRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarModels = `-- name: ListCarModels :many
SELECT m.id, m.uuid, m.car_brand_id, m.external_id, m.name, m.body_type, m.powertrain, m.year_start, m.year_stop, m.hero_object_key, m.active, m.created_at, m.updated_at, b.uuid AS brand_uuid, b.name AS brand_name, b.hero_object_key AS brand_hero_object_key
FROM car_models m
JOIN car_brands b ON b.id = m.car_brand_id
WHERE ($1::bigint IS NULL OR m.car_brand_id = $1::bigint)
  AND ($2::bool IS NULL OR m.active = $2::bool)
  AND ($3::bool IS NULL OR b.active = $3::bool)
  AND (
    COALESCE(cardinality($4::text[]), 0) = 0
    OR m.body_type = ANY ($4::text[])
  )
  AND (
    COALESCE(cardinality($5::text[]), 0) = 0
    OR m.powertrain = ANY ($5::text[])
  )
  -- Model year range: the production span [year_start, year_stop] overlaps
  -- [year_min, year_max]; an open end (NULL) counts as unbounded.
  AND ($6::int IS NULL OR m.year_start IS NULL OR m.year_start <= $6::int)
  AND ($7::int IS NULL OR m.year_stop IS NULL OR m.year_stop >= $7::int)
  AND ($8::text IS NULL OR (b.name || ' ' || m.name) ILIKE '%' || $8::text || '%'
       OR m.external_id = $8::text)
ORDER BY
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'name' THEN lower(m.name) WHEN 'brand' THEN lower(b.name) END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'name' THEN lower(m.name) WHEN 'brand' THEN lower(b.name) END
  END DESC,
  CASE WHEN NOT $9::bool AND $10::text = 'year_start' THEN m.year_start END ASC NULLS LAST,
  CASE WHEN $9::bool AND $10::text = 'year_start' THEN m.year_start END DESC NULLS LAST,
  CASE WHEN NOT $9::bool AND $10::text = 'year_stop' THEN m.year_stop END ASC NULLS LAST,
  CASE WHEN $9::bool AND $10::text = 'year_stop' THEN m.year_stop END DESC NULLS LAST,
  CASE WHEN NOT $9::bool AND $10::text = 'body_type' THEN lower(m.body_type) END ASC NULLS LAST,
  CASE WHEN $9::bool AND $10::text = 'body_type' THEN lower(m.body_type) END DESC NULLS LAST,
  CASE WHEN NOT $9::bool AND $10::text = 'powertrain' THEN lower(m.powertrain) END ASC NULLS LAST,
  CASE WHEN $9::bool AND $10::text = 'powertrain' THEN lower(m.powertrain) END DESC NULLS LAST,
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'active' THEN m.active END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'active' THEN m.active END
  END DESC,
  CASE WHEN NOT $9::bool THEN
    CASE $10::text WHEN 'created_at' THEN m.created_at WHEN 'updated_at' THEN m.updated_at END
  END ASC,
  CASE WHEN $9::bool THEN
    CASE $10::text WHEN 'created_at' THEN m.created_at WHEN 'updated_at' THEN m.updated_at END
  END DESC,
  lower(b.name) ASC,
  lower(m.name) ASC,
  CASE WHEN $9::bool THEN m.id END DESC,
  m.id ASC
LIMIT $12 OFFSET $11
`

type ListCarModelsParams struct {
	CarBrandID  pgtype.Int8 `json:"car_brand_id"`
	Active      pgtype.Bool `json:"active"`
	BrandActive pgtype.Bool `json:"brand_active"`
	BodyTypes   []string    `json:"body_types"`
	Powertrains []string    `json:"powertrains"`
	YearMax     pgtype.Int4 `json:"year_max"`
	YearMin     pgtype.Int4 `json:"year_min"`
	Q           pgtype.Text `json:"q"`
	SortDesc    bool        `json:"sort_desc"`
	SortKey     string      `json:"sort_key"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListCarModelsRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	CarBrandID         int64              `json:"car_brand_id"`
	ExternalID         pgtype.Text        `json:"external_id"`
	Name               string             `json:"name"`
	BodyType           pgtype.Text        `json:"body_type"`
	Powertrain         pgtype.Text        `json:"powertrain"`
	YearStart          pgtype.Int2        `json:"year_start"`
	YearStop           pgtype.Int2        `json:"year_stop"`
	HeroObjectKey      pgtype.Text        `json:"hero_object_key"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	BrandUuid          uuid.UUID          `json:"brand_uuid"`
	BrandName          string             `json:"brand_name"`
	BrandHeroObjectKey pgtype.Text        `json:"brand_hero_object_key"`
}

// Search matches the model name, "brand model" and the external id.
// TEC-369: sort keys from model.ModelSort (docs/list-contract.md); default brand.
func (q *Queries) ListCarModels(ctx context.Context, arg ListCarModelsParams) ([]ListCarModelsRow, error) {
	rows, err := q.db.Query(ctx, listCarModels,
		arg.CarBrandID,
		arg.Active,
		arg.BrandActive,
		arg.BodyTypes,
		arg.Powertrains,
		arg.YearMax,
		arg.YearMin,
		arg.Q,
		arg.SortDesc,
		arg.SortKey,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarModelsRow{}
	for rows.Next() {
		var i ListCarModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CarBrandID,
			&i.ExternalID,
			&i.Name,
			&i.BodyType,
			&i.Powertrain,
			&i.YearStart,
			&i.YearStop,
			&i.HeroObjectKey,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandUuid,
			&i.BrandName,
			&i.BrandHeroObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCarBrandActiveByUUID = `-- name: SetCarBrandActiveByUUID :one
UPDATE car_brands SET active = $1
WHERE uuid = $2
RETURNING id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at
`

type SetCarBrandActiveByUUIDParams struct {
	Active bool      `json:"active"`
	Uuid   uuid.UUID `json:"uuid"`
}

// TEC-369 bulk activate/deactivate.
func (q *Queries) SetCarBrandActiveByUUID(ctx context.Context, arg SetCarBrandActiveByUUIDParams) (CarBrand, error) {
	row := q.db.QueryRow(ctx, setCarBrandActiveByUUID, arg.Active, arg.Uuid)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarBrandHero = `-- name: SetCarBrandHero :one
UPDATE car_brands SET hero_object_key = $1
WHERE id = $2
RETURNING id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at
`

type SetCarBrandHeroParams struct {
	HeroObjectKey pgtype.Text `json:"hero_object_key"`
	ID            int64       `json:"id"`
}

func (q *Queries) SetCarBrandHero(ctx context.Context, arg SetCarBrandHeroParams) (CarBrand, error) {
	row := q.db.QueryRow(ctx, setCarBrandHero, arg.HeroObjectKey, arg.ID)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarBrandLogo = `-- name: SetCarBrandLogo :one
UPDATE car_brands SET logo_object_key = $1
WHERE id = $2
RETURNING id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at
`

type SetCarBrandLogoParams struct {
	LogoObjectKey pgtype.Text `json:"logo_object_key"`
	ID            int64       `json:"id"`
}

func (q *Queries) SetCarBrandLogo(ctx context.Context, arg SetCarBrandLogoParams) (CarBrand, error) {
	row := q.db.QueryRow(ctx, setCarBrandLogo, arg.LogoObjectKey, arg.ID)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarModelActiveByUUID = `-- name: SetCarModelActiveByUUID :one
UPDATE car_models SET active = $1
WHERE uuid = $2
RETURNING id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at
`

type SetCarModelActiveByUUIDParams struct {
	Active bool      `json:"active"`
	Uuid   uuid.UUID `json:"uuid"`
}

func (q *Queries) SetCarModelActiveByUUID(ctx context.Context, arg SetCarModelActiveByUUIDParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, setCarModelActiveByUUID, arg.Active, arg.Uuid)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCarModelHero = `-- name: SetCarModelHero :one
UPDATE car_models SET hero_object_key = $1
WHERE id = $2
RETURNING id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at
`

type SetCarModelHeroParams struct {
	HeroObjectKey pgtype.Text `json:"hero_object_key"`
	ID            int64       `json:"id"`
}

func (q *Queries) SetCarModelHero(ctx context.Context, arg SetCarModelHeroParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, setCarModelHero, arg.HeroObjectKey, arg.ID)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCarBrand = `-- name: UpdateCarBrand :one
UPDATE car_brands
SET external_id = $1,
    name = $2,
    show_name = $3,
    logo_height = $4,
    active = $5
WHERE id = $6
RETURNING id, uuid, external_id, name, logo_object_key, hero_object_key, show_name, logo_height, active, created_at, updated_at
`

type UpdateCarBrandParams struct {
	ExternalID pgtype.Text `json:"external_id"`
	Name       string      `json:"name"`
	ShowName   bool        `json:"show_name"`
	LogoHeight pgtype.Int2 `json:"logo_height"`
	Active     bool        `json:"active"`
	ID         int64       `json:"id"`
}

// Full replacement of the editable fields (read-modify-write in the use case).
func (q *Queries) UpdateCarBrand(ctx context.Context, arg UpdateCarBrandParams) (CarBrand, error) {
	row := q.db.QueryRow(ctx, updateCarBrand,
		arg.ExternalID,
		arg.Name,
		arg.ShowName,
		arg.LogoHeight,
		arg.Active,
		arg.ID,
	)
	var i CarBrand
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.LogoObjectKey,
		&i.HeroObjectKey,
		&i.ShowName,
		&i.LogoHeight,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCarModel = `-- name: UpdateCarModel :one
UPDATE car_models
SET external_id = $1,
    name = $2,
    body_type = $3,
    powertrain = $4,
    year_start = $5,
    year_stop = $6,
    active = $7
WHERE id = $8
RETURNING id, uuid, car_brand_id, external_id, name, body_type, powertrain, year_start, year_stop, hero_object_key, active, created_at, updated_at
`

type UpdateCarModelParams struct {
	ExternalID pgtype.Text `json:"external_id"`
	Name       string      `json:"name"`
	BodyType   pgtype.Text `json:"body_type"`
	Powertrain pgtype.Text `json:"powertrain"`
	YearStart  pgtype.Int2 `json:"year_start"`
	YearStop   pgtype.Int2 `json:"year_stop"`
	Active     bool        `json:"active"`
	ID         int64       `json:"id"`
}

func (q *Queries) UpdateCarModel(ctx context.Context, arg UpdateCarModelParams) (CarModel, error) {
	row := q.db.QueryRow(ctx, updateCarModel,
		arg.ExternalID,
		arg.Name,
		arg.BodyType,
		arg.Powertrain,
		arg.YearStart,
		arg.YearStop,
		arg.Active,
		arg.ID,
	)
	var i CarModel
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CarBrandID,
		&i.ExternalID,
		&i.Name,
		&i.BodyType,
		&i.Powertrain,
		&i.YearStart,
		&i.YearStop,
		&i.HeroObjectKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
