// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warranties.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelVehicleTransfer = `-- name: CancelVehicleTransfer :one
UPDATE vehicle_transfers
SET status = 'cancelled', cancelled_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) CancelVehicleTransfer(ctx context.Context, id int64) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, cancelVehicleTransfer, id)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeWarrantyHolderByVehicle = `-- name: ChangeWarrantyHolderByVehicle :many
UPDATE warranties
SET holder_user_id = $1
WHERE vehicle_id = $2 AND status = 'active'
  AND holder_user_id IS DISTINCT FROM $1
RETURNING id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at
`

type ChangeWarrantyHolderByVehicleParams struct {
	NewHolderUserID int64 `json:"new_holder_user_id"`
	VehicleID       int64 `json:"vehicle_id"`
}

// Vehicle transfer (decision 6): the active warranties of the vehicle move
// to the new owner in the transfer transaction.
func (q *Queries) ChangeWarrantyHolderByVehicle(ctx context.Context, arg ChangeWarrantyHolderByVehicleParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, changeWarrantyHolderByVehicle, arg.NewHolderUserID, arg.VehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeVehicleTransfer = `-- name: CompleteVehicleTransfer :one
UPDATE vehicle_transfers
SET status = 'completed', completed_at = NOW(), to_user_id = $1
WHERE id = $2 AND status = 'pending'
  AND from_verified_at IS NOT NULL AND to_verified_at IS NOT NULL
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

type CompleteVehicleTransferParams struct {
	ToUserID pgtype.Int8 `json:"to_user_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) CompleteVehicleTransfer(ctx context.Context, arg CompleteVehicleTransferParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, completeVehicleTransfer, arg.ToUserID, arg.ID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWarrantiesInScope = `-- name: CountWarrantiesInScope :one
SELECT COUNT(*) FROM warranties
WHERE brand_id = $1
  AND ($2::bigint[] IS NULL OR organization_id = ANY ($2::bigint[]))
  AND ($3::bigint IS NULL OR holder_user_id = $3)
  AND ($4::bigint IS NULL OR vehicle_id = $4)
  AND ($5::text IS NULL OR status = $5::text)
`

type CountWarrantiesInScopeParams struct {
	BrandID      int64       `json:"brand_id"`
	OrgIds       []int64     `json:"org_ids"`
	HolderUserID pgtype.Int8 `json:"holder_user_id"`
	VehicleID    pgtype.Int8 `json:"vehicle_id"`
	Status       pgtype.Text `json:"status"`
}

func (q *Queries) CountWarrantiesInScope(ctx context.Context, arg CountWarrantiesInScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWarrantiesInScope,
		arg.BrandID,
		arg.OrgIds,
		arg.HolderUserID,
		arg.VehicleID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicleTransfer = `-- name: CreateVehicleTransfer :one

INSERT INTO vehicle_transfers (
    organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone,
    from_code_hash, to_code_hash, expires_at, initiated_by_user_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

type CreateVehicleTransferParams struct {
	OrganizationID    int64              `json:"organization_id"`
	BrandID           int64              `json:"brand_id"`
	VehicleID         int64              `json:"vehicle_id"`
	FromUserID        int64              `json:"from_user_id"`
	ToUserID          pgtype.Int8        `json:"to_user_id"`
	ToPhone           string             `json:"to_phone"`
	FromCodeHash      string             `json:"from_code_hash"`
	ToCodeHash        string             `json:"to_code_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	InitiatedByUserID pgtype.Int8        `json:"initiated_by_user_id"`
}

// ---------------------------------------------------------------------------
// Vehicle transfers.
func (q *Queries) CreateVehicleTransfer(ctx context.Context, arg CreateVehicleTransferParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, createVehicleTransfer,
		arg.OrganizationID,
		arg.BrandID,
		arg.VehicleID,
		arg.FromUserID,
		arg.ToUserID,
		arg.ToPhone,
		arg.FromCodeHash,
		arg.ToCodeHash,
		arg.ExpiresAt,
		arg.InitiatedByUserID,
	)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWarrantyForServiceItem = `-- name: CreateWarrantyForServiceItem :one


INSERT INTO warranties (
    organization_id, brand_id, service_id, service_item_id, product_id, unit_id,
    item_kind, vehicle_id, holder_user_id, start_at, end_at
)
SELECT si.organization_id, si.brand_id, si.service_id, si.id, si.product_id, si.unit_id,
       si.kind, s.vehicle_id, $1, $2, $3
FROM service_items si
JOIN services s ON s.id = si.service_id
WHERE si.id = $4
  -- TEC-230: a corrected item (unit returned to stock) gets no warranty.
  AND NOT EXISTS (SELECT 1 FROM service_item_corrections c WHERE c.service_item_id = si.id)
ON CONFLICT (service_item_id) DO NOTHING
RETURNING id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at
`

type CreateWarrantyForServiceItemParams struct {
	HolderUserID  int64              `json:"holder_user_id"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	ServiceItemID int64              `json:"service_item_id"`
}

// TEC-185 (F1-06a): warranties and vehicle ownership transfers (migration
// 000051). Panel reads are brand-bound (K20); the public lookup by
// public_code is brand-bound too (a warranty of another brand is 404).
// ---------------------------------------------------------------------------
// Warranties.
// Idempotent creation from service.completed (decision 3): the item, its
// service, organization, brand, product, unit and kind come from the
// service item; a second run returns no row (ON CONFLICT DO NOTHING).
func (q *Queries) CreateWarrantyForServiceItem(ctx context.Context, arg CreateWarrantyForServiceItemParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, createWarrantyForServiceItem,
		arg.HolderUserID,
		arg.StartAt,
		arg.EndAt,
		arg.ServiceItemID,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDueVehicleTransfers = `-- name: ExpireDueVehicleTransfers :many
UPDATE vehicle_transfers
SET status = 'expired'
WHERE status = 'pending' AND expires_at <= $1
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) ExpireDueVehicleTransfers(ctx context.Context, now pgtype.Timestamptz) ([]VehicleTransfer, error) {
	rows, err := q.db.Query(ctx, expireDueVehicleTransfers, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleTransfer{}
	for rows.Next() {
		var i VehicleTransfer
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.VehicleID,
			&i.FromUserID,
			&i.ToUserID,
			&i.ToPhone,
			&i.FromCodeHash,
			&i.ToCodeHash,
			&i.FromVerifiedAt,
			&i.ToVerifiedAt,
			&i.Attempts,
			&i.ExpiresAt,
			&i.Status,
			&i.InitiatedByUserID,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireDueWarranties = `-- name: ExpireDueWarranties :many
UPDATE warranties
SET status = 'expired', expired_at = $1
WHERE status = 'active' AND end_at <= $1
RETURNING id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at
`

// Daily cron (decision 4/5): end_at is the end of the last covered day in
// the organization's time zone, so expiry is a plain comparison.
func (q *Queries) ExpireDueWarranties(ctx context.Context, now pgtype.Timestamptz) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, expireDueWarranties, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveFullWarrantyByVehicleUnit = `-- name: GetActiveFullWarrantyByVehicleUnit :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE vehicle_id = $1 AND unit_id = $2
  AND status = 'active' AND item_kind = 'full'
`

type GetActiveFullWarrantyByVehicleUnitParams struct {
	VehicleID int64 `json:"vehicle_id"`
	UnitID    int64 `json:"unit_id"`
}

// Full-unit duplicate guard before creation (decision 3); the partial
// unique index uq_warranties_active_full_unit is the final barrier.
func (q *Queries) GetActiveFullWarrantyByVehicleUnit(ctx context.Context, arg GetActiveFullWarrantyByVehicleUnitParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, getActiveFullWarrantyByVehicleUnit, arg.VehicleID, arg.UnitID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingVehicleTransfer = `-- name: GetPendingVehicleTransfer :one
SELECT id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at FROM vehicle_transfers
WHERE vehicle_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingVehicleTransfer(ctx context.Context, vehicleID int64) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, getPendingVehicleTransfer, vehicleID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicWarrantyByCode = `-- name: GetPublicWarrantyByCode :one
SELECT w.public_code, w.status, w.start_at, w.end_at,
       p.name AS product_name,
       o.name AS organization_name, o.city AS organization_city,
       COALESCE(pr.name, '')::text AS organization_province,
       cb.uuid AS car_brand_uuid, cb.name AS car_brand_name,
       (cb.logo_object_key IS NOT NULL)::boolean AS car_brand_has_logo,
       cm.name AS car_model_name,
       s.model_year AS service_model_year, s.plate AS service_plate,
       s.plate_country AS service_plate_country, s.vin AS service_vin,
       v.model_year AS vehicle_model_year, v.plate AS vehicle_plate,
       v.plate_country AS vehicle_plate_country, v.vin AS vehicle_vin
FROM warranties w
JOIN products p ON p.id = w.product_id
JOIN organizations o ON o.id = w.organization_id
LEFT JOIN provinces pr ON pr.id = o.province_id
JOIN services s ON s.id = w.service_id
JOIN car_brands cb ON cb.id = s.car_brand_id
JOIN car_models cm ON cm.id = s.car_model_id
JOIN vehicles v ON v.id = w.vehicle_id
WHERE w.brand_id = $1::bigint
  AND (w.public_code = $2::text
       OR w.id = (SELECT a.warranty_id FROM warranty_public_code_aliases a
                  WHERE a.code = $2::text AND a.brand_id = $1::bigint))
ORDER BY (w.public_code = $2::text) DESC
LIMIT 1
`

type GetPublicWarrantyByCodeParams struct {
	BrandID    int64  `json:"brand_id"`
	PublicCode string `json:"public_code"`
}

type GetPublicWarrantyByCodeRow struct {
	PublicCode           string             `json:"public_code"`
	Status               string             `json:"status"`
	StartAt              pgtype.Timestamptz `json:"start_at"`
	EndAt                pgtype.Timestamptz `json:"end_at"`
	ProductName          string             `json:"product_name"`
	OrganizationName     string             `json:"organization_name"`
	OrganizationCity     string             `json:"organization_city"`
	OrganizationProvince string             `json:"organization_province"`
	CarBrandUuid         uuid.UUID          `json:"car_brand_uuid"`
	CarBrandName         string             `json:"car_brand_name"`
	CarBrandHasLogo      bool               `json:"car_brand_has_logo"`
	CarModelName         string             `json:"car_model_name"`
	ServiceModelYear     pgtype.Int2        `json:"service_model_year"`
	ServicePlate         pgtype.Text        `json:"service_plate"`
	ServicePlateCountry  pgtype.Text        `json:"service_plate_country"`
	ServiceVin           pgtype.Text        `json:"service_vin"`
	VehicleModelYear     pgtype.Int2        `json:"vehicle_model_year"`
	VehiclePlate         pgtype.Text        `json:"vehicle_plate"`
	VehiclePlateCountry  pgtype.Text        `json:"vehicle_plate_country"`
	VehicleVin           pgtype.Text        `json:"vehicle_vin"`
}

// Public warranty lookup (TEC-189): only the fields the public page shows.
// No users join: the holder's personal data is never read, so an anonymized
// customer's warranty answers the same way (K19). Vehicle fields come from
// the service snapshot first, then the vehicle. TEC-260: an old hub number
// merged into another warranty resolves through warranty_public_code_aliases
// to the kept warranty; the row carries that warranty's own public_code.
func (q *Queries) GetPublicWarrantyByCode(ctx context.Context, arg GetPublicWarrantyByCodeParams) (GetPublicWarrantyByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPublicWarrantyByCode, arg.BrandID, arg.PublicCode)
	var i GetPublicWarrantyByCodeRow
	err := row.Scan(
		&i.PublicCode,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.ProductName,
		&i.OrganizationName,
		&i.OrganizationCity,
		&i.OrganizationProvince,
		&i.CarBrandUuid,
		&i.CarBrandName,
		&i.CarBrandHasLogo,
		&i.CarModelName,
		&i.ServiceModelYear,
		&i.ServicePlate,
		&i.ServicePlateCountry,
		&i.ServiceVin,
		&i.VehicleModelYear,
		&i.VehiclePlate,
		&i.VehiclePlateCountry,
		&i.VehicleVin,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, uuid, user_id, organization_id, brand_id, car_brand_id, car_model_id, model_year, plate, plate_normalized, plate_country, vin, created_at, updated_at, deleted_at, fleet_org_id FROM vehicles
WHERE id = $1
`

// Vehicle of a transfer (TEC-190): scope check and response of the verify /
// cancel endpoints, which address the transfer, not the vehicle.
func (q *Queries) GetVehicleByID(ctx context.Context, id int64) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.OrganizationID,
		&i.BrandID,
		&i.CarBrandID,
		&i.CarModelID,
		&i.ModelYear,
		&i.Plate,
		&i.PlateNormalized,
		&i.PlateCountry,
		&i.Vin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FleetOrgID,
	)
	return i, err
}

const getVehicleTransfer = `-- name: GetVehicleTransfer :one
SELECT id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at FROM vehicle_transfers
WHERE id = $1 AND brand_id = $2
`

type GetVehicleTransferParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) GetVehicleTransfer(ctx context.Context, arg GetVehicleTransferParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, getVehicleTransfer, arg.ID, arg.BrandID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleTransferByUUID = `-- name: GetVehicleTransferByUUID :one
SELECT id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at FROM vehicle_transfers
WHERE uuid = $1 AND brand_id = $2
`

type GetVehicleTransferByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetVehicleTransferByUUID(ctx context.Context, arg GetVehicleTransferByUUIDParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, getVehicleTransferByUUID, arg.Uuid, arg.BrandID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarranty = `-- name: GetWarranty :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE id = $1 AND brand_id = $2
`

type GetWarrantyParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) GetWarranty(ctx context.Context, arg GetWarrantyParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, getWarranty, arg.ID, arg.BrandID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarrantyByPublicCode = `-- name: GetWarrantyByPublicCode :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE public_code = $1 AND brand_id = $2
`

type GetWarrantyByPublicCodeParams struct {
	PublicCode string `json:"public_code"`
	BrandID    int64  `json:"brand_id"`
}

// Public page /garanti/{public_code} (decision 1).
func (q *Queries) GetWarrantyByPublicCode(ctx context.Context, arg GetWarrantyByPublicCodeParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByPublicCode, arg.PublicCode, arg.BrandID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarrantyByServiceItem = `-- name: GetWarrantyByServiceItem :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE service_item_id = $1
`

func (q *Queries) GetWarrantyByServiceItem(ctx context.Context, serviceItemID int64) (Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByServiceItem, serviceItemID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarrantyByUUID = `-- name: GetWarrantyByUUID :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE uuid = $1 AND brand_id = $2
`

type GetWarrantyByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) GetWarrantyByUUID(ctx context.Context, arg GetWarrantyByUUIDParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, getWarrantyByUUID, arg.Uuid, arg.BrandID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarrantyServiceContext = `-- name: GetWarrantyServiceContext :one
SELECT s.id, s.uuid, s.service_no, s.status, s.organization_id, s.brand_id, s.vehicle_id,
       s.customer_user_id, s.completed_at, o.timezone, b.slug AS brand_slug
FROM services s
JOIN organizations o ON o.id = s.organization_id
JOIN brands b ON b.id = s.brand_id
WHERE s.id = $1
`

type GetWarrantyServiceContextRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	ServiceNo      string             `json:"service_no"`
	Status         string             `json:"status"`
	OrganizationID int64              `json:"organization_id"`
	BrandID        int64              `json:"brand_id"`
	VehicleID      int64              `json:"vehicle_id"`
	CustomerUserID int64              `json:"customer_user_id"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Timezone       string             `json:"timezone"`
	BrandSlug      string             `json:"brand_slug"`
}

// service.completed consumer (TEC-186): the service, its organization's
// time zone (end_at is the end of the last day there, decision 4) and its
// brand slug (Glorian services get no warranty, K2).
func (q *Queries) GetWarrantyServiceContext(ctx context.Context, serviceID int64) (GetWarrantyServiceContextRow, error) {
	row := q.db.QueryRow(ctx, getWarrantyServiceContext, serviceID)
	var i GetWarrantyServiceContextRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ServiceNo,
		&i.Status,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.CustomerUserID,
		&i.CompletedAt,
		&i.Timezone,
		&i.BrandSlug,
	)
	return i, err
}

const incrementVehicleTransferAttempts = `-- name: IncrementVehicleTransferAttempts :one
UPDATE vehicle_transfers
SET attempts = attempts + 1
WHERE id = $1 AND status = 'pending'
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

// A wrong code: one more attempt (the use case cancels at the limit).
func (q *Queries) IncrementVehicleTransferAttempts(ctx context.Context, id int64) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, incrementVehicleTransferAttempts, id)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVehicleTransfersByVehicle = `-- name: ListVehicleTransfersByVehicle :many
SELECT id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at FROM vehicle_transfers
WHERE vehicle_id = $1 AND brand_id = $2
ORDER BY created_at DESC, id DESC
`

type ListVehicleTransfersByVehicleParams struct {
	VehicleID int64 `json:"vehicle_id"`
	BrandID   int64 `json:"brand_id"`
}

func (q *Queries) ListVehicleTransfersByVehicle(ctx context.Context, arg ListVehicleTransfersByVehicleParams) ([]VehicleTransfer, error) {
	rows, err := q.db.Query(ctx, listVehicleTransfersByVehicle, arg.VehicleID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleTransfer{}
	for rows.Next() {
		var i VehicleTransfer
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.BrandID,
			&i.VehicleID,
			&i.FromUserID,
			&i.ToUserID,
			&i.ToPhone,
			&i.FromCodeHash,
			&i.ToCodeHash,
			&i.FromVerifiedAt,
			&i.ToVerifiedAt,
			&i.Attempts,
			&i.ExpiresAt,
			&i.Status,
			&i.InitiatedByUserID,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesByService = `-- name: ListWarrantiesByService :many
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE service_id = $1 AND brand_id = $2
ORDER BY id
`

type ListWarrantiesByServiceParams struct {
	ServiceID int64 `json:"service_id"`
	BrandID   int64 `json:"brand_id"`
}

// All warranties of a service (one PDF per service, decision 2).
func (q *Queries) ListWarrantiesByService(ctx context.Context, arg ListWarrantiesByServiceParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, listWarrantiesByService, arg.ServiceID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesByVehicle = `-- name: ListWarrantiesByVehicle :many
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE vehicle_id = $1 AND brand_id = $2
ORDER BY start_at DESC, id DESC
`

type ListWarrantiesByVehicleParams struct {
	VehicleID int64 `json:"vehicle_id"`
	BrandID   int64 `json:"brand_id"`
}

func (q *Queries) ListWarrantiesByVehicle(ctx context.Context, arg ListWarrantiesByVehicleParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, listWarrantiesByVehicle, arg.VehicleID, arg.BrandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesDue30DayNotice = `-- name: ListWarrantiesDue30DayNotice :many
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE status = 'active' AND notified_30_at IS NULL
  AND end_at > $1
  AND end_at <= $1::timestamptz + INTERVAL '30 days'
ORDER BY end_at, id
LIMIT $2
`

type ListWarrantiesDue30DayNoticeParams struct {
	Now      pgtype.Timestamptz `json:"now"`
	RowLimit int32              `json:"row_limit"`
}

// Reminder scan, 30 days: active warranties ending within 30 days that were
// not notified yet (a missed day is caught up by the <= condition).
func (q *Queries) ListWarrantiesDue30DayNotice(ctx context.Context, arg ListWarrantiesDue30DayNoticeParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, listWarrantiesDue30DayNotice, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesDue7DayNotice = `-- name: ListWarrantiesDue7DayNotice :many
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE status = 'active' AND notified_7_at IS NULL
  AND end_at > $1
  AND end_at <= $1::timestamptz + INTERVAL '7 days'
ORDER BY end_at, id
LIMIT $2
`

type ListWarrantiesDue7DayNoticeParams struct {
	Now      pgtype.Timestamptz `json:"now"`
	RowLimit int32              `json:"row_limit"`
}

func (q *Queries) ListWarrantiesDue7DayNotice(ctx context.Context, arg ListWarrantiesDue7DayNoticeParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, listWarrantiesDue7DayNotice, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesInScope = `-- name: ListWarrantiesInScope :many
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE brand_id = $1
  AND ($2::bigint[] IS NULL OR organization_id = ANY ($2::bigint[]))
  AND ($3::bigint IS NULL OR holder_user_id = $3)
  AND ($4::bigint IS NULL OR vehicle_id = $4)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY end_at DESC, id DESC
LIMIT $7 OFFSET $6
`

type ListWarrantiesInScopeParams struct {
	BrandID      int64       `json:"brand_id"`
	OrgIds       []int64     `json:"org_ids"`
	HolderUserID pgtype.Int8 `json:"holder_user_id"`
	VehicleID    pgtype.Int8 `json:"vehicle_id"`
	Status       pgtype.Text `json:"status"`
	RowOffset    int32       `json:"row_offset"`
	RowLimit     int32       `json:"row_limit"`
}

// Scope list: org_ids NULL = whole brand (brand/all scope);
// holder_user_id for scope customer (portal).
func (q *Queries) ListWarrantiesInScope(ctx context.Context, arg ListWarrantiesInScopeParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, listWarrantiesInScope,
		arg.BrandID,
		arg.OrgIds,
		arg.HolderUserID,
		arg.VehicleID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantyCandidatesByService = `-- name: ListWarrantyCandidatesByService :many
SELECT si.id, si.kind, si.product_id, si.unit_id,
       p.warranty_duration_months,
       u.source AS unit_source, u.connection_id AS unit_connection_id,
       ub.slug AS unit_brand_slug,
       EXISTS (
           SELECT 1 FROM stock_movements m
           WHERE m.unit_id = si.unit_id AND m.type = 'external_outbound'
       )::boolean AS external_outbound
FROM service_items si
JOIN products p ON p.id = si.product_id
JOIN units u ON u.id = si.unit_id
JOIN brands ub ON ub.id = u.brand_id
WHERE si.service_id = $1
  -- TEC-230: corrected items (unit returned to stock) get no warranty.
  AND NOT EXISTS (SELECT 1 FROM service_item_corrections c WHERE c.service_item_id = si.id)
ORDER BY si.id
`

type ListWarrantyCandidatesByServiceRow struct {
	ID                     int64       `json:"id"`
	Kind                   string      `json:"kind"`
	ProductID              int64       `json:"product_id"`
	UnitID                 int64       `json:"unit_id"`
	WarrantyDurationMonths pgtype.Int4 `json:"warranty_duration_months"`
	UnitSource             string      `json:"unit_source"`
	UnitConnectionID       pgtype.Int8 `json:"unit_connection_id"`
	UnitBrandSlug          string      `json:"unit_brand_slug"`
	ExternalOutbound       bool        `json:"external_outbound"`
}

// One row per service item with what the warranty rules need: the
// product's warranty period (NULL/0 = none), the unit's source, external
// connection and brand, and whether the unit ever left the system through
// an external_outbound movement (no warranty for those, K2).
func (q *Queries) ListWarrantyCandidatesByService(ctx context.Context, serviceID int64) ([]ListWarrantyCandidatesByServiceRow, error) {
	rows, err := q.db.Query(ctx, listWarrantyCandidatesByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarrantyCandidatesByServiceRow{}
	for rows.Next() {
		var i ListWarrantyCandidatesByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProductID,
			&i.UnitID,
			&i.WarrantyDurationMonths,
			&i.UnitSource,
			&i.UnitConnectionID,
			&i.UnitBrandSlug,
			&i.ExternalOutbound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantyCertificateItems = `-- name: ListWarrantyCertificateItems :many
SELECT w.id, w.uuid, w.public_code, w.item_kind, w.start_at, w.end_at, w.holder_user_id,
       p.name AS product_name, p.sku AS product_sku,
       u.barcode AS unit_barcode, si.meters
FROM warranties w
JOIN products p ON p.id = w.product_id
JOIN units u ON u.id = w.unit_id
JOIN service_items si ON si.id = w.service_item_id
WHERE w.service_id = $1 AND w.brand_id = $2 AND w.status = 'active'
  AND ($3::bigint IS NULL OR w.holder_user_id = $3::bigint)
ORDER BY w.id
`

type ListWarrantyCertificateItemsParams struct {
	ServiceID    int64       `json:"service_id"`
	BrandID      int64       `json:"brand_id"`
	HolderUserID pgtype.Int8 `json:"holder_user_id"`
}

type ListWarrantyCertificateItemsRow struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	PublicCode   string             `json:"public_code"`
	ItemKind     string             `json:"item_kind"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	EndAt        pgtype.Timestamptz `json:"end_at"`
	HolderUserID int64              `json:"holder_user_id"`
	ProductName  string             `json:"product_name"`
	ProductSku   string             `json:"product_sku"`
	UnitBarcode  string             `json:"unit_barcode"`
	Meters       pgtype.Numeric     `json:"meters"`
}

// Warranty certificate (TEC-188, one PDF per service, decision 2): the
// active warranties of a service with the covered product, unit and item.
// holder_user_id narrows to the portal customer's own warranties (a
// transferred vehicle's warranties belong to the new holder).
func (q *Queries) ListWarrantyCertificateItems(ctx context.Context, arg ListWarrantyCertificateItemsParams) ([]ListWarrantyCertificateItemsRow, error) {
	rows, err := q.db.Query(ctx, listWarrantyCertificateItems, arg.ServiceID, arg.BrandID, arg.HolderUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarrantyCertificateItemsRow{}
	for rows.Next() {
		var i ListWarrantyCertificateItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.ItemKind,
			&i.StartAt,
			&i.EndAt,
			&i.HolderUserID,
			&i.ProductName,
			&i.ProductSku,
			&i.UnitBarcode,
			&i.Meters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantyNoticeContexts = `-- name: ListWarrantyNoticeContexts :many
SELECT w.id, v.plate, p.name AS product_name, o.name AS organization_name, o.timezone
FROM warranties w
JOIN vehicles v ON v.id = w.vehicle_id
JOIN products p ON p.id = w.product_id
JOIN organizations o ON o.id = w.organization_id
WHERE w.id = ANY ($1::bigint[])
`

type ListWarrantyNoticeContextsRow struct {
	ID               int64       `json:"id"`
	Plate            pgtype.Text `json:"plate"`
	ProductName      string      `json:"product_name"`
	OrganizationName string      `json:"organization_name"`
	Timezone         string      `json:"timezone"`
}

// Notification context of the cron events (TEC-187): plate, product and the
// organization's name and time zone (end date is shown in the org zone).
func (q *Queries) ListWarrantyNoticeContexts(ctx context.Context, ids []int64) ([]ListWarrantyNoticeContextsRow, error) {
	rows, err := q.db.Query(ctx, listWarrantyNoticeContexts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarrantyNoticeContextsRow{}
	for rows.Next() {
		var i ListWarrantyNoticeContextsRow
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.ProductName,
			&i.OrganizationName,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantyRepairCandidates = `-- name: ListWarrantyRepairCandidates :many
WITH page AS (
    SELECT s.id
    FROM services s
    WHERE s.status = 'completed'
      AND s.completed_at >= $1
      AND s.completed_at <= $2
      AND s.id > $3::bigint
      AND ($4::bigint = 0 OR s.organization_id = $4::bigint)
      -- TEC-260: a service the migrator brought over already completed is
      -- legacy data; its items were left without a warranty on purpose
      -- (or skipped with warranty_skipped_*), so the scan must not open
      -- one. A migrated service completed in the new app after its
      -- migration stays in scope. idx_migration_map_target covers it.
      AND NOT EXISTS (
          SELECT 1 FROM migration_map mm
          WHERE mm.target_table = 'services'
            AND mm.target_uuid = s.uuid
            AND s.completed_at <= mm.migrated_at
      )
      AND EXISTS (
          SELECT 1 FROM service_items si
          WHERE si.service_id = s.id
            AND NOT EXISTS (SELECT 1 FROM warranties w WHERE w.service_item_id = si.id)
            AND NOT EXISTS (SELECT 1 FROM service_item_corrections c WHERE c.service_item_id = si.id)
      )
    ORDER BY s.id
    LIMIT $5
)
SELECT s.id AS service_id, b.slug AS service_brand_slug,
       si.id, si.kind, si.product_id, si.unit_id,
       p.warranty_duration_months,
       u.source AS unit_source, u.connection_id AS unit_connection_id,
       ub.slug AS unit_brand_slug,
       EXISTS (
           SELECT 1 FROM stock_movements m
           WHERE m.unit_id = si.unit_id AND m.type = 'external_outbound'
       )::boolean AS external_outbound
FROM page
JOIN services s ON s.id = page.id
JOIN brands b ON b.id = s.brand_id
JOIN service_items si ON si.service_id = s.id
JOIN products p ON p.id = si.product_id
JOIN units u ON u.id = si.unit_id
JOIN brands ub ON ub.id = u.brand_id
WHERE NOT EXISTS (SELECT 1 FROM warranties w WHERE w.service_item_id = si.id)
  AND NOT EXISTS (SELECT 1 FROM service_item_corrections c WHERE c.service_item_id = si.id)
ORDER BY s.id, si.id
`

type ListWarrantyRepairCandidatesParams struct {
	Since          pgtype.Timestamptz `json:"since"`
	Until          pgtype.Timestamptz `json:"until"`
	AfterServiceID int64              `json:"after_service_id"`
	OrganizationID int64              `json:"organization_id"`
	ServiceLimit   int32              `json:"service_limit"`
}

type ListWarrantyRepairCandidatesRow struct {
	ServiceID              int64       `json:"service_id"`
	ServiceBrandSlug       string      `json:"service_brand_slug"`
	ID                     int64       `json:"id"`
	Kind                   string      `json:"kind"`
	ProductID              int64       `json:"product_id"`
	UnitID                 int64       `json:"unit_id"`
	WarrantyDurationMonths pgtype.Int4 `json:"warranty_duration_months"`
	UnitSource             string      `json:"unit_source"`
	UnitConnectionID       pgtype.Int8 `json:"unit_connection_id"`
	UnitBrandSlug          string      `json:"unit_brand_slug"`
	ExternalOutbound       bool        `json:"external_outbound"`
}

// TEC-194: repair scan. One page of completed services (completed in
// [since, until], id > after_service_id, organization_id = 0 for all) that
// still have an item without a warranty, with the same eligibility columns
// as ListWarrantyCandidatesByService for those items. The page is cut by
// service, so every missing item of a listed service is returned.
func (q *Queries) ListWarrantyRepairCandidates(ctx context.Context, arg ListWarrantyRepairCandidatesParams) ([]ListWarrantyRepairCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listWarrantyRepairCandidates,
		arg.Since,
		arg.Until,
		arg.AfterServiceID,
		arg.OrganizationID,
		arg.ServiceLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarrantyRepairCandidatesRow{}
	for rows.Next() {
		var i ListWarrantyRepairCandidatesRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.ServiceBrandSlug,
			&i.ID,
			&i.Kind,
			&i.ProductID,
			&i.UnitID,
			&i.WarrantyDurationMonths,
			&i.UnitSource,
			&i.UnitConnectionID,
			&i.UnitBrandSlug,
			&i.ExternalOutbound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVehicleTransferByUUID = `-- name: LockVehicleTransferByUUID :one
SELECT id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at FROM vehicle_transfers
WHERE uuid = $1 AND brand_id = $2
FOR UPDATE
`

type LockVehicleTransferByUUIDParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	BrandID int64     `json:"brand_id"`
}

func (q *Queries) LockVehicleTransferByUUID(ctx context.Context, arg LockVehicleTransferByUUIDParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, lockVehicleTransferByUUID, arg.Uuid, arg.BrandID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWarranty = `-- name: LockWarranty :one
SELECT id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at FROM warranties
WHERE id = $1 AND brand_id = $2
FOR UPDATE
`

type LockWarrantyParams struct {
	ID      int64 `json:"id"`
	BrandID int64 `json:"brand_id"`
}

func (q *Queries) LockWarranty(ctx context.Context, arg LockWarrantyParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, lockWarranty, arg.ID, arg.BrandID)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWarrantyNotified30 = `-- name: MarkWarrantyNotified30 :execrows
UPDATE warranties
SET notified_30_at = $1
WHERE id = $2 AND status = 'active' AND notified_30_at IS NULL
`

type MarkWarrantyNotified30Params struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  int64              `json:"id"`
}

// Stamped in the notification transaction; a second run is a no-op.
func (q *Queries) MarkWarrantyNotified30(ctx context.Context, arg MarkWarrantyNotified30Params) (int64, error) {
	result, err := q.db.Exec(ctx, markWarrantyNotified30, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWarrantyNotified7 = `-- name: MarkWarrantyNotified7 :execrows
UPDATE warranties
SET notified_7_at = $1
WHERE id = $2 AND status = 'active' AND notified_7_at IS NULL
`

type MarkWarrantyNotified7Params struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  int64              `json:"id"`
}

func (q *Queries) MarkWarrantyNotified7(ctx context.Context, arg MarkWarrantyNotified7Params) (int64, error) {
	result, err := q.db.Exec(ctx, markWarrantyNotified7, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrganizationGoogleBusinessURL = `-- name: SetOrganizationGoogleBusinessURL :one

UPDATE organizations
SET google_business_url = $1
WHERE id = $2
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color, type, parent_id, brand_id, currency, locale, timezone, country_id, contract_pdf_key, contract_valid_until, settings, province_id, district_id, phone_raw, google_business_url, latitude, longitude, invoice_vkn, invoice_tckn, invoice_tax_office, invoice_legal_name, einvoice_registered, einvoice_alias, invoice_email
`

type SetOrganizationGoogleBusinessURLParams struct {
	GoogleBusinessUrl pgtype.Text `json:"google_business_url"`
	ID                int64       `json:"id"`
}

// ---------------------------------------------------------------------------
// Organization Google Business link (decision 7).
func (q *Queries) SetOrganizationGoogleBusinessURL(ctx context.Context, arg SetOrganizationGoogleBusinessURLParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationGoogleBusinessURL, arg.GoogleBusinessUrl, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
		&i.Type,
		&i.ParentID,
		&i.BrandID,
		&i.Currency,
		&i.Locale,
		&i.Timezone,
		&i.CountryID,
		&i.ContractPdfKey,
		&i.ContractValidUntil,
		&i.Settings,
		&i.ProvinceID,
		&i.DistrictID,
		&i.PhoneRaw,
		&i.GoogleBusinessUrl,
		&i.Latitude,
		&i.Longitude,
		&i.InvoiceVkn,
		&i.InvoiceTckn,
		&i.InvoiceTaxOffice,
		&i.InvoiceLegalName,
		&i.EinvoiceRegistered,
		&i.EinvoiceAlias,
		&i.InvoiceEmail,
	)
	return i, err
}

const setVehicleOwner = `-- name: SetVehicleOwner :one
UPDATE vehicles
SET user_id = $1
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, uuid, user_id, organization_id, brand_id, car_brand_id, car_model_id, model_year, plate, plate_normalized, plate_country, vin, created_at, updated_at, deleted_at, fleet_org_id
`

type SetVehicleOwnerParams struct {
	NewUserID int64 `json:"new_user_id"`
	ID        int64 `json:"id"`
	OldUserID int64 `json:"old_user_id"`
}

// Vehicle owner change in the transfer transaction (services keep their
// customer snapshot, 000050).
func (q *Queries) SetVehicleOwner(ctx context.Context, arg SetVehicleOwnerParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, setVehicleOwner, arg.NewUserID, arg.ID, arg.OldUserID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.OrganizationID,
		&i.BrandID,
		&i.CarBrandID,
		&i.CarModelID,
		&i.ModelYear,
		&i.Plate,
		&i.PlateNormalized,
		&i.PlateCountry,
		&i.Vin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FleetOrgID,
	)
	return i, err
}

const setVehicleTransferVerified = `-- name: SetVehicleTransferVerified :one
UPDATE vehicle_transfers
SET from_verified_at = CASE WHEN $1::boolean THEN COALESCE(from_verified_at, NOW()) ELSE from_verified_at END,
    to_verified_at = CASE WHEN $2::boolean THEN COALESCE(to_verified_at, NOW()) ELSE to_verified_at END
WHERE id = $3 AND status = 'pending'
RETURNING id, uuid, organization_id, brand_id, vehicle_id, from_user_id, to_user_id, to_phone, from_code_hash, to_code_hash, from_verified_at, to_verified_at, attempts, expires_at, status, initiated_by_user_id, completed_at, cancelled_at, created_at, updated_at
`

type SetVehicleTransferVerifiedParams struct {
	FromSide bool  `json:"from_side"`
	ToSide   bool  `json:"to_side"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetVehicleTransferVerified(ctx context.Context, arg SetVehicleTransferVerifiedParams) (VehicleTransfer, error) {
	row := q.db.QueryRow(ctx, setVehicleTransferVerified, arg.FromSide, arg.ToSide, arg.ID)
	var i VehicleTransfer
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.VehicleID,
		&i.FromUserID,
		&i.ToUserID,
		&i.ToPhone,
		&i.FromCodeHash,
		&i.ToCodeHash,
		&i.FromVerifiedAt,
		&i.ToVerifiedAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.Status,
		&i.InitiatedByUserID,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidWarrantiesByService = `-- name: VoidWarrantiesByService :many
UPDATE warranties
SET status = 'void',
    voided_at = NOW(),
    voided_by_user_id = $1,
    void_reason = $2
WHERE service_id = $3
  AND brand_id = $4
  AND status IN ('active', 'expired')
RETURNING id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at
`

type VoidWarrantiesByServiceParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	VoidReason  pgtype.Text `json:"void_reason"`
	ServiceID   int64       `json:"service_id"`
	BrandID     int64       `json:"brand_id"`
}

func (q *Queries) VoidWarrantiesByService(ctx context.Context, arg VoidWarrantiesByServiceParams) ([]Warranty, error) {
	rows, err := q.db.Query(ctx, voidWarrantiesByService,
		arg.ActorUserID,
		arg.VoidReason,
		arg.ServiceID,
		arg.BrandID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warranty{}
	for rows.Next() {
		var i Warranty
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PublicCode,
			&i.OrganizationID,
			&i.BrandID,
			&i.ServiceID,
			&i.ServiceItemID,
			&i.ProductID,
			&i.UnitID,
			&i.ItemKind,
			&i.VehicleID,
			&i.HolderUserID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.ExpiredAt,
			&i.VoidedAt,
			&i.VoidedByUserID,
			&i.VoidReason,
			&i.Notified30At,
			&i.Notified7At,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidWarranty = `-- name: VoidWarranty :one
UPDATE warranties
SET status = 'void',
    voided_at = NOW(),
    voided_by_user_id = $1,
    void_reason = $2
WHERE id = $3 AND brand_id = $4 AND status IN ('active', 'expired')
RETURNING id, uuid, public_code, organization_id, brand_id, service_id, service_item_id, product_id, unit_id, item_kind, vehicle_id, holder_user_id, start_at, end_at, status, expired_at, voided_at, voided_by_user_id, void_reason, notified_30_at, notified_7_at, created_at, updated_at
`

type VoidWarrantyParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	VoidReason  pgtype.Text `json:"void_reason"`
	ID          int64       `json:"id"`
	BrandID     int64       `json:"brand_id"`
}

// Center void (warranties.void). Expired warranties may be voided too.
func (q *Queries) VoidWarranty(ctx context.Context, arg VoidWarrantyParams) (Warranty, error) {
	row := q.db.QueryRow(ctx, voidWarranty,
		arg.ActorUserID,
		arg.VoidReason,
		arg.ID,
		arg.BrandID,
	)
	var i Warranty
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PublicCode,
		&i.OrganizationID,
		&i.BrandID,
		&i.ServiceID,
		&i.ServiceItemID,
		&i.ProductID,
		&i.UnitID,
		&i.ItemKind,
		&i.VehicleID,
		&i.HolderUserID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.ExpiredAt,
		&i.VoidedAt,
		&i.VoidedByUserID,
		&i.VoidReason,
		&i.Notified30At,
		&i.Notified7At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
