// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: whatsapp_visitor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationModelRunsSince = `-- name: CountConversationModelRunsSince :one

SELECT COUNT(*)::bigint
FROM conversation_ai_runs
WHERE conversation_id = $1
  AND model <> ''
  AND started_at >= $2::timestamptz
`

type CountConversationModelRunsSinceParams struct {
	ConversationID int64              `json:"conversation_id"`
	Since          pgtype.Timestamptz `json:"since"`
}

// TEC-397 (F4-02e): WhatsApp visitor flow — abuse limits, the KVKK notice
// before a lead, the 30 day lead window and the address of a visitor lead.
// AI runs of a conversation since a time that called the model (a fixed
// reply without a model call is not a turn).
func (q *Queries) CountConversationModelRunsSince(ctx context.Context, arg CountConversationModelRunsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationModelRunsSince, arg.ConversationID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countConversationRunsWithStageBefore = `-- name: CountConversationRunsWithStageBefore :one
SELECT COUNT(*)::bigint
FROM conversation_ai_runs
WHERE conversation_id = $1
  AND id < $2::bigint
  AND started_at >= $3::timestamptz
  AND stages @> jsonb_build_array(jsonb_build_object('stage', $4::text))
`

type CountConversationRunsWithStageBeforeParams struct {
	ConversationID int64              `json:"conversation_id"`
	BeforeRunID    int64              `json:"before_run_id"`
	Since          pgtype.Timestamptz `json:"since"`
	Stage          string             `json:"stage"`
}

// Earlier AI runs (id below before_run_id) of a conversation since a time
// that recorded a stage (e.g. the KVKK notice of a visitor lead).
func (q *Queries) CountConversationRunsWithStageBefore(ctx context.Context, arg CountConversationRunsWithStageBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationRunsWithStageBefore,
		arg.ConversationID,
		arg.BeforeRunID,
		arg.Since,
		arg.Stage,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findDistrictByName = `-- name: FindDistrictByName :one
SELECT id, province_id, code, name, created_at FROM districts
WHERE province_id = $1
  AND lower(translate(name, 'İIıŞşĞğÜüÖöÇç', 'iiissgguuoocc')) = lower(translate($2::text, 'İIıŞşĞğÜüÖöÇç', 'iiissgguuoocc'))
ORDER BY id
LIMIT 1
`

type FindDistrictByNameParams struct {
	ProvinceID int64  `json:"province_id"`
	Name       string `json:"name"`
}

// A district of a province by name, case- and Turkish-accent-insensitively.
func (q *Queries) FindDistrictByName(ctx context.Context, arg FindDistrictByNameParams) (District, error) {
	row := q.db.QueryRow(ctx, findDistrictByName, arg.ProvinceID, arg.Name)
	var i District
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const findProvinceByName = `-- name: FindProvinceByName :one
SELECT p.id, p.country_id, p.code, p.name, p.created_at
FROM provinces p
JOIN countries c ON c.id = p.country_id
WHERE c.is_active
  AND lower(translate(p.name, 'İIıŞşĞğÜüÖöÇç', 'iiissgguuoocc')) = lower(translate($1::text, 'İIıŞşĞğÜüÖöÇç', 'iiissgguuoocc'))
ORDER BY (c.iso2 = 'TR') DESC, p.id
LIMIT 1
`

// A province of an active country by name, case- and Turkish-accent-
// insensitively; Turkey first when several countries have the name.
func (q *Queries) FindProvinceByName(ctx context.Context, name string) (Province, error) {
	row := q.db.QueryRow(ctx, findProvinceByName, name)
	var i Province
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentWhatsAppVisitorLead = `-- name: GetRecentWhatsAppVisitorLead :one
SELECT id, uuid, organization_id, brand_id, target_type, customer_user_id, vehicle_id, candidate_company_name, candidate_contact_name, candidate_phone_e164, candidate_email, country_id, province_id, district_id, source, temperature, status, lost_reason, follow_up_date, assignee_user_id, notes, won_ref_type, won_ref_id, created_by_user_id, created_at, updated_at, deleted_at FROM leads
WHERE brand_id = $1
  AND candidate_phone_e164 = $2
  AND source = 'whatsapp'
  AND target_type = 'customer'
  AND deleted_at IS NULL
  AND created_at >= $3::timestamptz
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetRecentWhatsAppVisitorLeadParams struct {
	BrandID   int64              `json:"brand_id"`
	PhoneE164 pgtype.Text        `json:"phone_e164"`
	Since     pgtype.Timestamptz `json:"since"`
}

// The newest WhatsApp customer lead of a phone number in a brand since a
// time (one lead per number per 30 days).
func (q *Queries) GetRecentWhatsAppVisitorLead(ctx context.Context, arg GetRecentWhatsAppVisitorLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, getRecentWhatsAppVisitorLead, arg.BrandID, arg.PhoneE164, arg.Since)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.BrandID,
		&i.TargetType,
		&i.CustomerUserID,
		&i.VehicleID,
		&i.CandidateCompanyName,
		&i.CandidateContactName,
		&i.CandidatePhoneE164,
		&i.CandidateEmail,
		&i.CountryID,
		&i.ProvinceID,
		&i.DistrictID,
		&i.Source,
		&i.Temperature,
		&i.Status,
		&i.LostReason,
		&i.FollowUpDate,
		&i.AssigneeUserID,
		&i.Notes,
		&i.WonRefType,
		&i.WonRefID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const sumVisitorWhatsAppTokensSince = `-- name: SumVisitorWhatsAppTokensSince :one
SELECT COALESCE(SUM(quota_tokens), 0)::bigint
FROM ai_usage
WHERE organization_id = $1
  AND pool = 'system'
  AND channel = 'whatsapp'
  AND user_id IS NULL
  AND created_at >= $2::timestamptz
`

type SumVisitorWhatsAppTokensSinceParams struct {
	OrganizationID int64              `json:"organization_id"`
	Since          pgtype.Timestamptz `json:"since"`
}

// Quota tokens of unidentified WhatsApp contacts (no user) on the system
// pool of an organization since a time.
func (q *Queries) SumVisitorWhatsAppTokensSince(ctx context.Context, arg SumVisitorWhatsAppTokensSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumVisitorWhatsAppTokensSince, arg.OrganizationID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
