-- TEC-84 (F0-07): countries > provinces > districts, distributor
-- territories, licence plate formats, currencies and exchange rates.
--
-- Seed data (generated by scripts/geo-seed/generate.py, do not edit by hand):
--   countries  ISO 3166-1 (iso-codes package), Turkish names from CLDR
--   provinces  TR: 81 il (plate code), DE/NL/GR/US/UA/BG/AZ/CN/AE: ISO 3166-2
--   districts  TR: 973 ilçe (olexfilms database/data/il-ilce.json),
--              NL: gemeenten of Noord-Holland + province capitals
-- Everything else (more NL gemeenten, other countries' districts) is added by
-- the platform admin (platform.geo.write).

CREATE TABLE countries (
    id               BIGSERIAL    PRIMARY KEY,
    iso2             CHAR(2)      NOT NULL,
    iso3             CHAR(3)      NOT NULL,
    numeric_code     CHAR(3)      NOT NULL,
    name_en          VARCHAR(100) NOT NULL,
    name_tr          VARCHAR(100) NOT NULL,
    phone_code       VARCHAR(8)   NULL,
    default_currency CHAR(3)      NULL,
    default_locale   VARCHAR(8)   NULL,
    timezone         VARCHAR(64)  NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT true,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_countries_iso2 UNIQUE (iso2),
    CONSTRAINT uq_countries_iso3 UNIQUE (iso3),
    CONSTRAINT chk_countries_iso2 CHECK (iso2 ~ '^[A-Z]{2}$'),
    CONSTRAINT chk_countries_currency CHECK (default_currency IS NULL OR default_currency ~ '^[A-Z]{3}$')
);

CREATE TRIGGER trg_countries_set_updated_at
    BEFORE UPDATE ON countries
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- code: TR plate code (01..81) or the ISO 3166-2 code (NL-NH).
CREATE TABLE provinces (
    id         BIGSERIAL    PRIMARY KEY,
    country_id BIGINT       NOT NULL REFERENCES countries (id) ON DELETE CASCADE,
    code       VARCHAR(16)  NOT NULL,
    name       VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_provinces_country_code UNIQUE (country_id, code)
);

-- Names repeat inside some countries (AZ rayon and city of the same name);
-- the code is the key.
CREATE INDEX idx_provinces_country_name ON provinces (country_id, name);

CREATE TABLE districts (
    id          BIGSERIAL    PRIMARY KEY,
    province_id BIGINT       NOT NULL REFERENCES provinces (id) ON DELETE CASCADE,
    code        VARCHAR(16)  NULL,
    name        VARCHAR(120) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_districts_province_name UNIQUE (province_id, name)
);

