-- TEC-314 (F3-03c): `quote` document kind and its platform default
-- templates in the 13 UI languages. Same seed shape as 000030 (variables
-- and content_hash derived from the HTML).

ALTER TABLE document_templates DROP CONSTRAINT chk_document_templates_kind;
ALTER TABLE document_templates ADD CONSTRAINT chk_document_templates_kind CHECK (
    kind IN ('service', 'measurement', 'contract', 'order_slip', 'invoice_view', 'warranty', 'quote')
);

WITH seed (kind, language, name, html) AS (
    VALUES
    ('quote', 'tr', 'Teklif', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header>
<h1 class="doc-title">Teklif</h1>
<table class="doc-meta"><tr><th>Teklif No</th><td>{{quote_number}}</td><th>Tarih</th><td>{{document_date}}</td></tr><tr><th>Müşteri</th><td>{{customer_name}}</td><th>Geçerlilik</th><td>{{valid_until}}</td></tr><tr><th>Telefon</th><td>{{customer_phone}}</td><th>Durum</th><td>{{status}}</td></tr></table>
{{items_table}}<table class="doc-totals"><tr><th>Ara toplam</th><td>{{subtotal}}</td></tr><tr><th>İndirim</th><td>{{discount_total}}</td></tr><tr><th>Vergi</th><td>{{tax_total}}</td></tr><tr><th>Genel toplam</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'en', 'Quote', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header>
<h1 class="doc-title">Quote</h1>
<table class="doc-meta"><tr><th>Quote No</th><td>{{quote_number}}</td><th>Date</th><td>{{document_date}}</td></tr><tr><th>Customer</th><td>{{customer_name}}</td><th>Valid until</th><td>{{valid_until}}</td></tr><tr><th>Phone</th><td>{{customer_phone}}</td><th>Status</th><td>{{status}}</td></tr></table>
{{items_table}}<table class="doc-totals"><tr><th>Subtotal</th><td>{{subtotal}}</td></tr><tr><th>Discount</th><td>{{discount_total}}</td></tr><tr><th>Tax</th><td>{{tax_total}}</td></tr><tr><th>Total</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'bg', 'Оферта', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Оферта</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Дата</th><td>{{document_date}}</td></tr><tr><th>Клиент</th><td>{{customer_name}}</td><th>Валидна до</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Междинна сума</th><td>{{subtotal}}</td></tr><tr><th>Отстъпка</th><td>{{discount_total}}</td></tr><tr><th>Данък</th><td>{{tax_total}}</td></tr><tr><th>Общо</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'de', 'Angebot', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Angebot</h1><table class="doc-meta"><tr><th>Nr.</th><td>{{quote_number}}</td><th>Datum</th><td>{{document_date}}</td></tr><tr><th>Kunde</th><td>{{customer_name}}</td><th>Gültig bis</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Zwischensumme</th><td>{{subtotal}}</td></tr><tr><th>Rabatt</th><td>{{discount_total}}</td></tr><tr><th>Steuer</th><td>{{tax_total}}</td></tr><tr><th>Gesamt</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'el', 'Προσφορά', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Προσφορά</h1><table class="doc-meta"><tr><th>Αρ.</th><td>{{quote_number}}</td><th>Ημερομηνία</th><td>{{document_date}}</td></tr><tr><th>Πελάτης</th><td>{{customer_name}}</td><th>Ισχύει έως</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Υποσύνολο</th><td>{{subtotal}}</td></tr><tr><th>Έκπτωση</th><td>{{discount_total}}</td></tr><tr><th>Φόρος</th><td>{{tax_total}}</td></tr><tr><th>Σύνολο</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'uk', 'Пропозиція', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Пропозиція</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Дата</th><td>{{document_date}}</td></tr><tr><th>Клієнт</th><td>{{customer_name}}</td><th>Дійсна до</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Проміжний підсумок</th><td>{{subtotal}}</td></tr><tr><th>Знижка</th><td>{{discount_total}}</td></tr><tr><th>Податок</th><td>{{tax_total}}</td></tr><tr><th>Разом</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'ru', 'Предложение', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Предложение</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Дата</th><td>{{document_date}}</td></tr><tr><th>Клиент</th><td>{{customer_name}}</td><th>Действительно до</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Промежуточный итог</th><td>{{subtotal}}</td></tr><tr><th>Скидка</th><td>{{discount_total}}</td></tr><tr><th>Налог</th><td>{{tax_total}}</td></tr><tr><th>Итого</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'fr', 'Devis', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Devis</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Date</th><td>{{document_date}}</td></tr><tr><th>Client</th><td>{{customer_name}}</td><th>Valide jusqu'au</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Sous-total</th><td>{{subtotal}}</td></tr><tr><th>Remise</th><td>{{discount_total}}</td></tr><tr><th>Taxe</th><td>{{tax_total}}</td></tr><tr><th>Total</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'es', 'Presupuesto', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Presupuesto</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Fecha</th><td>{{document_date}}</td></tr><tr><th>Cliente</th><td>{{customer_name}}</td><th>Válido hasta</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Subtotal</th><td>{{subtotal}}</td></tr><tr><th>Descuento</th><td>{{discount_total}}</td></tr><tr><th>Impuesto</th><td>{{tax_total}}</td></tr><tr><th>Total</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'it', 'Preventivo', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Preventivo</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Data</th><td>{{document_date}}</td></tr><tr><th>Cliente</th><td>{{customer_name}}</td><th>Valido fino al</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Subtotale</th><td>{{subtotal}}</td></tr><tr><th>Sconto</th><td>{{discount_total}}</td></tr><tr><th>Imposta</th><td>{{tax_total}}</td></tr><tr><th>Totale</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'zh_CN', '报价', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">报价</h1><table class="doc-meta"><tr><th>编号</th><td>{{quote_number}}</td><th>日期</th><td>{{document_date}}</td></tr><tr><th>客户</th><td>{{customer_name}}</td><th>有效期至</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>小计</th><td>{{subtotal}}</td></tr><tr><th>折扣</th><td>{{discount_total}}</td></tr><tr><th>税额</th><td>{{tax_total}}</td></tr><tr><th>合计</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'az', 'Təklif', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">Təklif</h1><table class="doc-meta"><tr><th>No</th><td>{{quote_number}}</td><th>Tarix</th><td>{{document_date}}</td></tr><tr><th>Müştəri</th><td>{{customer_name}}</td><th>Etibarlıdır</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>Aralıq cəm</th><td>{{subtotal}}</td></tr><tr><th>Endirim</th><td>{{discount_total}}</td></tr><tr><th>Vergi</th><td>{{tax_total}}</td></tr><tr><th>Cəmi</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$),
    ('quote', 'ar', 'عرض سعر', $html$<header class="doc-header"><div class="doc-logo">{{company_logo}}</div><div class="doc-company"><strong>{{company_name}}</strong><br>{{company_address}}<br>{{company_phone}} · {{company_email}}</div></header><h1 class="doc-title">عرض سعر</h1><table class="doc-meta"><tr><th>رقم العرض</th><td>{{quote_number}}</td><th>التاريخ</th><td>{{document_date}}</td></tr><tr><th>العميل</th><td>{{customer_name}}</td><th>صالح حتى</th><td>{{valid_until}}</td></tr></table>{{items_table}}<table class="doc-totals"><tr><th>المجموع الفرعي</th><td>{{subtotal}}</td></tr><tr><th>الخصم</th><td>{{discount_total}}</td></tr><tr><th>الضريبة</th><td>{{tax_total}}</td></tr><tr><th>الإجمالي</th><td>{{total_amount}}</td></tr></table><p class="doc-footer">{{footer_text}}</p>$html$)
)
INSERT INTO document_templates (kind, brand_id, language, name, version, is_active, html, variables, content_hash, published_at)
SELECT s.kind, NULL, s.language, s.name, 1, TRUE, s.html,
       COALESCE((
           SELECT jsonb_agg(DISTINCT lower(m[1]))
           FROM regexp_matches(s.html, '\{\{\s*\.?([a-zA-Z0-9_]+)\s*\}\}', 'g') AS m
       ), '[]'::jsonb),
       encode(sha256(convert_to(s.html, 'UTF8')), 'hex'),
       NOW()
FROM seed s;
