-- TEC-464 (F4-02i): complete the seeded legal text locales for WhatsApp
-- visitors and portal consents. The existing Turkish/English rows and consent
-- history are intentionally left untouched.

INSERT INTO kvkk_notices (locale, version, body) VALUES
    ('ar', 1, 'KVKK: تتم معالجة رقم هاتفك فقط لأغراض التحقق من الهوية وإشعارات الخدمة في نطاق قانون حماية البيانات الشخصية التركي رقم 6698 (KVKK). نص الإخطار التفصيلي: olexfilms.app/kvkk'),
    ('az', 1, 'KVKK: Telefon nömrəniz yalnız şəxsiyyətin doğrulanması və xidmət bildirişləri üçün 6698 saylı Türkiyə Şəxsi Məlumatların Qorunması Qanunu (KVKK) çərçivəsində işlənir. Ətraflı məlumatlandırma mətni: olexfilms.app/kvkk'),
    ('bg', 1, 'KVKK: Вашият телефонен номер се обработва единствено за удостоверяване на самоличността и служебни уведомления съгласно турския Закон № 6698 за защита на личните данни (KVKK). Подробно уведомление: olexfilms.app/kvkk'),
    ('de', 1, 'KVKK: Ihre Telefonnummer wird ausschließlich zur Identitätsprüfung und für Servicemitteilungen im Rahmen des türkischen Gesetzes Nr. 6698 zum Schutz personenbezogener Daten (KVKK) verarbeitet. Ausführlicher Hinweis: olexfilms.app/kvkk'),
    ('el', 1, 'KVKK: Ο αριθμός τηλεφώνου σας υποβάλλεται σε επεξεργασία αποκλειστικά για επαλήθευση ταυτότητας και ειδοποιήσεις υπηρεσίας σύμφωνα με τον τουρκικό Νόμο αριθ. 6698 περί Προστασίας Δεδομένων Προσωπικού Χαρακτήρα (KVKK). Αναλυτική ενημέρωση: olexfilms.app/kvkk'),
    ('es', 1, 'KVKK: Su número de teléfono se trata únicamente para verificación de identidad y notificaciones de servicio conforme a la Ley turca n.º 6698 de Protección de Datos Personales (KVKK). Aviso informativo completo: olexfilms.app/kvkk'),
    ('fr', 1, 'KVKK : votre numéro de téléphone est traité uniquement pour la vérification d’identité et les notifications de service dans le cadre de la loi turque n° 6698 sur la protection des données personnelles (KVKK). Notice complète : olexfilms.app/kvkk'),
    ('it', 1, 'KVKK: il suo numero di telefono è trattato esclusivamente per la verifica dell’identità e per le comunicazioni di servizio ai sensi della Legge turca n. 6698 sulla protezione dei dati personali (KVKK). Informativa completa: olexfilms.app/kvkk'),
    ('ru', 1, 'KVKK: Ваш номер телефона обрабатывается исключительно для проверки личности и сервисных уведомлений в соответствии с Законом Турции № 6698 о защите персональных данных (KVKK). Подробное уведомление: olexfilms.app/kvkk'),
    ('uk', 1, 'KVKK: Ваш номер телефону обробляється виключно для підтвердження особи та сервісних повідомлень відповідно до Закону Туреччини № 6698 про захист персональних даних (KVKK). Повний текст повідомлення: olexfilms.app/kvkk'),
    ('zh-CN', 1, 'KVKK：您的电话号码仅会根据土耳其第 6698 号《个人数据保护法》（KVKK）用于身份验证和服务通知。完整告知文本：olexfilms.app/kvkk');

INSERT INTO legal_texts (kind, locale, version, body) VALUES
    ('ai_guidelines', 'ar', 1, E'## إرشادات مساعد الذكاء الاصطناعي\n\nيستخدم مساعد الذكاء الاصطناعي في البوابة سجلات الخدمة والضمان الخاصة بك للإجابة عن أسئلتك. الإجابات لأغراض إعلامية فقط؛ وللحصول على معلومات قطعية يُرجى مراجعة الوكيل الخاص بك.\n\n- لا تشارك مع المساعد بيانات صحية أو بيانات هوية أو معلومات دفع شخصية.\n- تُحفظ المحادثات لتحسين جودة الخدمة.\n- يمكنك سحب موافقتك في أي وقت من ملفك الشخصي.'),
    ('ai_guidelines', 'az', 1, E'## Süni intellekt köməkçisi üzrə təlimat\n\nPortaldakı süni intellekt köməkçisi suallarınızı cavablandırmaq üçün xidmət və zəmanət qeydlərinizdən istifadə edir. Cavablar yalnız məlumat xarakterlidir; qəti məlumat üçün dilerinizə müraciət edin.\n\n- Köməkçi ilə şəxsi sağlamlıq, şəxsiyyət və ya ödəniş məlumatları paylaşmayın.\n- Söhbətlər xidmət keyfiyyətini artırmaq üçün saxlanılır.\n- Razılığınızı istənilən vaxt profilinizdən geri götürə bilərsiniz.'),
    ('ai_guidelines', 'bg', 1, E'## Указания за AI асистента\n\nAI асистентът в портала използва вашите сервизни и гаранционни записи, за да отговаря на въпросите ви. Отговорите са само с информационна цел; за окончателна информация се обърнете към вашия дилър.\n\n- Не споделяйте с асистента лични здравни, идентификационни или платежни данни.\n- Разговорите се съхраняват с цел подобряване на качеството на услугата.\n- Можете да оттеглите съгласието си по всяко време от профила си.'),
    ('ai_guidelines', 'de', 1, E'## Richtlinie für den KI-Assistenten\n\nDer KI-Assistent im Portal nutzt Ihre Service- und Garantiedatensätze, um Ihre Fragen zu beantworten. Die Antworten dienen nur der Information; verbindliche Auskünfte erhalten Sie bei Ihrem Händler.\n\n- Teilen Sie dem Assistenten keine persönlichen Gesundheits-, Identitäts- oder Zahlungsdaten mit.\n- Gespräche werden zur Verbesserung der Servicequalität gespeichert.\n- Sie können Ihre Einwilligung jederzeit in Ihrem Profil widerrufen.'),
    ('ai_guidelines', 'el', 1, E'## Οδηγίες βοηθού τεχνητής νοημοσύνης\n\nΟ βοηθός τεχνητής νοημοσύνης στην πύλη χρησιμοποιεί τα αρχεία υπηρεσιών και εγγύησής σας για να απαντά στις ερωτήσεις σας. Οι απαντήσεις παρέχονται μόνο για ενημερωτικούς σκοπούς· για οριστικές πληροφορίες απευθυνθείτε στον αντιπρόσωπό σας.\n\n- Μην κοινοποιείτε στον βοηθό προσωπικά δεδομένα υγείας, ταυτότητας ή πληρωμής.\n- Οι συνομιλίες διατηρούνται για τη βελτίωση της ποιότητας της υπηρεσίας.\n- Μπορείτε να ανακαλέσετε τη συγκατάθεσή σας ανά πάσα στιγμή από το προφίλ σας.'),
    ('ai_guidelines', 'es', 1, E'## Directrices del asistente de IA\n\nEl asistente de IA del portal utiliza sus registros de servicio y garantía para responder a sus preguntas. Las respuestas tienen carácter informativo; para información definitiva consulte a su distribuidor.\n\n- No comparta con el asistente datos personales de salud, identidad o pago.\n- Las conversaciones se conservan para mejorar la calidad del servicio.\n- Puede retirar su consentimiento en cualquier momento desde su perfil.'),
    ('ai_guidelines', 'fr', 1, E'## Consignes de l’assistant IA\n\nL’assistant IA du portail utilise vos dossiers de service et de garantie pour répondre à vos questions. Les réponses sont fournies à titre informatif uniquement ; pour des informations définitives, veuillez consulter votre revendeur.\n\n- Ne partagez pas avec l’assistant de données personnelles de santé, d’identité ou de paiement.\n- Les conversations sont conservées afin d’améliorer la qualité du service.\n- Vous pouvez retirer votre consentement à tout moment depuis votre profil.'),
    ('ai_guidelines', 'it', 1, E'## Linee guida dell’assistente IA\n\nL’assistente IA del portale utilizza i suoi registri di servizio e garanzia per rispondere alle sue domande. Le risposte sono fornite solo a scopo informativo; per informazioni definitive si rivolga al suo rivenditore.\n\n- Non condivida con l’assistente dati personali sanitari, identificativi o di pagamento.\n- Le conversazioni sono conservate per migliorare la qualità del servizio.\n- Può revocare il consenso in qualsiasi momento dal suo profilo.'),
    ('ai_guidelines', 'ru', 1, E'## Правила использования AI-ассистента\n\nAI-ассистент на портале использует ваши записи об обслуживании и гарантии, чтобы отвечать на ваши вопросы. Ответы носят информационный характер; за окончательной информацией обращайтесь к своему дилеру.\n\n- Не передавайте ассистенту личные медицинские данные, данные личности или платежную информацию.\n- Разговоры сохраняются для повышения качества сервиса.\n- Вы можете в любое время отозвать согласие в своем профиле.'),
    ('ai_guidelines', 'uk', 1, E'## Правила користування AI-асистентом\n\nAI-асистент у порталі використовує ваші записи щодо сервісу та гарантії, щоб відповідати на ваші запитання. Відповіді мають інформаційний характер; для отримання остаточної інформації зверніться до свого дилера.\n\n- Не повідомляйте асистенту особисті медичні, ідентифікаційні або платіжні дані.\n- Розмови зберігаються для підвищення якості сервісу.\n- Ви можете будь-коли відкликати свою згоду у профілі.'),
    ('ai_guidelines', 'zh-CN', 1, E'## AI 助手指引\n\n门户中的 AI 助手会使用您的服务和保修记录来回答您的问题。回答仅供参考；如需确定信息，请咨询您的经销商。\n\n- 请勿向助手提供个人健康、身份或支付信息。\n- 对话会被保存以提升服务质量。\n- 您可随时在个人资料中撤回同意。'),
    ('marketing_consent', 'ar', 1, E'## الموافقة على الرسائل التجارية الإلكترونية\n\nأوافق على إرسال الحملات والخصومات وإعلانات المنتجات والخدمات الجديدة إليّ عبر إشعارات الدفع وWhatsApp والبريد الإلكتروني.\n\n- هذه الموافقة اختيارية؛ وعدم منحها لا يؤثر في معاملات الخدمة والضمان الخاصة بك.\n- تُرسل إشعارات الخدمة والمواعيد والضمان بشكل مستقل عن هذه الموافقة.\n- يمكنك سحب موافقتك في أي وقت من ملفك الشخصي.'),
    ('marketing_consent', 'az', 1, E'## Kommersiya elektron mesajlarına razılıq\n\nKampaniya, endirim, yeni məhsul və xidmət elanlarının mənə push bildirişi, WhatsApp və e-poçt vasitəsilə göndərilməsinə razılıq verirəm.\n\n- Bu razılıq könüllüdür; verməməyiniz xidmət və zəmanət əməliyyatlarınıza təsir etmir.\n- Xidmət, görüş və zəmanət bildirişləri bu razılıqdan asılı olmayaraq göndərilir.\n- Razılığınızı istənilən vaxt profilinizdən geri götürə bilərsiniz.'),
    ('marketing_consent', 'bg', 1, E'## Съгласие за търговски електронни съобщения\n\nСъгласявам се да получавам кампании, отстъпки и съобщения за нови продукти и услуги чрез push известия, WhatsApp и електронна поща.\n\n- Това съгласие е доброволно; отказът не засяга вашите сервизни и гаранционни операции.\n- Уведомленията за услуга, среща и гаранция се изпращат независимо от това съгласие.\n- Можете да оттеглите съгласието си по всяко време от профила си.'),
    ('marketing_consent', 'de', 1, E'## Einwilligung in kommerzielle elektronische Mitteilungen\n\nIch willige ein, Kampagnen, Rabatte sowie Ankündigungen neuer Produkte und Dienstleistungen per Push-Benachrichtigung, WhatsApp und E-Mail zu erhalten.\n\n- Diese Einwilligung ist freiwillig; eine Ablehnung beeinträchtigt Ihre Service- und Garantieabwicklungen nicht.\n- Service-, Termin- und Garantiemitteilungen werden unabhängig von dieser Einwilligung versendet.\n- Sie können Ihre Einwilligung jederzeit in Ihrem Profil widerrufen.'),
    ('marketing_consent', 'el', 1, E'## Συγκατάθεση για εμπορικά ηλεκτρονικά μηνύματα\n\nΣυμφωνώ να λαμβάνω καμπάνιες, εκπτώσεις και ανακοινώσεις νέων προϊόντων και υπηρεσιών μέσω ειδοποιήσεων push, WhatsApp και ηλεκτρονικού ταχυδρομείου.\n\n- Η συγκατάθεση αυτή είναι προαιρετική· η μη παροχή της δεν επηρεάζει τις διαδικασίες υπηρεσίας και εγγύησής σας.\n- Οι ειδοποιήσεις υπηρεσίας, ραντεβού και εγγύησης αποστέλλονται ανεξάρτητα από αυτήν τη συγκατάθεση.\n- Μπορείτε να ανακαλέσετε τη συγκατάθεσή σας ανά πάσα στιγμή από το προφίλ σας.'),
    ('marketing_consent', 'es', 1, E'## Consentimiento para comunicaciones comerciales electrónicas\n\nAcepto recibir campañas, descuentos y anuncios de nuevos productos y servicios mediante notificaciones push, WhatsApp y correo electrónico.\n\n- Este consentimiento es opcional; no otorgarlo no afecta a sus operaciones de servicio y garantía.\n- Las notificaciones de servicio, cita y garantía se envían con independencia de este consentimiento.\n- Puede retirar su consentimiento en cualquier momento desde su perfil.'),
    ('marketing_consent', 'fr', 1, E'## Consentement aux communications électroniques commerciales\n\nJ’accepte de recevoir des campagnes, remises et annonces de nouveaux produits et services par notification push, WhatsApp et e-mail.\n\n- Ce consentement est facultatif ; son refus n’affecte pas vos opérations de service et de garantie.\n- Les notifications de service, de rendez-vous et de garantie sont envoyées indépendamment de ce consentement.\n- Vous pouvez retirer votre consentement à tout moment depuis votre profil.'),
    ('marketing_consent', 'it', 1, E'## Consenso alle comunicazioni elettroniche commerciali\n\nAcconsento a ricevere campagne, sconti e annunci di nuovi prodotti e servizi tramite notifiche push, WhatsApp ed e-mail.\n\n- Questo consenso è facoltativo; il mancato consenso non influisce sulle sue operazioni di servizio e garanzia.\n- Le notifiche di servizio, appuntamento e garanzia vengono inviate indipendentemente da questo consenso.\n- Può revocare il consenso in qualsiasi momento dal suo profilo.'),
    ('marketing_consent', 'ru', 1, E'## Согласие на коммерческие электронные сообщения\n\nЯ соглашаюсь получать кампании, скидки и объявления о новых продуктах и услугах через push-уведомления, WhatsApp и электронную почту.\n\n- Это согласие является добровольным; отказ не влияет на ваши операции по обслуживанию и гарантии.\n- Уведомления об обслуживании, записи и гарантии отправляются независимо от этого согласия.\n- Вы можете в любое время отозвать согласие в своем профиле.'),
    ('marketing_consent', 'uk', 1, E'## Згода на комерційні електронні повідомлення\n\nЯ погоджуюся отримувати кампанії, знижки та оголошення про нові продукти й послуги через push-сповіщення, WhatsApp та електронну пошту.\n\n- Ця згода є добровільною; її ненадання не впливає на ваші сервісні та гарантійні операції.\n- Сервісні, записні та гарантійні повідомлення надсилаються незалежно від цієї згоди.\n- Ви можете будь-коли відкликати свою згоду у профілі.'),
    ('marketing_consent', 'zh-CN', 1, E'## 商业电子信息同意\n\n我同意通过推送通知、WhatsApp 和电子邮件接收活动、折扣以及新产品和服务公告。\n\n- 此同意为自愿；拒绝不会影响您的服务和保修事务。\n- 服务、预约和保修通知会独立于此同意发送。\n- 您可随时在个人资料中撤回同意。');
